//=====================================================================
// generated by scenegen from src/scene.js — do not edit by hand
//=====================================================================


//--- library: glsl/shapes/fractals/apollonianGasket.glsl ---
//----------------------------------------------------------------------------
// APOLLONIAN GASKET — the FRACT-fold gasket, morphed by `foldOffset`.
//
// A DIFFERENT ESTIMATOR from fractals/apollonian.glsl, not a preset of it. That
// one folds with `p -= 2*round(0.5*p)` and morphs through the inversion radius;
// this one folds with `p = -1 + 2*fract(0.5*p + foldOffset)` at a fixed scale of
// 1.5 and morphs by SHIFTING the fold each iteration. Different fold, different
// fractal — hence two files.
//
// Two things make it renderable at all. An outer sphere INVERSION maps the
// space-filling gasket into a compact blob, and its conformal factor has to be
// undone: distances measured in the inverted coordinates are stretched by
// 3/|p|^2, so the estimate is scaled back by m/3. And the result is CLIPPED to
// the unit ball, because the folded fractal is otherwise infinite.
//
// THIS ESTIMATOR NEEDS A FINE EPSILON — see scenes/apollonianGasket, which sets
// `march: {epsilon: 1e-7, maxSteps: 4000}`.
//
// It is unusually pessimistic. `res` carries a +0.2 floor so it never reaches
// zero, and `scale` diverges over the ten iterations, so the returned value is
// tiny almost EVERYWHERE inside the unit ball rather than only near the gasket.
// Measured over 200k interior points at foldOffset 0.877:
//
//     percentile     value            epsilon    fraction of the ball it "hits"
//     0.01%          9.3e-10          1e-3       97.1%   <- the engine default
//     1%             7.1e-08          1e-5       30.7%
//     25%            6.7e-06          1e-6        7.7%
//     50%            3.1e-05          1e-7        1.3%   <- what the scene uses
//     90%            3.7e-04          1e-8        0.15%
//
// At the engine default the marcher counts 97% of the ball as a hit and the
// object renders as a smooth SPHERE. That is not a bug in this file — the maths
// is the original's — it is what a distance estimator this conservative costs,
// and the per-scene `march:` key is how it is paid.
//----------------------------------------------------------------------------


// p is in the gasket's own coordinates. `radius` is the inversion radius,
// `foldOffset` shifts the fold each iteration and morphs the gasket.
float apollonianGasketDistance(vec3 p, float radius, float foldOffset){
    //the clip that makes an infinite space-filler into an object
    float ballDist = length(p) - 1.0;

    vec3 q = radius*p;

    //conformal factor of the inversion below, undone at the end
    float m = dot(q, q);

    q /= dot(q, q);
    q += vec3(1.0);
    q *= 3.0;

    float scale = 1.0;
    const float s = 1.5;

    for(int i = 0; i < 10; i++){
        q = -1.0 + 2.0*fract(0.5*q + foldOffset);

        float r2 = dot(q, q);
        float k  = s/r2;
        q     *= k;
        scale *= k;
    }

    float res  = min(abs(q.z) + abs(q.x), min(abs(q.x) + abs(q.y), abs(q.y) + abs(q.z))) + 0.2;
    float dist = 0.25*res/scale * m/3.0;

    return max(dist, ballDist);
}


// ADDED IN THE PORT. The sdf ends in max(dist, length(p) - 1), so the solid is
// contained in the unit ball and this is provably conservative — the same
// argument models/hypDod.glsl uses. The legacy had no bound, which meant every
// far-away ray paid for a 10-iteration fold loop; this skips it.
float apollonianGasketBound(vec3 p, float radius, float foldOffset){
    return length(p) - 1.0;
}


//--- library: glsl/shapes/environments/room.glsl ---
//----------------------------------------------------------------------------
// ROOM — a closed box, seen from the inside.
//
// The room is ONE region whose solid is everything OUTSIDE the box, so the
// interior is open air and regionAt() returns ID_NONE there. Its six walls are
// not six objects: they are a material FIELD over that one region, read off by
// asking which face a point is nearest. roomFace() answers that.
//
// glsl/shapes/ is the math-only library: plain functions of a point and some
// floats. No structs, no Frame, no Material.
//----------------------------------------------------------------------------


const int ROOM_FLOOR   = 0;
const int ROOM_CEILING = 1;
const int ROOM_LEFT    = 2;
const int ROOM_RIGHT   = 3;
const int ROOM_FRONT   = 4;
const int ROOM_BACK    = 5;


// p is in the room's own coordinates (origin at the box centre).
// Negative in the WALLS, positive in the open interior — the sign convention
// every other region uses, just turned inside out.
float roomDistance(vec3 p, vec3 halfSize){
    return -boxDistance(p, halfSize);
}


// Exact ray intersection, in world coordinates. The ray is inside the box, so
// this is simply the distance at which it leaves: the nearest of the three
// far slab crossings.
float roomTrace(Vector tv, vec3 centre, vec3 halfSize){
    vec3  o  = tv.pos - centre;
    vec3  tm = max((-halfSize - o)/tv.dir, (halfSize - o)/tv.dir);
    float t  = min(tm.x, min(tm.y, tm.z));
    if(t < 0.){ return maxDist; }
    return min(t, maxDist);
}


// Which wall p is on (or nearest to) — a shape DATA output (docs/shape-data.md):
// a material that reads `faceData` gets it injected. d is negative inside the
// room, so its LARGEST component names the axis the point is closest to leaving
// through, and the sign of p picks which of that axis's two faces.
int roomFaceData(vec3 p, vec3 halfSize){
    vec3 d = abs(p) - halfSize;

    if(d.y >= d.x && d.y >= d.z){
        return (p.y > 0.) ? ROOM_CEILING : ROOM_FLOOR;
    }
    if(d.x >= d.z){
        return (p.x > 0.) ? ROOM_RIGHT : ROOM_LEFT;
    }
    return (p.z > 0.) ? ROOM_BACK : ROOM_FRONT;
}


//--- the objects, in declaration order (= containment priority, inner to outer)
const int ID_GASKET = 0;
const int ID_KEY    = 1;
const int ID_ROOM   = 2;

const int N_OBJ = 3;
float gSDF[N_OBJ];


//--- placement and shape parameters ----------------------------------
const vec3  GASKET_P      = vec3(0.0, 1.8, 0.0);
const float GASKET_RADIUS = 1.0;

const vec3  KEY_P      = vec3(-8.0, 9.0, 5.0);
const float KEY_RADIUS = 2.0;

const vec3 ROOM_P        = vec3(0.0, 5.75, -5.0);
const vec3 ROOM_HALFSIZE = vec3(20.0, 8.25, 15.0);


//---------------------------------------------------------------------
// the region sdfs
//---------------------------------------------------------------------

float sdf_gasket(vec3 p){
    return apollonianGasketDistance(p - GASKET_P, GASKET_RADIUS, foldOffset);
}

float sdf_key(vec3 p){
    return sphereDistance(p - KEY_P, KEY_RADIUS);
}

//the room SOLID is everything outside the box, so its interior is open air and
//regionAt() returns ID_NONE there
float sdf_room(vec3 p){
    return roomDistance(p - ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the bounds — the acceleration structure (sdf_Scene only; sdfAll stays exact)
//---------------------------------------------------------------------

float bound_gasket(vec3 p){
    return apollonianGasketBound(p - GASKET_P, GASKET_RADIUS, foldOffset);
}


//---------------------------------------------------------------------
// the normals — the 4-tap of each region's own sdf, in world coordinates
//---------------------------------------------------------------------
const float NRM_E = 0.0002;

Vector normal_gasket(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_gasket(p + k.xyy*NRM_E) + k.yyx*sdf_gasket(p + k.yyx*NRM_E)
                              + k.yxy*sdf_gasket(p + k.yxy*NRM_E) + k.xxx*sdf_gasket(p + k.xxx*NRM_E) ));
}

Vector normal_key(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_key(p + k.xyy*NRM_E) + k.yyx*sdf_key(p + k.yyx*NRM_E)
                              + k.yxy*sdf_key(p + k.yxy*NRM_E) + k.xxx*sdf_key(p + k.xxx*NRM_E) ));
}

Vector normal_room(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_room(p + k.xyy*NRM_E) + k.yyx*sdf_room(p + k.yyx*NRM_E)
                              + k.yxy*sdf_room(p + k.yxy*NRM_E) + k.xxx*sdf_room(p + k.xxx*NRM_E) ));
}


//---------------------------------------------------------------------
// the materials
//  material_ gives the Surface plus this object's own Medium; medium_ gives
//  only the Medium, for when the object is merely the far side
//---------------------------------------------------------------------

Medium medium_gasket(vec3 p){
    Medium m = defaultMedium();
    m.ior    = 1.2;
    m.absorb = vec3(1.0, 0.415, 0.685);
    return m;
}
Material material_gasket(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //glass
    m.interior = medium_gasket(p);
    m.surf.transmit = 0.8;
    return m;
}

Material material_key(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //light
    m.surf.emit = 260.0*vec3(0.9);
    return m;
}
Medium   medium_key  (vec3 p){ return defaultMedium(); }

Material material_room(vec3 p, inout Vector n){
    vec3 q = p - ROOM_P;
    int faceData = roomFaceData(q, ROOM_HALFSIZE);
    if(faceData == ROOM_CEILING){ return makeLight(vec3(1.0), roomLight); }
    if(faceData == ROOM_FLOOR)  { return makeGloss(floorColor, 0.0, wallRough); }
    if(faceData == ROOM_LEFT)   { return makeGloss(warmColor,  0.0, wallRough); }
    if(faceData == ROOM_RIGHT)  { return makeGloss(coolColor,  0.0, wallRough); }
    return makeGloss(wallColor, 0.0, wallRough);
}
Medium medium_room(vec3 p){ return defaultMedium(); }


//---------------------------------------------------------------------
// the analytic intersections
//---------------------------------------------------------------------

float trace_key(Vector tv){
    return sphereTrace(tv, KEY_P, KEY_RADIUS);
}

float trace_room(Vector tv){
    return roomTrace(tv, ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the dispatchers
//---------------------------------------------------------------------

void sdfAll(vec3 p){
    gSDF[ID_GASKET] = sdf_gasket(p);
    gSDF[ID_KEY   ] = sdf_key(p);
    gSDF[ID_ROOM  ] = sdf_room(p);
}

Vector normalOf(int id, vec3 p){
    if(id == ID_GASKET){ return normal_gasket(p); }
    if(id == ID_KEY   ){ return normal_key(p); }
    return normal_room(p);
}

//no sheets in this scene: every object is a region with an interior
bool isSheet(int id){ return false; }

Material materialOf(int id, vec3 p, inout Vector n, bool front){
    if(id == ID_GASKET){ return material_gasket(p, n); }
    if(id == ID_KEY   ){ return material_key(p, n); }
    return material_room(p, n);
}

Medium mediumOf(int id, vec3 p){
    if(id == ID_GASKET){ return medium_gasket(p); }
    if(id == ID_KEY   ){ return medium_key(p); }
    if(id == ID_ROOM  ){ return medium_room(p); }
    return defaultMedium();      //ID_NONE: open air
}


//---------------------------------------------------------------------
// the entry points
//---------------------------------------------------------------------

void buildScene(){}

float sdf_Scene(Vector tv){
    vec3 p = tv.pos;
    float d = maxDist;

    float b_gasket = bound_gasket(p);
    d = min(d, (b_gasket > BOUND_MARGIN) ? b_gasket : sdf_gasket(p));

    return d;
}

float trace_Scene(Vector tv){
    float d = maxDist;
    d = min(d, trace_key(tv));
    d = min(d, trace_room(tv));
    return d;
}
