//=====================================================================
// generated by scenegen from src/scene.js — do not edit by hand
//=====================================================================


//--- the objects, in declaration order (= containment priority, inner to outer)
const int ID_CUBE = 0;

const int N_OBJ = 1;
float gSDF[N_OBJ];


//--- placement and shape parameters ----------------------------------
const vec3 CUBE_P        = vec3(0.0);
const vec3 CUBE_HALFSIZE = vec3(1.8);


//---------------------------------------------------------------------
// the media — a per-region varying index the ODE marcher bends light through
//---------------------------------------------------------------------

float indexField_cube(vec3 q){
    return pow(1.0 + mass/max(length(q), 1e-4), 2.0);
}

bool isMedium(int id){ return id == ID_CUBE; }

float indexFieldOf(int id, vec3 p){
    if(id == ID_CUBE){ return indexField_cube(p - CUBE_P); }
    return 1.0;   //not a medium: vacuum
}


//---------------------------------------------------------------------
// the region sdfs
//---------------------------------------------------------------------

float sdf_cube(vec3 p){
    return boxDistance(p - CUBE_P, CUBE_HALFSIZE);
}


//---------------------------------------------------------------------
// the normals — the 4-tap of each region's own sdf, in world coordinates
//---------------------------------------------------------------------
const float NRM_E = 0.0002;

Vector normal_cube(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_cube(p + k.xyy*NRM_E) + k.yyx*sdf_cube(p + k.yyx*NRM_E)
                              + k.yxy*sdf_cube(p + k.yxy*NRM_E) + k.xxx*sdf_cube(p + k.xxx*NRM_E) ));
}


//---------------------------------------------------------------------
// the materials
//  material_ gives the Surface plus this object's own Medium; medium_ gives
//  only the Medium, for when the object is merely the far side
//---------------------------------------------------------------------

Medium medium_cube(vec3 p){
    Medium m = defaultMedium();
    m.ior    = indexField_cube(p - CUBE_P);
    m.absorb = vec3(0.0);
    return m;
}
Material material_cube(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //glass
    m.interior = medium_cube(p);
    m.surf.transmit = 1.0;
    return m;
}


//---------------------------------------------------------------------
// the dispatchers
//---------------------------------------------------------------------

void sdfAll(vec3 p){
    gSDF[ID_CUBE] = sdf_cube(p);
}

Vector normalOf(int id, vec3 p){

    return normal_cube(p);
}

//no sheets in this scene: every object is a region with an interior
bool isSheet(int id){ return false; }

Material materialOf(int id, vec3 p, inout Vector n, bool front){

    return material_cube(p, n);
}

Medium mediumOf(int id, vec3 p){
    if(id == ID_CUBE){ return medium_cube(p); }
    return defaultMedium();      //ID_NONE: open air
}


//---------------------------------------------------------------------
// the entry points
//---------------------------------------------------------------------

void buildScene(){}

float sdf_Scene(Vector tv){
    vec3 p = tv.pos;
    float d = maxDist;

    d = min(d, sdf_cube(p));

    return d;
}

float trace_Scene(Vector tv){
    return maxDist;
}
