//=====================================================================
// generated by scenegen from src/scene.js — do not edit by hand
//=====================================================================


//--- library: glsl/shapes/models/bottle.glsl ---
//----------------------------------------------------------------------------
// BOTTLE — a rounded-cylinder base and neck, smooth-unioned, hollowed to a glass
// shell with the neck chopped open (and a punt dimple in the base).
//
// glsl/shapes/ is the math-only library: plain functions of a point and floats.
// Built from cylinderDistance + opSmoothUnion/Intersect/Onion (glsl/shapes/ops/,
// always compiled). `bottleCavity` is the interior surface, for a liquid region
// in a group (bottleLiquid); `bottleDistance` is the glass shell for a plain object.
//----------------------------------------------------------------------------


//the solid profile BEFORE hollowing — the shared source for the shell and the
//cavity, so the two can never drift (file-private)
float bottle_solid(vec3 p, float baseRadius, float baseHeight, float neckRadius,
                   float neckHeight, float rounded, float smoothJoin, float bump){
    float base = cylinderDistance(p, baseRadius, baseHeight, rounded);
    vec3  q    = p - vec3(0.0, baseHeight + neckHeight, 0.0);
    float neck = cylinderDistance(q, neckRadius, neckHeight, rounded);
    float solid = opSmoothUnion(base, neck, smoothJoin);       //smooth union
    if(bump != 0.0){
        float dimple = length(p + vec3(0.0, baseHeight, 0.0)) - 0.25;
        solid = opSmoothIntersect(solid, -dimple, 1.0);             //punt at the base
    }
    return solid;
}


// p is in the bottle's own coordinates (origin at the base centre). The glass
// SHELL: the solid hollowed to a wall of `thickness`, neck chopped open.
float bottleDistance(vec3 p, float baseRadius, float baseHeight, float neckRadius,
                     float neckHeight, float thickness, float rounded, float smoothJoin, float bump){
    float solid = bottle_solid(p, baseRadius, baseHeight, neckRadius, neckHeight, rounded, smoothJoin, bump);
    float shell = opOnion(solid, thickness);
    float top   = (p.y - (baseHeight + neckHeight)) - neckHeight/3.0;   //chop the neck open
    return opSmoothIntersect(shell, top, thickness);
}


// the interior cavity — the solid inset by the wall. For a liquid region in a
// group: `drink = max(bottleCavity(q, ...), q.y - level)`.
float bottleCavity(vec3 p, float baseRadius, float baseHeight, float neckRadius,
                   float neckHeight, float thickness, float rounded, float smoothJoin, float bump){
    return bottle_solid(p, baseRadius, baseHeight, neckRadius, neckHeight, rounded, smoothJoin, bump) + thickness;
}


// tight bounding cylinder, centred on the (asymmetric) shape, not the origin
float bottleBound(vec3 p, float baseRadius, float baseHeight, float neckHeight,
                  float thickness, float rounded, float smoothJoin){
    float yTop = baseHeight + (4.0/3.0)*neckHeight + thickness + 0.1;
    float yBot = -(baseHeight + rounded + thickness + 0.1);
    float R    = baseRadius + thickness + 0.25*smoothJoin + 0.1;
    return cylinderSlab(p - vec3(0.0, 0.5*(yTop + yBot), 0.0), R, 0.5*(yTop - yBot));
}


//--- library: glsl/shapes/environments/room.glsl ---
//----------------------------------------------------------------------------
// ROOM — a closed box, seen from the inside.
//
// The room is ONE region whose solid is everything OUTSIDE the box, so the
// interior is open air and regionAt() returns ID_NONE there. Its six walls are
// not six objects: they are a material FIELD over that one region, read off by
// asking which face a point is nearest. roomFace() answers that.
//
// glsl/shapes/ is the math-only library: plain functions of a point and some
// floats. No structs, no Frame, no Material.
//----------------------------------------------------------------------------


const int ROOM_FLOOR   = 0;
const int ROOM_CEILING = 1;
const int ROOM_LEFT    = 2;
const int ROOM_RIGHT   = 3;
const int ROOM_FRONT   = 4;
const int ROOM_BACK    = 5;


// p is in the room's own coordinates (origin at the box centre).
// Negative in the WALLS, positive in the open interior — the sign convention
// every other region uses, just turned inside out.
float roomDistance(vec3 p, vec3 halfSize){
    return -boxDistance(p, halfSize);
}


// Exact ray intersection, in world coordinates. The ray is inside the box, so
// this is simply the distance at which it leaves: the nearest of the three
// far slab crossings.
float roomTrace(Vector tv, vec3 centre, vec3 halfSize){
    vec3  o  = tv.pos - centre;
    vec3  tm = max((-halfSize - o)/tv.dir, (halfSize - o)/tv.dir);
    float t  = min(tm.x, min(tm.y, tm.z));
    if(t < 0.){ return maxDist; }
    return min(t, maxDist);
}


// Which wall p is on (or nearest to) — a shape DATA output (docs/shape-data.md):
// a material that reads `faceData` gets it injected. d is negative inside the
// room, so its LARGEST component names the axis the point is closest to leaving
// through, and the sign of p picks which of that axis's two faces.
int roomFaceData(vec3 p, vec3 halfSize){
    vec3 d = abs(p) - halfSize;

    if(d.y >= d.x && d.y >= d.z){
        return (p.y > 0.) ? ROOM_CEILING : ROOM_FLOOR;
    }
    if(d.x >= d.z){
        return (p.x > 0.) ? ROOM_RIGHT : ROOM_LEFT;
    }
    return (p.z > 0.) ? ROOM_BACK : ROOM_FRONT;
}


//--- the objects, in declaration order (= containment priority, inner to outer)
const int ID_CUP   = 0;
const int ID_DRINK = 1;
const int ID_LIGHT = 2;
const int ID_ROOM  = 3;

const int N_OBJ = 4;
float gSDF[N_OBJ];


//--- placement and shape parameters ----------------------------------
const vec3 BOTTLELIQUID_P = vec3(1.0, 0.48, 2.0);
const float B_BASE_R = 1.25;
const float B_BASE_H = 1.5;
const float B_NECK_R = 0.3;
const float B_NECK_H = 1.0;
const float B_THICK  = 0.1;
const float B_ROUND  = 0.1;
const float B_JOIN   = 0.3;
const float B_BUMP   = 1.0;
const float FILL     = 0.6;     //drink level, as a fraction of the base height

const vec3  LIGHT_P      = vec3(-6.0, 3.0, 0.0);
const float LIGHT_RADIUS = 1.0;

const vec3 ROOM_P        = vec3(-5.75, 6.5, -5.0);
const vec3 ROOM_HALFSIZE = vec3(14.25, 7.5, 15.0);


//---------------------------------------------------------------------
// the region sdfs
//---------------------------------------------------------------------

void sdf_bottleLiquid(vec3 p, out float cup, out float drink){
    vec3  q = p - BOTTLELIQUID_P;
    cup   = bottleDistance(q, B_BASE_R, B_BASE_H, B_NECK_R, B_NECK_H, B_THICK, B_ROUND, B_JOIN, B_BUMP);
    drink = max(bottleCavity(q, B_BASE_R, B_BASE_H, B_NECK_R, B_NECK_H, B_THICK, B_ROUND, B_JOIN, B_BUMP),
                q.y - B_BASE_H*FILL);
}

//single-region entry points, for the 4-tap normals
float sdf_cup(vec3 p){ float cup, drink; sdf_bottleLiquid(p, cup, drink); return cup; }
float sdf_drink(vec3 p){ float cup, drink; sdf_bottleLiquid(p, cup, drink); return drink; }

float sdf_light(vec3 p){
    return sphereDistance(p - LIGHT_P, LIGHT_RADIUS);
}

//the room SOLID is everything outside the box, so its interior is open air and
//regionAt() returns ID_NONE there
float sdf_room(vec3 p){
    return roomDistance(p - ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the bounds — the acceleration structure (sdf_Scene only; sdfAll stays exact)
//---------------------------------------------------------------------

float bound_bottleLiquid(vec3 p){
    vec3 q = p - BOTTLELIQUID_P;
    return bottleBound(q, B_BASE_R, B_BASE_H, B_NECK_H, B_THICK, B_ROUND, B_JOIN);
}


//---------------------------------------------------------------------
// the normals — the 4-tap of each region's own sdf, in world coordinates
//---------------------------------------------------------------------
const float NRM_E = 0.0002;

Vector normal_cup(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_cup(p + k.xyy*NRM_E) + k.yyx*sdf_cup(p + k.yyx*NRM_E)
                              + k.yxy*sdf_cup(p + k.yxy*NRM_E) + k.xxx*sdf_cup(p + k.xxx*NRM_E) ));
}

Vector normal_drink(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_drink(p + k.xyy*NRM_E) + k.yyx*sdf_drink(p + k.yyx*NRM_E)
                              + k.yxy*sdf_drink(p + k.yxy*NRM_E) + k.xxx*sdf_drink(p + k.xxx*NRM_E) ));
}

Vector normal_light(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_light(p + k.xyy*NRM_E) + k.yyx*sdf_light(p + k.yyx*NRM_E)
                              + k.yxy*sdf_light(p + k.yxy*NRM_E) + k.xxx*sdf_light(p + k.xxx*NRM_E) ));
}

Vector normal_room(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_room(p + k.xyy*NRM_E) + k.yyx*sdf_room(p + k.yyx*NRM_E)
                              + k.yxy*sdf_room(p + k.yxy*NRM_E) + k.xxx*sdf_room(p + k.xxx*NRM_E) ));
}


//---------------------------------------------------------------------
// the materials
//  material_ gives the Surface plus this object's own Medium; medium_ gives
//  only the Medium, for when the object is merely the far side
//---------------------------------------------------------------------

Medium medium_cup(vec3 p){
    Medium m = defaultMedium();
    m.ior    = 1.5;
    m.absorb = 0.5*vec3(0.3, 0.05, 0.08);
    return m;
}
Material material_cup(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //glass
    m.interior = medium_cup(p);
    m.surf.transmit = 1.0;
    return m;
}

Medium medium_drink(vec3 p){
    Medium m = defaultMedium();
    m.ior    = 1.3;
    m.absorb = vec3(0.1, 0.05, 0.0);
    return m;
}
Material material_drink(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //glass
    m.interior = medium_drink(p);
    m.surf.transmit = 1.0;
    return m;
}

Material material_light(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //light
    m.surf.emit = 150.0*vec3(0.9);
    return m;
}
Medium   medium_light  (vec3 p){ return defaultMedium(); }

Material material_room(vec3 p, inout Vector n){
    vec3 q = p - ROOM_P;
    int faceData = roomFaceData(q, ROOM_HALFSIZE);
    if(faceData == ROOM_CEILING){ return makeLight(vec3(1.0), roomLight); }
    if(faceData == ROOM_FLOOR)  { return makeGloss(floorColor, 0.0, wallRough); }
    if(faceData == ROOM_LEFT)   { return makeGloss(warmColor,  0.0, wallRough); }
    if(faceData == ROOM_RIGHT)  { return makeGloss(coolColor,  0.0, wallRough); }
    return makeGloss(wallColor, 0.0, wallRough);
}
Medium medium_room(vec3 p){ return defaultMedium(); }


//---------------------------------------------------------------------
// the analytic intersections
//---------------------------------------------------------------------

float trace_light(Vector tv){
    return sphereTrace(tv, LIGHT_P, LIGHT_RADIUS);
}

float trace_room(Vector tv){
    return roomTrace(tv, ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the dispatchers
//---------------------------------------------------------------------

void sdfAll(vec3 p){
    sdf_bottleLiquid(p, gSDF[ID_CUP], gSDF[ID_DRINK]);
    gSDF[ID_LIGHT] = sdf_light(p);
    gSDF[ID_ROOM ] = sdf_room(p);
}

Vector normalOf(int id, vec3 p){
    if(id == ID_CUP  ){ return normal_cup(p); }
    if(id == ID_DRINK){ return normal_drink(p); }
    if(id == ID_LIGHT){ return normal_light(p); }
    return normal_room(p);
}

//no sheets in this scene: every object is a region with an interior
bool isSheet(int id){ return false; }

Material materialOf(int id, vec3 p, inout Vector n, bool front){
    if(id == ID_CUP  ){ return material_cup(p, n); }
    if(id == ID_DRINK){ return material_drink(p, n); }
    if(id == ID_LIGHT){ return material_light(p, n); }
    return material_room(p, n);
}

Medium mediumOf(int id, vec3 p){
    if(id == ID_CUP  ){ return medium_cup(p); }
    if(id == ID_DRINK){ return medium_drink(p); }
    if(id == ID_LIGHT){ return medium_light(p); }
    if(id == ID_ROOM ){ return medium_room(p); }
    return defaultMedium();      //ID_NONE: open air
}


//---------------------------------------------------------------------
// the entry points
//---------------------------------------------------------------------

void buildScene(){}

float sdf_Scene(Vector tv){
    vec3 p = tv.pos;
    float d = maxDist;

    float b_bottleLiquid = bound_bottleLiquid(p);
    if(b_bottleLiquid > BOUND_MARGIN){ d = min(d, b_bottleLiquid); }
    else{
        float cup, drink;
        sdf_bottleLiquid(p, cup, drink);
        d = min(d, min(cup, drink));
    }

    return d;
}

float trace_Scene(Vector tv){
    float d = maxDist;
    d = min(d, trace_light(tv));
    d = min(d, trace_room(tv));
    return d;
}
