//=====================================================================
// generated by scenegen from src/scene.js — do not edit by hand
//=====================================================================


//--- library: glsl/shapes/models/bottle.glsl ---
//----------------------------------------------------------------------------
// BOTTLE — a rounded-cylinder base and neck, smooth-unioned, hollowed to a glass
// shell with the neck chopped open (and a punt dimple in the base).
//
// glsl/shapes/ is the math-only library: plain functions of a point and floats.
// Built from cylinderDistance + opSmoothUnion/Intersect/Onion (glsl/shapes/ops/,
// always compiled). `bottleCavity` is the interior surface, for a liquid region
// in a group (bottleLiquid); `bottleDistance` is the glass shell for a plain object.
//----------------------------------------------------------------------------


//the solid profile BEFORE hollowing — the shared source for the shell and the
//cavity, so the two can never drift (file-private)
float bottle_solid(vec3 p, float baseRadius, float baseHeight, float neckRadius,
                   float neckHeight, float rounded, float smoothJoin, float bump){
    float base = cylinderDistance(p, baseRadius, baseHeight, rounded);
    vec3  q    = p - vec3(0.0, baseHeight + neckHeight, 0.0);
    float neck = cylinderDistance(q, neckRadius, neckHeight, rounded);
    float solid = opSmoothUnion(base, neck, smoothJoin);       //smooth union
    if(bump != 0.0){
        float dimple = length(p + vec3(0.0, baseHeight, 0.0)) - 0.25;
        solid = opSmoothIntersect(solid, -dimple, 1.0);             //punt at the base
    }
    return solid;
}


// p is in the bottle's own coordinates (origin at the base centre). The glass
// SHELL: the solid hollowed to a wall of `thickness`, neck chopped open.
float bottleDistance(vec3 p, float baseRadius, float baseHeight, float neckRadius,
                     float neckHeight, float thickness, float rounded, float smoothJoin, float bump){
    float solid = bottle_solid(p, baseRadius, baseHeight, neckRadius, neckHeight, rounded, smoothJoin, bump);
    float shell = opOnion(solid, thickness);
    float top   = (p.y - (baseHeight + neckHeight)) - neckHeight/3.0;   //chop the neck open
    return opSmoothIntersect(shell, top, thickness);
}


// the interior cavity — the solid inset by the wall. For a liquid region in a
// group: `drink = max(bottleCavity(q, ...), q.y - level)`.
float bottleCavity(vec3 p, float baseRadius, float baseHeight, float neckRadius,
                   float neckHeight, float thickness, float rounded, float smoothJoin, float bump){
    return bottle_solid(p, baseRadius, baseHeight, neckRadius, neckHeight, rounded, smoothJoin, bump) + thickness;
}


// tight bounding cylinder, centred on the (asymmetric) shape, not the origin
float bottleBound(vec3 p, float baseRadius, float baseHeight, float neckHeight,
                  float thickness, float rounded, float smoothJoin){
    float yTop = baseHeight + (4.0/3.0)*neckHeight + thickness + 0.1;
    float yBot = -(baseHeight + rounded + thickness + 0.1);
    float R    = baseRadius + thickness + 0.25*smoothJoin + 0.1;
    return cylinderSlab(p - vec3(0.0, 0.5*(yTop + yBot), 0.0), R, 0.5*(yTop - yBot));
}


//--- library: glsl/shapes/environments/room.glsl ---
//----------------------------------------------------------------------------
// ROOM — a closed box, seen from the inside.
//
// The room is ONE region whose solid is everything OUTSIDE the box, so the
// interior is open air and regionAt() returns ID_NONE there. Its six walls are
// not six objects: they are a material FIELD over that one region, read off by
// asking which face a point is nearest. roomFace() answers that.
//
// glsl/shapes/ is the math-only library: plain functions of a point and some
// floats. No structs, no Frame, no Material.
//----------------------------------------------------------------------------


const int ROOM_FLOOR   = 0;
const int ROOM_CEILING = 1;
const int ROOM_LEFT    = 2;
const int ROOM_RIGHT   = 3;
const int ROOM_FRONT   = 4;
const int ROOM_BACK    = 5;


// p is in the room's own coordinates (origin at the box centre).
// Negative in the WALLS, positive in the open interior — the sign convention
// every other region uses, just turned inside out.
float roomDistance(vec3 p, vec3 halfSize){
    return -boxDistance(p, halfSize);
}


// Exact ray intersection, in world coordinates. The ray is inside the box, so
// this is simply the distance at which it leaves: the nearest of the three
// far slab crossings.
float roomTrace(Vector tv, vec3 centre, vec3 halfSize){
    vec3  o  = tv.pos - centre;
    vec3  tm = max((-halfSize - o)/tv.dir, (halfSize - o)/tv.dir);
    float t  = min(tm.x, min(tm.y, tm.z));
    if(t < 0.){ return maxDist; }
    return min(t, maxDist);
}


// Which wall p is on (or nearest to) — a shape DATA output (docs/shape-data.md):
// a material that reads `faceData` gets it injected. d is negative inside the
// room, so its LARGEST component names the axis the point is closest to leaving
// through, and the sign of p picks which of that axis's two faces.
int roomFaceData(vec3 p, vec3 halfSize){
    vec3 d = abs(p) - halfSize;

    if(d.y >= d.x && d.y >= d.z){
        return (p.y > 0.) ? ROOM_CEILING : ROOM_FLOOR;
    }
    if(d.x >= d.z){
        return (p.x > 0.) ? ROOM_RIGHT : ROOM_LEFT;
    }
    return (p.z > 0.) ? ROOM_BACK : ROOM_FRONT;
}


//--- the objects, in declaration order (= containment priority, inner to outer)
const int ID_ROCK   = 0;
const int ID_BLOCK  = 1;
const int ID_NUGGET = 2;
const int ID_LAMP   = 3;
const int ID_ROOM   = 4;

const int N_OBJ = 5;
float gSDF[N_OBJ];


//--- placement and shape parameters ----------------------------------
const vec3  ROCK_P      = vec3(-2.9, 2.0, 0.4);
const float ROCK_SEED   = 0.0;
const float ROCK_RADIUS = 1.9;

const vec3  BLOCK_P        = vec3(1.4, 1.7, -0.6);
const float BLOCK_SEED     = 17.0;
const vec3  BLOCK_HALFSIZE = vec3(1.6);

const vec3  NUGGET_P          = vec3(4.0, 0.0, 2.4);
const float NUGGET_SEED       = 93.0;
const float NUGGET_BASERADIUS = 1.25;
const float NUGGET_BASEHEIGHT = 1.5;
const float NUGGET_NECKRADIUS = 0.3;
const float NUGGET_NECKHEIGHT = 1.0;
const float NUGGET_THICKNESS  = 0.1;
const float NUGGET_ROUNDED    = 0.1;
const float NUGGET_SMOOTHJOIN = 0.3;
const float NUGGET_BUMP       = 1.0;

const vec3  LAMP_P      = vec3(-4.0, 8.5, 5.0);
const float LAMP_RADIUS = 1.4;

const vec3 ROOM_P        = vec3(0.0, 6.0, 0.0);
const vec3 ROOM_HALFSIZE = vec3(10.0, 6.0, 10.0);


//---------------------------------------------------------------------
// the region sdfs
//---------------------------------------------------------------------

float sdf_rock(vec3 p){
    vec3  q = p - ROCK_P;
    float d = sphereDistance(q, ROCK_RADIUS);
    return opCarveFbm(q, d, detail, erosion, gain, blend, ROCK_SEED);
}

float sdf_block(vec3 p){
    vec3  q = p - BLOCK_P;
    float d = boxDistance(q, BLOCK_HALFSIZE);
    return opCarveFbm(q, d, detail, erosion, gain, blend, BLOCK_SEED);
}

float sdf_nugget(vec3 p){
    vec3  q = p - NUGGET_P;
    float d = bottleDistance(q, NUGGET_BASERADIUS, NUGGET_BASEHEIGHT, NUGGET_NECKRADIUS, NUGGET_NECKHEIGHT, NUGGET_THICKNESS, NUGGET_ROUNDED, NUGGET_SMOOTHJOIN, NUGGET_BUMP);
    return opCarveFbm(q, d, detail, erosion, gain, blend, NUGGET_SEED);
}

float sdf_lamp(vec3 p){
    return sphereDistance(p - LAMP_P, LAMP_RADIUS);
}

//the room SOLID is everything outside the box, so its interior is open air and
//regionAt() returns ID_NONE there
float sdf_room(vec3 p){
    return roomDistance(p - ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the bounds — the acceleration structure (sdf_Scene only; sdfAll stays exact)
//---------------------------------------------------------------------

float bound_rock(vec3 p){
    return sphereDistance(p - ROCK_P, ROCK_RADIUS);
}

float bound_block(vec3 p){
    return boxDistance(p - BLOCK_P, BLOCK_HALFSIZE);
}

float bound_nugget(vec3 p){
    return bottleBound(p - NUGGET_P, NUGGET_BASERADIUS, NUGGET_BASEHEIGHT, NUGGET_NECKHEIGHT, NUGGET_THICKNESS, NUGGET_ROUNDED, NUGGET_SMOOTHJOIN);
}


//---------------------------------------------------------------------
// the normals — the 4-tap of each region's own sdf, in world coordinates
//---------------------------------------------------------------------
const float NRM_E = 0.0002;

Vector normal_rock(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_rock(p + k.xyy*NRM_E) + k.yyx*sdf_rock(p + k.yyx*NRM_E)
                              + k.yxy*sdf_rock(p + k.yxy*NRM_E) + k.xxx*sdf_rock(p + k.xxx*NRM_E) ));
}

Vector normal_block(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_block(p + k.xyy*NRM_E) + k.yyx*sdf_block(p + k.yyx*NRM_E)
                              + k.yxy*sdf_block(p + k.yxy*NRM_E) + k.xxx*sdf_block(p + k.xxx*NRM_E) ));
}

Vector normal_nugget(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_nugget(p + k.xyy*NRM_E) + k.yyx*sdf_nugget(p + k.yyx*NRM_E)
                              + k.yxy*sdf_nugget(p + k.yxy*NRM_E) + k.xxx*sdf_nugget(p + k.xxx*NRM_E) ));
}

Vector normal_lamp(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_lamp(p + k.xyy*NRM_E) + k.yyx*sdf_lamp(p + k.yyx*NRM_E)
                              + k.yxy*sdf_lamp(p + k.yxy*NRM_E) + k.xxx*sdf_lamp(p + k.xxx*NRM_E) ));
}

Vector normal_room(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_room(p + k.xyy*NRM_E) + k.yyx*sdf_room(p + k.yyx*NRM_E)
                              + k.yxy*sdf_room(p + k.yxy*NRM_E) + k.xxx*sdf_room(p + k.xxx*NRM_E) ));
}


//---------------------------------------------------------------------
// the materials
//  material_ gives the Surface plus this object's own Medium; medium_ gives
//  only the Medium, for when the object is merely the far side
//---------------------------------------------------------------------

Material material_rock(vec3 p, inout Vector n){
    vec3 q = p - ROCK_P;
    float grain = fbm(6.0*q);
    vec3  col   = mix(/*ironCol*/vec3(0.31, 0.16, 0.1), /*stoneCol*/vec3(0.52, 0.47, 0.4), smoothstep(0.35, 0.7, grain));
    return makeGloss(col, 0.02, mix(0.75, 0.45, grain));
}
Medium medium_rock(vec3 p){ return defaultMedium(); }

Material material_block(vec3 p, inout Vector n){
    vec3 q = p - BLOCK_P;
    float grain = fbm(5.0*q);
    return makeGloss(mix(/*stoneCol*/vec3(0.52, 0.47, 0.4), vec3(0.72, 0.70, 0.66), grain), 0.03, 0.5);
}
Medium medium_block(vec3 p){ return defaultMedium(); }

Material material_nugget(vec3 p, inout Vector n){
    vec3 q = p - NUGGET_P;
    float grain = fbm(8.0*q);
    return makeMetal(mix(/*copperCol*/vec3(0.62, 0.35, 0.18), vec3(0.75, 0.55, 0.35), grain), 1.0, mix(0.45, 0.2, grain));
}
Medium medium_nugget(vec3 p){ return defaultMedium(); }

Material material_lamp(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //light
    m.surf.emit = lampPower*vec3(1.0, 0.95, 0.88);
    return m;
}
Medium   medium_lamp  (vec3 p){ return defaultMedium(); }

Material material_room(vec3 p, inout Vector n){
    vec3 q = p - ROOM_P;
    int faceData = roomFaceData(q, ROOM_HALFSIZE);
    if(faceData == ROOM_CEILING){ return makeLight(vec3(1.0), roomLight); }
    if(faceData == ROOM_FLOOR)  { return makeGloss(floorColor, 0.0, wallRough); }
    if(faceData == ROOM_LEFT)   { return makeGloss(warmColor,  0.0, wallRough); }
    if(faceData == ROOM_RIGHT)  { return makeGloss(coolColor,  0.0, wallRough); }
    return makeGloss(wallColor, 0.0, wallRough);
}
Medium medium_room(vec3 p){ return defaultMedium(); }


//---------------------------------------------------------------------
// the analytic intersections
//---------------------------------------------------------------------

float trace_lamp(Vector tv){
    return sphereTrace(tv, LAMP_P, LAMP_RADIUS);
}

float trace_room(Vector tv){
    return roomTrace(tv, ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the dispatchers
//---------------------------------------------------------------------

void sdfAll(vec3 p){
    gSDF[ID_ROCK  ] = sdf_rock(p);
    gSDF[ID_BLOCK ] = sdf_block(p);
    gSDF[ID_NUGGET] = sdf_nugget(p);
    gSDF[ID_LAMP  ] = sdf_lamp(p);
    gSDF[ID_ROOM  ] = sdf_room(p);
}

Vector normalOf(int id, vec3 p){
    if(id == ID_ROCK  ){ return normal_rock(p); }
    if(id == ID_BLOCK ){ return normal_block(p); }
    if(id == ID_NUGGET){ return normal_nugget(p); }
    if(id == ID_LAMP  ){ return normal_lamp(p); }
    return normal_room(p);
}

//no sheets in this scene: every object is a region with an interior
bool isSheet(int id){ return false; }

Material materialOf(int id, vec3 p, inout Vector n, bool front){
    if(id == ID_ROCK  ){ return material_rock(p, n); }
    if(id == ID_BLOCK ){ return material_block(p, n); }
    if(id == ID_NUGGET){ return material_nugget(p, n); }
    if(id == ID_LAMP  ){ return material_lamp(p, n); }
    return material_room(p, n);
}

Medium mediumOf(int id, vec3 p){
    if(id == ID_ROCK  ){ return medium_rock(p); }
    if(id == ID_BLOCK ){ return medium_block(p); }
    if(id == ID_NUGGET){ return medium_nugget(p); }
    if(id == ID_LAMP  ){ return medium_lamp(p); }
    if(id == ID_ROOM  ){ return medium_room(p); }
    return defaultMedium();      //ID_NONE: open air
}


//---------------------------------------------------------------------
// the entry points
//---------------------------------------------------------------------

void buildScene(){}

float sdf_Scene(Vector tv){
    vec3 p = tv.pos;
    float d = maxDist;

    float b_rock = bound_rock(p);
    d = min(d, (b_rock > BOUND_MARGIN) ? b_rock : sdf_rock(p));

    float b_block = bound_block(p);
    d = min(d, (b_block > BOUND_MARGIN) ? b_block : sdf_block(p));

    float b_nugget = bound_nugget(p);
    d = min(d, (b_nugget > BOUND_MARGIN) ? b_nugget : sdf_nugget(p));

    return d;
}

float trace_Scene(Vector tv){
    float d = maxDist;
    d = min(d, trace_lamp(tv));
    d = min(d, trace_room(tv));
    return d;
}
