//=====================================================================
// generated by scenegen from src/scene.js — do not edit by hand
//=====================================================================


//--- library: glsl/shapes/models/gem.glsl ---
//----------------------------------------------------------------------------
// GEM — a brilliant-ish cut stone, girdle radius `size`.
//
// 8 crown facets rising to an octagonal table, 8 pavilion facets falling to the
// culet point, offset half a sector so the rings alternate (the classic
// brilliant look), plus an octagonal girdle band. Built as an exact convex
// intersection of planes: folding the angle into one wedge makes r*cos(folded)
// the support function of every rotated facet copy, so max() over the plane set
// is a true convex sdf that sphere-traces cleanly. Unit proportions: girdle
// radius 1, table at y=0.38, culet at (0,-0.85).
//
// glsl/shapes/ is the math-only library: plain functions of a point and floats.
//----------------------------------------------------------------------------


//fold the angle into the +/- sector/2 wedge about phase, and return the folded
//radial support r*cos(a) (file-private helper)
float gem_support(float r, float ang, float sector, float phase){
    float a = mod(ang + phase + 0.5*sector, sector) - 0.5*sector;
    return r*cos(a);
}


// p is in the gem's own coordinates (origin at the girdle centre)
float gemDistance(vec3 p, float size){
    p /= size;
    float r   = length(p.xz);
    float ang = atan(p.z, p.x);
    const float sector = 2.*PI/8.;

    float rc = gem_support(r, ang, sector, 0.);            //crown + girdle wedge
    float rp = gem_support(r, ang, sector, 0.5*sector);    //pavilion wedge (alternates)

    float table    = p.y - 0.38;
    float girdle   = rc - 1.;
    float crown    = dot(vec2(rc, p.y), vec2(0.5547, 0.8321)) - 0.6213;
    float pavilion = dot(vec2(rp, p.y), vec2(0.6247, -0.7809)) - 0.6637;

    return size * max( max(table, girdle), max(crown, pavilion) );
}


// bounding sphere: girdle polygon corners reach r = 1.082, all else is inside
float gemBound(vec3 p, float size){
    return length(p) - 1.15*size;
}


//--- library: glsl/shapes/environments/room.glsl ---
//----------------------------------------------------------------------------
// ROOM — a closed box, seen from the inside.
//
// The room is ONE region whose solid is everything OUTSIDE the box, so the
// interior is open air and regionAt() returns ID_NONE there. Its six walls are
// not six objects: they are a material FIELD over that one region, read off by
// asking which face a point is nearest. roomFace() answers that.
//
// glsl/shapes/ is the math-only library: plain functions of a point and some
// floats. No structs, no Frame, no Material.
//----------------------------------------------------------------------------


const int ROOM_FLOOR   = 0;
const int ROOM_CEILING = 1;
const int ROOM_LEFT    = 2;
const int ROOM_RIGHT   = 3;
const int ROOM_FRONT   = 4;
const int ROOM_BACK    = 5;


// p is in the room's own coordinates (origin at the box centre).
// Negative in the WALLS, positive in the open interior — the sign convention
// every other region uses, just turned inside out.
float roomDistance(vec3 p, vec3 halfSize){
    return -boxDistance(p, halfSize);
}


// Exact ray intersection, in world coordinates. The ray is inside the box, so
// this is simply the distance at which it leaves: the nearest of the three
// far slab crossings.
float roomTrace(Vector tv, vec3 centre, vec3 halfSize){
    vec3  o  = tv.pos - centre;
    vec3  tm = max((-halfSize - o)/tv.dir, (halfSize - o)/tv.dir);
    float t  = min(tm.x, min(tm.y, tm.z));
    if(t < 0.){ return maxDist; }
    return min(t, maxDist);
}


// Which wall p is on (or nearest to) — a shape DATA output (docs/shape-data.md):
// a material that reads `faceData` gets it injected. d is negative inside the
// room, so its LARGEST component names the axis the point is closest to leaving
// through, and the sign of p picks which of that axis's two faces.
int roomFaceData(vec3 p, vec3 halfSize){
    vec3 d = abs(p) - halfSize;

    if(d.y >= d.x && d.y >= d.z){
        return (p.y > 0.) ? ROOM_CEILING : ROOM_FLOOR;
    }
    if(d.x >= d.z){
        return (p.x > 0.) ? ROOM_RIGHT : ROOM_LEFT;
    }
    return (p.z > 0.) ? ROOM_BACK : ROOM_FRONT;
}


//--- the objects, in declaration order (= containment priority, inner to outer)
const int ID_MESA   = 0;
const int ID_BEADS  = 1;
const int ID_PILLAR = 2;
const int ID_HUSK   = 3;
const int ID_DICE   = 4;
const int ID_REEF   = 5;
const int ID_LAMP   = 6;
const int ID_ROOM   = 7;

const int N_OBJ = 8;
float gSDF[N_OBJ];


//--- placement and shape parameters ----------------------------------
const vec3  MESA_P           = vec3(-4.0, 1.9, -1.5);
const int   MESA_OCTAVES     = 6;
const float MESA_GAIN        = 0.5;
const float MESA_SEED        = 0.0;
const vec3  MESA_CLIP_P      = vec3(0.0, 0.9, 0.0);
const vec3  MESA_CLIP_NORMAL = vec3(0.0, 1.0, 0.0);
const float MESA_CLIP_BLEND  = 0.05;
const float MESA_RADIUS      = 1.9;

const vec3  BEADS_P           = vec3(3.6, 0.32, -2.6);
const float BEADS_SPACING     = 1.0;
const vec3  BEADS_LIMIT       = vec3(3.0, 0.0, 3.0);
const float BEADS_CLIP_RADIUS = 2.4;
const float BEADS_RADIUS      = 0.32;

const vec3  PILLAR_P        = vec3(-0.6, 1.2, 0.6);
const int   PILLAR_OCTAVES  = 6;
const float PILLAR_GAIN     = 0.5;
const float PILLAR_SEED     = 17.0;
const vec3  PILLAR_HALFSIZE = vec3(0.35, 1.2, 0.35);

const vec3  HUSK_P             = vec3(3.2, 1.5, 1.8);
const vec3  HUSK_CLIP_P        = vec3(0.0, 0.0, 1.2);
const vec3  HUSK_CLIP_HALFSIZE = vec3(2.0, 2.0, 1.0);
const float HUSK_SIZE          = 1.4;

const vec3  DICE_P          = vec3(-2.2, 1.0, 3.2);
const vec3  DICE_CUT_P      = vec3(0.7);
const float DICE_CUT_RADIUS = 1.25;
const float DICE_CUT_BLEND  = 0.08;
const vec3  DICE_HALFSIZE   = vec3(1.0);

const vec3  REEF_P        = vec3(0.9, 0.85, 3.6);
const int   REEF_OCTAVES  = 6;
const float REEF_GAIN     = 0.5;
const float REEF_SEED     = 41.0;
const vec3  REEF_HALFSIZE = vec3(0.85);

const vec3  LAMP_P      = vec3(-4.0, 8.5, 5.0);
const float LAMP_RADIUS = 1.4;

const vec3 ROOM_P        = vec3(0.0, 6.0, 0.0);
const vec3 ROOM_HALFSIZE = vec3(10.0, 6.0, 10.0);


//---------------------------------------------------------------------
// the region sdfs
//---------------------------------------------------------------------

float sdf_mesa(vec3 p){
    vec3  q = p - MESA_P;
    float d = sphereDistance(q, MESA_RADIUS);
    d = opCarveFbm(q, d, MESA_OCTAVES, erosion, MESA_GAIN, bite, MESA_SEED);
    return smax(d, planeDistance(p - MESA_P - MESA_CLIP_P, MESA_CLIP_NORMAL), MESA_CLIP_BLEND);
}

float sdf_beads(vec3 p){
    vec3  q = opRepLim(p - BEADS_P, BEADS_SPACING, BEADS_LIMIT);
    float d = sphereDistance(q, BEADS_RADIUS);
    return max(d, sphereDistance(p - BEADS_P, BEADS_CLIP_RADIUS));
}

float sdf_pillar(vec3 p){
    vec3  q = opRadialY(p - PILLAR_P, float(segments));
    float d = boxDistance(q, PILLAR_HALFSIZE);
    return opCarveFbm(q, d, PILLAR_OCTAVES, erosion, PILLAR_GAIN, bite, PILLAR_SEED);
}

float sdf_husk(vec3 p){
    float d = gemDistance(p - HUSK_P, HUSK_SIZE);
    d = max(d, boxDistance(p - HUSK_P - HUSK_CLIP_P, HUSK_CLIP_HALFSIZE));
    return abs(d) - thickness;
}

float sdf_dice(vec3 p){
    float d = boxDistance(p - DICE_P, DICE_HALFSIZE);
    return opSmoothSubtract(d, sphereDistance(p - DICE_P - DICE_CUT_P, DICE_CUT_RADIUS), DICE_CUT_BLEND);
}

float sdf_reef(vec3 p){
    vec3  q = p - REEF_P;
    float d = boxDistance(q, REEF_HALFSIZE);
    return opAccreteFbm(q, d, REEF_OCTAVES, erosion, REEF_GAIN, bite, REEF_SEED);
}

float sdf_lamp(vec3 p){
    return sphereDistance(p - LAMP_P, LAMP_RADIUS);
}

//the room SOLID is everything outside the box, so its interior is open air and
//regionAt() returns ID_NONE there
float sdf_room(vec3 p){
    return roomDistance(p - ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the bounds — the acceleration structure (sdf_Scene only; sdfAll stays exact)
//---------------------------------------------------------------------

float bound_mesa(vec3 p){
    return planeDistance(p - MESA_P - MESA_CLIP_P, MESA_CLIP_NORMAL) - MESA_CLIP_BLEND;
}

float bound_beads(vec3 p){
    return sphereDistance(p - BEADS_P, BEADS_CLIP_RADIUS);
}

float bound_pillar(vec3 p){
    return boxDistance(opRadialY(p - PILLAR_P, float(segments)), PILLAR_HALFSIZE);
}

float bound_husk(vec3 p){
    return boxDistance(p - HUSK_P - HUSK_CLIP_P, HUSK_CLIP_HALFSIZE) - thickness;
}

float bound_dice(vec3 p){
    return boxDistance(p - DICE_P, DICE_HALFSIZE);
}

float bound_reef(vec3 p){
    return boxDistance(p - REEF_P, REEF_HALFSIZE) - (ACCRETE_REACH + 0.25*bite)/(1.0 - REEF_GAIN);
}


//---------------------------------------------------------------------
// the normals — the 4-tap of each region's own sdf, in world coordinates
//---------------------------------------------------------------------
const float NRM_E = 0.0002;

Vector normal_mesa(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_mesa(p + k.xyy*NRM_E) + k.yyx*sdf_mesa(p + k.yyx*NRM_E)
                              + k.yxy*sdf_mesa(p + k.yxy*NRM_E) + k.xxx*sdf_mesa(p + k.xxx*NRM_E) ));
}

Vector normal_beads(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_beads(p + k.xyy*NRM_E) + k.yyx*sdf_beads(p + k.yyx*NRM_E)
                              + k.yxy*sdf_beads(p + k.yxy*NRM_E) + k.xxx*sdf_beads(p + k.xxx*NRM_E) ));
}

Vector normal_pillar(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_pillar(p + k.xyy*NRM_E) + k.yyx*sdf_pillar(p + k.yyx*NRM_E)
                              + k.yxy*sdf_pillar(p + k.yxy*NRM_E) + k.xxx*sdf_pillar(p + k.xxx*NRM_E) ));
}

Vector normal_husk(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_husk(p + k.xyy*NRM_E) + k.yyx*sdf_husk(p + k.yyx*NRM_E)
                              + k.yxy*sdf_husk(p + k.yxy*NRM_E) + k.xxx*sdf_husk(p + k.xxx*NRM_E) ));
}

Vector normal_dice(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_dice(p + k.xyy*NRM_E) + k.yyx*sdf_dice(p + k.yyx*NRM_E)
                              + k.yxy*sdf_dice(p + k.yxy*NRM_E) + k.xxx*sdf_dice(p + k.xxx*NRM_E) ));
}

Vector normal_reef(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_reef(p + k.xyy*NRM_E) + k.yyx*sdf_reef(p + k.yyx*NRM_E)
                              + k.yxy*sdf_reef(p + k.yxy*NRM_E) + k.xxx*sdf_reef(p + k.xxx*NRM_E) ));
}

Vector normal_lamp(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_lamp(p + k.xyy*NRM_E) + k.yyx*sdf_lamp(p + k.yyx*NRM_E)
                              + k.yxy*sdf_lamp(p + k.yxy*NRM_E) + k.xxx*sdf_lamp(p + k.xxx*NRM_E) ));
}

Vector normal_room(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_room(p + k.xyy*NRM_E) + k.yyx*sdf_room(p + k.yyx*NRM_E)
                              + k.yxy*sdf_room(p + k.yxy*NRM_E) + k.xxx*sdf_room(p + k.xxx*NRM_E) ));
}


//---------------------------------------------------------------------
// the materials
//  material_ gives the Surface plus this object's own Medium; medium_ gives
//  only the Medium, for when the object is merely the far side
//---------------------------------------------------------------------

Material material_mesa(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //gloss
    m.surf.diffuse   = vec3(0.52, 0.47, 0.4);
    m.surf.roughness = 0.55;
    m.surf.gloss     = 0.02;
    return m;
}
Medium   medium_mesa  (vec3 p){ return defaultMedium(); }

Material material_beads(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //gloss
    m.surf.diffuse   = vec3(0.78, 0.26, 0.22);
    m.surf.roughness = 0.2;
    m.surf.gloss     = 0.1;
    return m;
}
Medium   medium_beads  (vec3 p){ return defaultMedium(); }

Material material_pillar(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //matte
    m.surf.diffuse = vec3(0.72, 0.68, 0.6);
    return m;
}
Medium   medium_pillar  (vec3 p){ return defaultMedium(); }

Material material_husk(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //metal
    m.surf.diffuse   = vec3(0.92, 0.8, 0.52);
    m.surf.specular  = vec3(0.92, 0.8, 0.52);
    m.surf.roughness = 0.25;
    m.surf.gloss     = 1.0;
    return m;
}
Medium   medium_husk  (vec3 p){ return defaultMedium(); }

Medium medium_dice(vec3 p){
    Medium m = defaultMedium();
    m.ior    = 1.5;
    m.absorb = vec3(0.03, 0.005, 0.02);
    return m;
}
Material material_dice(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //glass
    m.interior = medium_dice(p);
    m.surf.transmit = 1.0;
    return m;
}

Material material_reef(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //gloss
    m.surf.diffuse   = vec3(0.3, 0.5, 0.46);
    m.surf.roughness = 0.4;
    m.surf.gloss     = 0.04;
    return m;
}
Medium   medium_reef  (vec3 p){ return defaultMedium(); }

Material material_lamp(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //light
    m.surf.emit = lampPower*vec3(1.0, 0.95, 0.88);
    return m;
}
Medium   medium_lamp  (vec3 p){ return defaultMedium(); }

Material material_room(vec3 p, inout Vector n){
    vec3 q = p - ROOM_P;
    int faceData = roomFaceData(q, ROOM_HALFSIZE);
    if(faceData == ROOM_CEILING){ return makeLight(vec3(1.0), roomLight); }
    if(faceData == ROOM_FLOOR)  { return makeGloss(floorColor, 0.0, wallRough); }
    if(faceData == ROOM_LEFT)   { return makeGloss(warmColor,  0.0, wallRough); }
    if(faceData == ROOM_RIGHT)  { return makeGloss(coolColor,  0.0, wallRough); }
    return makeGloss(wallColor, 0.0, wallRough);
}
Medium medium_room(vec3 p){ return defaultMedium(); }


//---------------------------------------------------------------------
// the analytic intersections
//---------------------------------------------------------------------

float trace_lamp(Vector tv){
    return sphereTrace(tv, LAMP_P, LAMP_RADIUS);
}

float trace_room(Vector tv){
    return roomTrace(tv, ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the dispatchers
//---------------------------------------------------------------------

void sdfAll(vec3 p){
    gSDF[ID_MESA  ] = sdf_mesa(p);
    gSDF[ID_BEADS ] = sdf_beads(p);
    gSDF[ID_PILLAR] = sdf_pillar(p);
    gSDF[ID_HUSK  ] = sdf_husk(p);
    gSDF[ID_DICE  ] = sdf_dice(p);
    gSDF[ID_REEF  ] = sdf_reef(p);
    gSDF[ID_LAMP  ] = sdf_lamp(p);
    gSDF[ID_ROOM  ] = sdf_room(p);
}

Vector normalOf(int id, vec3 p){
    if(id == ID_MESA  ){ return normal_mesa(p); }
    if(id == ID_BEADS ){ return normal_beads(p); }
    if(id == ID_PILLAR){ return normal_pillar(p); }
    if(id == ID_HUSK  ){ return normal_husk(p); }
    if(id == ID_DICE  ){ return normal_dice(p); }
    if(id == ID_REEF  ){ return normal_reef(p); }
    if(id == ID_LAMP  ){ return normal_lamp(p); }
    return normal_room(p);
}

//no sheets in this scene: every object is a region with an interior
bool isSheet(int id){ return false; }

Material materialOf(int id, vec3 p, inout Vector n, bool front){
    if(id == ID_MESA  ){ return material_mesa(p, n); }
    if(id == ID_BEADS ){ return material_beads(p, n); }
    if(id == ID_PILLAR){ return material_pillar(p, n); }
    if(id == ID_HUSK  ){ return material_husk(p, n); }
    if(id == ID_DICE  ){ return material_dice(p, n); }
    if(id == ID_REEF  ){ return material_reef(p, n); }
    if(id == ID_LAMP  ){ return material_lamp(p, n); }
    return material_room(p, n);
}

Medium mediumOf(int id, vec3 p){
    if(id == ID_MESA  ){ return medium_mesa(p); }
    if(id == ID_BEADS ){ return medium_beads(p); }
    if(id == ID_PILLAR){ return medium_pillar(p); }
    if(id == ID_HUSK  ){ return medium_husk(p); }
    if(id == ID_DICE  ){ return medium_dice(p); }
    if(id == ID_REEF  ){ return medium_reef(p); }
    if(id == ID_LAMP  ){ return medium_lamp(p); }
    if(id == ID_ROOM  ){ return medium_room(p); }
    return defaultMedium();      //ID_NONE: open air
}


//---------------------------------------------------------------------
// the entry points
//---------------------------------------------------------------------

void buildScene(){}

float sdf_Scene(Vector tv){
    vec3 p = tv.pos;
    float d = maxDist;

    float b_mesa = bound_mesa(p);
    d = min(d, (b_mesa > BOUND_MARGIN) ? b_mesa : sdf_mesa(p));

    float b_beads = bound_beads(p);
    d = min(d, (b_beads > BOUND_MARGIN) ? b_beads : sdf_beads(p));

    float b_pillar = bound_pillar(p);
    d = min(d, (b_pillar > BOUND_MARGIN) ? b_pillar : sdf_pillar(p));

    float b_husk = bound_husk(p);
    d = min(d, (b_husk > BOUND_MARGIN) ? b_husk : sdf_husk(p));

    float b_dice = bound_dice(p);
    d = min(d, (b_dice > BOUND_MARGIN) ? b_dice : sdf_dice(p));

    float b_reef = bound_reef(p);
    d = min(d, (b_reef > BOUND_MARGIN) ? b_reef : sdf_reef(p));

    return d;
}

float trace_Scene(Vector tv){
    float d = maxDist;
    d = min(d, trace_lamp(tv));
    d = min(d, trace_room(tv));
    return d;
}
