//=====================================================================
// generated by scenegen from src/scene.js — do not edit by hand
//=====================================================================


//--- library: glsl/shapes/cocktailGlass.glsl ---
//----------------------------------------------------------------------------
// COCKTAIL GLASS
//
// glsl/shapes/ is the ported math-only library: plain functions of a point and
// some floats. No structs, no Frame, no Material, no at()/inside()/setData().
// Placement, materials and the region interface are all emitted by the scene.
//
// Ported from the old objects/shapes/cocktailGlass.glsl — the math is
// unchanged; only the CocktailGlass struct is gone from the signature.
//----------------------------------------------------------------------------


// The bowl wall, with the cavity carved out of it and the underside scooped by
// a ball. `cavity` hands back the sdf of the enclosed volume, so a caller can
// build the liquid from the SAME evaluation — one shape, two outputs.
//
// p is in the glass's own coordinates (origin at the bowl centre).
//@shape cocktailGlass -> wall, cavity
float cocktailGlassDistance(vec3 p, float radius, float height,
                            float thickness, float base, out float cavity){

    float outside = cylinderDistance(p, radius, height, 0.1);

    vec3  q      = p - vec3(0., 2.*base, 0.);
    float inside = cylinderDistance(q, radius - thickness, height, 0.05);

    float dist = max(outside, -inside);

    q = p + vec3(0., height - 1.75*base/2.5, 0.);
    float ball = length(q) - 2.*base/2.5;

    cavity = inside;
    return smax(dist, -ball, 0.2);
}


// A conservative bounding cylinder for the whole glass: the bowl plus the base
// ball below it, about the y axis. Never overestimates the distance to the
// surface, so it is safe as an acceleration bound.
float cocktailGlassBound(vec3 p, float radius, float height, float base){
    return bCyl(p, vec2(radius + 0.3, height + 2.*base + 1.));
}


//--- library: glsl/shapes/sphere.glsl ---
//----------------------------------------------------------------------------
// SPHERE
//
// glsl/shapes/ is the math-only library: plain functions of a point and some
// floats. No structs, no Frame, no Material, no at()/inside()/setData().
// Placement, materials and the region interface are emitted by the scene.
//----------------------------------------------------------------------------


// p is in the sphere's own coordinates (origin at the centre)
float sphereDistance(vec3 p, float radius){
    return length(p) - radius;
}


// Exact ray intersection, in world coordinates: the distance along tv to the
// sphere, or maxDist if it is not in front of us. tv.dir is unit length.
//
// A ray STARTING INSIDE takes the far root — glass needs that, since a
// transmitted ray has to find the far wall of the object it just entered.
float sphereTrace(Vector tv, vec3 centre, float radius){
    vec3  oc = tv.pos - centre;
    float b  = dot(oc, tv.dir);
    float c  = dot(oc, oc) - radius*radius;
    float disc = b*b - c;
    if(disc < 0.){ return maxDist; }

    float s = sqrt(disc);
    float t = -b - s;
    if(t < 0.){ t = -b + s; }
    if(t < 0.){ return maxDist; }
    return min(t, maxDist);
}


//--- library: glsl/shapes/room.glsl ---
//----------------------------------------------------------------------------
// ROOM — a closed box, seen from the inside.
//
// The room is ONE region whose solid is everything OUTSIDE the box, so the
// interior is open air and regionAt() returns ID_NONE there. Its six walls are
// not six objects: they are a material FIELD over that one region, read off by
// asking which face a point is nearest. roomFace() answers that.
//
// glsl/shapes/ is the math-only library: plain functions of a point and some
// floats. No structs, no Frame, no Material.
//----------------------------------------------------------------------------


const int ROOM_FLOOR   = 0;
const int ROOM_CEILING = 1;
const int ROOM_LEFT    = 2;
const int ROOM_RIGHT   = 3;
const int ROOM_FRONT   = 4;
const int ROOM_BACK    = 5;


// p is in the room's own coordinates (origin at the box centre).
// Negative in the WALLS, positive in the open interior — the sign convention
// every other region uses, just turned inside out.
float roomDistance(vec3 p, vec3 halfSize){
    return -bBox(p, halfSize);
}


// Exact ray intersection, in world coordinates. The ray is inside the box, so
// this is simply the distance at which it leaves: the nearest of the three
// far slab crossings.
float roomTrace(Vector tv, vec3 centre, vec3 halfSize){
    vec3  o  = tv.pos - centre;
    vec3  tm = max((-halfSize - o)/tv.dir, (halfSize - o)/tv.dir);
    float t  = min(tm.x, min(tm.y, tm.z));
    if(t < 0.){ return maxDist; }
    return min(t, maxDist);
}


// Which wall p is on (or nearest to) — a shape DATA output (docs/shape-data.md):
// a material that reads `faceData` gets it injected. d is negative inside the
// room, so its LARGEST component names the axis the point is closest to leaving
// through, and the sign of p picks which of that axis's two faces.
int roomFaceData(vec3 p, vec3 halfSize){
    vec3 d = abs(p) - halfSize;

    if(d.y >= d.x && d.y >= d.z){
        return (p.y > 0.) ? ROOM_CEILING : ROOM_FLOOR;
    }
    if(d.x >= d.z){
        return (p.x > 0.) ? ROOM_RIGHT : ROOM_LEFT;
    }
    return (p.z > 0.) ? ROOM_BACK : ROOM_FRONT;
}


//--- the objects, in declaration order (= containment priority, inner to outer)
const int ID_CUP   = 0;
const int ID_DRINK = 1;
const int ID_LIGHT = 2;
const int ID_ROOM  = 3;

const int N_OBJ = 4;
float gSDF[N_OBJ];


//--- placement and shape parameters ----------------------------------
const vec3 COCKTAIL_P = vec3(-1.0, 0.1, -1.2);
const float COCKTAIL_RADIUS    = 1.0;
const float COCKTAIL_HEIGHT    = 1.0;
const float COCKTAIL_THICKNESS = 0.1;
const float COCKTAIL_BASE      = 0.3;
const float DRINK_LEVEL        = COCKTAIL_HEIGHT/3.0;   //in the glass's own coordinates

const vec3  LIGHT_P      = vec3(-7.0, 4.0, 2.0);
const float LIGHT_RADIUS = 1.5;

const vec3 ROOM_P        = vec3(-5.75, 6.5, -5.0);
const vec3 ROOM_HALFSIZE = vec3(14.25, 7.5, 15.0);


//---------------------------------------------------------------------
// the region sdfs
//---------------------------------------------------------------------

void sdf_cocktail(vec3 p, out float cup, out float drink){
    vec3  q = p - COCKTAIL_P;
    float cavity;
    cup   = cocktailGlassDistance(q, COCKTAIL_RADIUS, COCKTAIL_HEIGHT, COCKTAIL_THICKNESS, COCKTAIL_BASE, cavity);
    drink = max(cavity, q.y - DRINK_LEVEL);
}

//single-region entry points, for the 4-tap normals
float sdf_cup(vec3 p){ float cup, drink; sdf_cocktail(p, cup, drink); return cup; }
float sdf_drink(vec3 p){ float cup, drink; sdf_cocktail(p, cup, drink); return drink; }

float sdf_light(vec3 p){
    return sphereDistance(p - LIGHT_P, LIGHT_RADIUS);
}

//the room SOLID is everything outside the box, so its interior is open air and
//regionAt() returns ID_NONE there
float sdf_room(vec3 p){
    return roomDistance(p - ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the bounds — the acceleration structure (sdf_Scene only; sdfAll stays exact)
//---------------------------------------------------------------------

float bound_cocktail(vec3 p){
    vec3 q = p - COCKTAIL_P;
    return cocktailGlassBound(q, COCKTAIL_RADIUS, COCKTAIL_HEIGHT, COCKTAIL_BASE);
}


//---------------------------------------------------------------------
// the normals — the 4-tap of each region's own sdf, in world coordinates
//---------------------------------------------------------------------
const float NRM_E = 0.0002;

Vector normal_cup(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_cup(p + k.xyy*NRM_E) + k.yyx*sdf_cup(p + k.yyx*NRM_E)
                              + k.yxy*sdf_cup(p + k.yxy*NRM_E) + k.xxx*sdf_cup(p + k.xxx*NRM_E) ));
}

Vector normal_drink(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_drink(p + k.xyy*NRM_E) + k.yyx*sdf_drink(p + k.yyx*NRM_E)
                              + k.yxy*sdf_drink(p + k.yxy*NRM_E) + k.xxx*sdf_drink(p + k.xxx*NRM_E) ));
}

Vector normal_light(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_light(p + k.xyy*NRM_E) + k.yyx*sdf_light(p + k.yyx*NRM_E)
                              + k.yxy*sdf_light(p + k.yxy*NRM_E) + k.xxx*sdf_light(p + k.xxx*NRM_E) ));
}

Vector normal_room(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_room(p + k.xyy*NRM_E) + k.yyx*sdf_room(p + k.yyx*NRM_E)
                              + k.yxy*sdf_room(p + k.yxy*NRM_E) + k.xxx*sdf_room(p + k.xxx*NRM_E) ));
}


//---------------------------------------------------------------------
// the materials
//  material_ gives the Surface plus this object's own Medium; medium_ gives
//  only the Medium, for when the object is merely the far side
//---------------------------------------------------------------------

Medium medium_cup(vec3 p){
    Medium m = defaultMedium();
    m.ior    = 1.5;
    m.absorb = 0.1*vec3(0.3, 0.05, 0.2);
    return m;
}
Material material_cup(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //glass
    m.interior = medium_cup(p);
    m.surf.transmit = 1.0;
    return m;
}

Medium medium_drink(vec3 p){
    Medium m = defaultMedium();
    m.ior    = 1.2;
    m.absorb = 3.0*(vec3(1.0) - vec3(204.0, 142.0, 105.0)/255.0 + 0.25*vec3(0.2, 1.0, 0.6));
    return m;
}
Material material_drink(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //glass
    m.interior = medium_drink(p);
    m.surf.transmit = 1.0;
    return m;
}

Material material_light(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //light
    m.surf.emit = 100.0*vec3(0.9);
    return m;
}
Medium   medium_light  (vec3 p){ return defaultMedium(); }

Material material_room(vec3 p, inout Vector n){
    vec3 q = p - ROOM_P;
    int faceData = roomFaceData(q, ROOM_HALFSIZE);
    if(faceData == ROOM_CEILING){ return makeLight(vec3(1.0), roomLight); }
    if(faceData == ROOM_FLOOR)  { return makeGloss(floorColor, 0.0, wallRough); }
    if(faceData == ROOM_LEFT)   { return makeGloss(warmColor,  0.0, wallRough); }
    if(faceData == ROOM_RIGHT)  { return makeGloss(coolColor,  0.0, wallRough); }
    return makeGloss(wallColor, 0.0, wallRough);
}
Medium medium_room(vec3 p){ return defaultMedium(); }


//---------------------------------------------------------------------
// the analytic intersections
//---------------------------------------------------------------------

float trace_light(Vector tv){
    return sphereTrace(tv, LIGHT_P, LIGHT_RADIUS);
}

float trace_room(Vector tv){
    return roomTrace(tv, ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the dispatchers
//---------------------------------------------------------------------

void sdfAll(vec3 p){
    sdf_cocktail(p, gSDF[ID_CUP], gSDF[ID_DRINK]);
    gSDF[ID_LIGHT] = sdf_light(p);
    gSDF[ID_ROOM ] = sdf_room(p);
}

Vector normalOf(int id, vec3 p){
    if(id == ID_CUP  ){ return normal_cup(p); }
    if(id == ID_DRINK){ return normal_drink(p); }
    if(id == ID_LIGHT){ return normal_light(p); }
    return normal_room(p);
}

//no sheets in this scene: every object is a region with an interior
bool isSheet(int id){ return false; }

Material materialOf(int id, vec3 p, inout Vector n, bool front){
    if(id == ID_CUP  ){ return material_cup(p, n); }
    if(id == ID_DRINK){ return material_drink(p, n); }
    if(id == ID_LIGHT){ return material_light(p, n); }
    return material_room(p, n);
}

Medium mediumOf(int id, vec3 p){
    if(id == ID_CUP  ){ return medium_cup(p); }
    if(id == ID_DRINK){ return medium_drink(p); }
    if(id == ID_LIGHT){ return medium_light(p); }
    if(id == ID_ROOM ){ return medium_room(p); }
    return defaultMedium();      //ID_NONE: open air
}


//---------------------------------------------------------------------
// the entry points
//---------------------------------------------------------------------

void buildScene(){}

float sdf_Scene(Vector tv){
    vec3 p = tv.pos;
    float d = maxDist;

    float b_cocktail = bound_cocktail(p);
    if(b_cocktail > BOUND_MARGIN){ d = min(d, b_cocktail); }
    else{
        float cup, drink;
        sdf_cocktail(p, cup, drink);
        d = min(d, min(cup, drink));
    }

    return d;
}

float trace_Scene(Vector tv){
    float d = maxDist;
    d = min(d, trace_light(tv));
    d = min(d, trace_room(tv));
    return d;
}
