//=====================================================================
// generated by scenegen from src/scene.js — do not edit by hand
//=====================================================================


//--- library: glsl/shapes/tilings/cubeGrid.glsl ---
//----------------------------------------------------------------------------
// CUBEGRID — a lattice of rounded bars, one per cell, standing on y = 0.
//
// After IQ's audio "equalizer city" (shadertoys/cube-grid.glsl), with the audio
// taken out: a STILL wants a height FIELD, not four moving bands. So a cell's
// height is a smooth district `swell` mixed with per-cell `jitter`, shaped by
// `contrast` — how big the neighbourhoods are, how ragged they are, and how few
// towers rise above them.
//
// THE DISTANCE is the one thing the original did not have to solve. It walked
// the grid cell by cell (a 2D DDA) and only ever measured the bar it was inside;
// a sphere tracer needs an estimate valid everywhere at once. So this measures
// the 3x3 cells around the query point and then FLOORS the result with the
// clearance to everything outside that block. Without the floor, a min over 9
// bars is an OVER-estimate — a tower two cells away can be nearer than all nine
// — and the marcher walks straight through it.
//
// `tiles` cuts the lattice to a finite block on CELL WALLS, so the edge is a
// clean last row of bars rather than a sawn one.
//
// glsl/shapes/ is the math-only library. Exposes a vec4 `cellData` output for
// coloring (docs/shape-data.md): the cell's id, its height fraction, how far up
// the bar the point sits, and the district swell.
//----------------------------------------------------------------------------


//the cell's own random number, in [0,1). fieldHash is the canonical hash
//(3Materials/fields.glsl) — a shapes file never rolls its own.
float cubeGrid_id(vec2 cell, float seed){
    return fieldHash(vec3(cell, seed));
}

//the cell's height fraction, in [0,1]: districts mixed with per-cell jitter,
//then shaped. contrast > 1 leaves a few towers standing over many low blocks.
float cubeGrid_f(vec2 cell, float clumpFreq, float jitter, float contrast, float seed){
    float swell = valueNoise(vec3(clumpFreq*cell, seed));
    float f     = mix(swell, cubeGrid_id(cell, seed), jitter);
    return pow(clamp(f, 0.0, 1.0), contrast);
}

//one bar: a box of footprint barHalf standing on y = 0, its edges rounded by
//bevel. The box is shrunk by the bevel before inflating, so barHalf and h stay
//the bar's TRUE half-width and height. A bar shorter than the bevel flattens
//into a paving slab rather than inverting.
float cubeGrid_bar(vec3 q, float h, float barHalf, float bevel){
    vec3 ext = vec3(max(barHalf - bevel, 0.0),
                    max(0.5*h    - bevel, 0.0),
                    max(barHalf - bevel, 0.0));
    return bBox(q - vec3(0.0, 0.5*h, 0.0), ext) - bevel;
}


// p is in the lattice's own coordinates: cell (0,0) spans [0,spacing] in x and z,
// and every bar stands on the plane y = 0.
float cubeGridDistance(vec3 p, float spacing, float barHalf, float bevel, float height,
                       float clumpFreq, float jitter, float contrast, float seed, vec2 tiles){
    vec2 base = floor(p.xz/spacing);
    vec2 frac = p.xz/spacing - base;              //where we sit in the home cell, [0,1)

    //---- the 3x3 block around us: the only bars that can be nearest ----------
    float d = 1.0e9;
    for(int j = -1; j <= 1; j++){
        for(int i = -1; i <= 1; i++){
            vec2  cell = base + vec2(float(i), float(j));
            float h    = height*cubeGrid_f(cell, clumpFreq, jitter, contrast, seed);
            vec3  q    = p - spacing*vec3(cell.x + 0.5, 0.0, cell.y + 0.5);
            d = min(d, cubeGrid_bar(q, h, barHalf, bevel));
        }
    }

    //---- and the floor that makes the estimate honest -----------------------
    //every cell we skipped lies outside the block, so it is at least `ring` away
    //horizontally; and no bar reaches above `height` or below y = 0, so it is at
    //least `clear` away vertically. The two clearances are orthogonal.
    float ring  = spacing*min(min(frac.x + 1.0, 2.0 - frac.x),
                              min(frac.y + 1.0, 2.0 - frac.y));
    float clear = max(max(p.y - height, 0.0), max(-p.y, 0.0));
    d = min(d, length(vec2(ring, clear)));

    //---- the block: cells |cell| <= tiles, cut on cell walls ----------------
    //bars are inset from their cell by spacing/2 - barHalf, so this never slices
    //one; outside the block it reads as the distance to the wall, an underestimate
    vec2  e     = abs(p.xz) - spacing*(tiles + 0.5);
    float block = min(max(e.x, e.y), 0.0) + length(max(e, 0.0));
    return max(d, block);
}


// the block, as a bounding box: the tile extent in xz, the tallest possible bar
// in y. IQ's own bounding volume was this same slab.
float cubeGridBound(vec3 p, float spacing, float bevel, float height, vec2 tiles){
    vec3 c   = vec3(0.0, 0.5*height, 0.0);
    vec3 ext = vec3(spacing*(tiles.x + 0.5), 0.5*height + bevel, spacing*(tiles.y + 0.5));
    return bBox(p - c, ext);
}


// the cell under q (shape data): (id, height fraction, height up the bar, swell).
// A bar is inset well inside its own cell, so a point ON one always resolves to
// the cell that owns it.
vec4 cubeGridCellData(vec3 q, float spacing, float height,
                      float clumpFreq, float jitter, float contrast, float seed){
    vec2  cell  = floor(q.xz/spacing);
    float f     = cubeGrid_f(cell, clumpFreq, jitter, contrast, seed);
    float swell = valueNoise(vec3(clumpFreq*cell, seed));
    float up    = clamp(q.y/max(height*f, 1.0e-3), 0.0, 1.0);
    return vec4(cubeGrid_id(cell, seed), f, up, swell);
}


//--- library: glsl/shapes/primitives/plane.glsl ---
//----------------------------------------------------------------------------
// PLANE — a half-space, seen from the side its normal points toward.
//
// Exact and analytic, so a ray never marches toward it — worth having, since
// the marched step is the PERPENDICULAR distance, which crawls on a ray running
// nearly parallel to the plane, and a ground plane is used at exactly that angle.
//
// CAVEAT, learned the hard way: an analytic plane is NOT a drop-in replacement
// for a floor term inside a fractal's own DE. Folding `min(p.z - h, dFractal)`
// into the estimator makes the floor CAP the fractal — it hides everything
// below it. Split that floor out into a plane object and rays fall straight
// through into the infinitely fine detail underneath, and the plane is never
// reached. Use this for a floor the scene genuinely owns.
//
// glsl/shapes/ is the math-only library: plain functions of a point and some
// floats. No structs, no Frame, no Material.
//----------------------------------------------------------------------------


// p is in the plane's own coordinates (origin ON the plane). Negative in the
// solid half-space behind it, positive in the open half-space it faces.
float planeDistance(vec3 p, vec3 normal){
    return dot(p, normal);
}


// Exact ray intersection, in world coordinates: the distance along tv to the
// plane, or maxDist if it is not in front of us. A ray running away from the
// plane, or parallel to it, never meets it — and costs nothing to find out.
float planeTrace(Vector tv, vec3 centre, vec3 normal){
    float dn = dot(tv.dir, normal);
    if(abs(dn) < 1.0e-9){ return maxDist; }     //parallel
    float t = -dot(tv.pos - centre, normal)/dn;
    if(t < 0.){ return maxDist; }
    return min(t, maxDist);
}


//--- library: glsl/shapes/primitives/sphere.glsl ---
//----------------------------------------------------------------------------
// SPHERE
//
// glsl/shapes/ is the math-only library: plain functions of a point and some
// floats. No structs, no Frame, no Material, no at()/inside()/setData().
// Placement, materials and the region interface are emitted by the scene.
//----------------------------------------------------------------------------


// p is in the sphere's own coordinates (origin at the centre)
float sphereDistance(vec3 p, float radius){
    return length(p) - radius;
}


// Exact ray intersection, in world coordinates: the distance along tv to the
// sphere, or maxDist if it is not in front of us. tv.dir is unit length.
//
// A ray STARTING INSIDE takes the far root — glass needs that, since a
// transmitted ray has to find the far wall of the object it just entered.
float sphereTrace(Vector tv, vec3 centre, float radius){
    vec3  oc = tv.pos - centre;
    float b  = dot(oc, tv.dir);
    float c  = dot(oc, oc) - radius*radius;
    float disc = b*b - c;
    if(disc < 0.){ return maxDist; }

    float s = sqrt(disc);
    float t = -b - s;
    if(t < 0.){ t = -b + s; }
    if(t < 0.){ return maxDist; }
    return min(t, maxDist);
}


//--- the objects, in declaration order (= containment priority, inner to outer)
const int ID_CITY   = 0;
const int ID_GROUND = 1;
const int ID_LIGHT  = 2;

const int N_OBJ = 3;
float gSDF[N_OBJ];


//--- placement and shape parameters ----------------------------------
const vec3  CITY_P       = vec3(0.0);
const float CITY_SPACING = 1.0;
const float CITY_BARHALF = 0.4;
const float CITY_BEVEL   = 0.1;
const vec2  CITY_TILES   = vec2(9.0, 9.0);

const vec3 GROUND_P      = vec3(0.0);
const vec3 GROUND_NORMAL = vec3(0.0, 1.0, 0.0);

const vec3  LIGHT_P      = vec3(17.0, 15.0, 20.0);
const float LIGHT_RADIUS = 7.0;


//---------------------------------------------------------------------
// the region sdfs
//---------------------------------------------------------------------

float sdf_city(vec3 p){
    return cubeGridDistance(p - CITY_P, CITY_SPACING, CITY_BARHALF, CITY_BEVEL, towerHeight, districtSize, cellJitter, heightPower, citySeed, CITY_TILES);
}

float sdf_ground(vec3 p){
    return planeDistance(p - GROUND_P, GROUND_NORMAL);
}

float sdf_light(vec3 p){
    return sphereDistance(p - LIGHT_P, LIGHT_RADIUS);
}


//---------------------------------------------------------------------
// the bounds — the acceleration structure (sdf_Scene only; sdfAll stays exact)
//---------------------------------------------------------------------

float bound_city(vec3 p){
    return cubeGridBound(p - CITY_P, CITY_SPACING, CITY_BEVEL, towerHeight, CITY_TILES);
}


//---------------------------------------------------------------------
// the normals — the 4-tap of each region's own sdf, in world coordinates
//---------------------------------------------------------------------
const float NRM_E = 0.0002;

Vector normal_city(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_city(p + k.xyy*NRM_E) + k.yyx*sdf_city(p + k.yyx*NRM_E)
                              + k.yxy*sdf_city(p + k.yxy*NRM_E) + k.xxx*sdf_city(p + k.xxx*NRM_E) ));
}

Vector normal_ground(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_ground(p + k.xyy*NRM_E) + k.yyx*sdf_ground(p + k.yyx*NRM_E)
                              + k.yxy*sdf_ground(p + k.yxy*NRM_E) + k.xxx*sdf_ground(p + k.xxx*NRM_E) ));
}

Vector normal_light(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_light(p + k.xyy*NRM_E) + k.yyx*sdf_light(p + k.yyx*NRM_E)
                              + k.yxy*sdf_light(p + k.yxy*NRM_E) + k.xxx*sdf_light(p + k.xxx*NRM_E) ));
}


//---------------------------------------------------------------------
// the materials
//  material_ gives the Surface plus this object's own Medium; medium_ gives
//  only the Medium, for when the object is merely the far side
//---------------------------------------------------------------------

Material material_city(vec3 p, inout Vector n){
    vec3 q = p - CITY_P;
    vec4 cellData = cubeGridCellData(q, CITY_SPACING, towerHeight, districtSize, cellJitter, heightPower, citySeed);
    float id    = cellData.x;
    float f     = cellData.y;
    float up    = cellData.z;
    float swell = cellData.w;

    //the palette rides the district, nudged by the cell's own id
    float t = mix(swell, id, 0.3) + paletteShift;
    vec3  c = 0.5 + 0.5*cos(6.2831*(t + vec3(0.0, 0.33, 0.67)));

    //a handful of bars are lamps, standing where the towers are
    if(id > 1.0 - lampChance){
        return makeLight(mix(c, vec3(1.0), 0.15), lampPower*(0.35 + f));
    }
    //a few more are bare metal
    if(id < metalChance){
        return makeMetal(mix(c, vec3(0.86, 0.88, 0.92), 0.35), 1.0, barRough);
    }
    //the rest: low blocks read darker than towers, and every bar
    //shades down toward its base
    c *= mix(0.5, 1.0, f);
    c  = mix(0.62*c, c, up);
    return makeGloss(c, 0.06, barRough);
}
Medium medium_city(vec3 p){ return defaultMedium(); }

Material material_ground(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //gloss
    m.surf.diffuse   = vec3(0.055, 0.052, 0.06);
    m.surf.roughness = 0.35;
    m.surf.gloss     = 0.04;
    return m;
}
Medium   medium_ground  (vec3 p){ return defaultMedium(); }

Material material_light(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //light
    m.surf.emit = 26.0*vec3(1.0, 0.88, 0.72);
    return m;
}
Medium   medium_light  (vec3 p){ return defaultMedium(); }


//---------------------------------------------------------------------
// the analytic intersections
//---------------------------------------------------------------------

float trace_ground(Vector tv){
    return planeTrace(tv, GROUND_P, GROUND_NORMAL);
}

float trace_light(Vector tv){
    return sphereTrace(tv, LIGHT_P, LIGHT_RADIUS);
}


//---------------------------------------------------------------------
// the dispatchers
//---------------------------------------------------------------------

void sdfAll(vec3 p){
    gSDF[ID_CITY  ] = sdf_city(p);
    gSDF[ID_GROUND] = sdf_ground(p);
    gSDF[ID_LIGHT ] = sdf_light(p);
}

Vector normalOf(int id, vec3 p){
    if(id == ID_CITY  ){ return normal_city(p); }
    if(id == ID_GROUND){ return normal_ground(p); }
    return normal_light(p);
}

//no sheets in this scene: every object is a region with an interior
bool isSheet(int id){ return false; }

Material materialOf(int id, vec3 p, inout Vector n, bool front){
    if(id == ID_CITY  ){ return material_city(p, n); }
    if(id == ID_GROUND){ return material_ground(p, n); }
    return material_light(p, n);
}

Medium mediumOf(int id, vec3 p){
    if(id == ID_CITY  ){ return medium_city(p); }
    if(id == ID_GROUND){ return medium_ground(p); }
    if(id == ID_LIGHT ){ return medium_light(p); }
    return defaultMedium();      //ID_NONE: open air
}


//---------------------------------------------------------------------
// the entry points
//---------------------------------------------------------------------

void buildScene(){}

float sdf_Scene(Vector tv){
    vec3 p = tv.pos;
    float d = maxDist;

    float b_city = bound_city(p);
    d = min(d, (b_city > BOUND_MARGIN) ? b_city : sdf_city(p));

    return d;
}

float trace_Scene(Vector tv){
    float d = maxDist;
    d = min(d, trace_ground(tv));
    d = min(d, trace_light(tv));
    return d;
}
