//=====================================================================
// generated by scenegen from src/scene.js — do not edit by hand
//=====================================================================


//--- library: glsl/shapes/primitives/line.glsl ---
//----------------------------------------------------------------------------
// LINE — an infinite straight line thickened to `radius`: a cylinder of
// unbounded length about an arbitrary axis.
//
// `point` is any point on the axis and `dir` its direction, which MUST be unit
// length (the caller's job — normalizing here would cost a sqrt on every line of
// every march step, and the data that drives this is normalized once upstream).
//
// UNBOUNDED, so it has no <stem>Bound and never will: clip it, or use it inside
// something that is already clipped. The cubic-surface scene min's 27 of these
// and intersects the result with its bounding sphere.
//
// glsl/shapes/primitives/ holds the exact closed forms; this one is CONTENT
// rather than vocabulary (it is not in _vocabulary.glsl), so it is inlined only
// into scenes that name it — via lib.line, or via uses: [lib.line] from an
// authored body that calls it with its own per-line data.
//----------------------------------------------------------------------------


// p is in the line's own coordinates. dir must be unit length.
float lineDistance(vec3 p, vec3 point, vec3 dir, float radius){
    vec3 d = p - point;
    return length(d - dot(d, dir)*dir) - radius;
}


//--- library: glsl/shapes/environments/room.glsl ---
//----------------------------------------------------------------------------
// ROOM — a closed box, seen from the inside.
//
// The room is ONE region whose solid is everything OUTSIDE the box, so the
// interior is open air and regionAt() returns ID_NONE there. Its six walls are
// not six objects: they are a material FIELD over that one region, read off by
// asking which face a point is nearest. roomFace() answers that.
//
// glsl/shapes/ is the math-only library: plain functions of a point and some
// floats. No structs, no Frame, no Material.
//----------------------------------------------------------------------------


const int ROOM_FLOOR   = 0;
const int ROOM_CEILING = 1;
const int ROOM_LEFT    = 2;
const int ROOM_RIGHT   = 3;
const int ROOM_FRONT   = 4;
const int ROOM_BACK    = 5;


// p is in the room's own coordinates (origin at the box centre).
// Negative in the WALLS, positive in the open interior — the sign convention
// every other region uses, just turned inside out.
float roomDistance(vec3 p, vec3 halfSize){
    return -boxDistance(p, halfSize);
}


// Exact ray intersection, in world coordinates. The ray is inside the box, so
// this is simply the distance at which it leaves: the nearest of the three
// far slab crossings.
float roomTrace(Vector tv, vec3 centre, vec3 halfSize){
    vec3  o  = tv.pos - centre;
    vec3  tm = max((-halfSize - o)/tv.dir, (halfSize - o)/tv.dir);
    float t  = min(tm.x, min(tm.y, tm.z));
    if(t < 0.){ return maxDist; }
    return min(t, maxDist);
}


// Which wall p is on (or nearest to) — a shape DATA output (docs/shape-data.md):
// a material that reads `faceData` gets it injected. d is negative inside the
// room, so its LARGEST component names the axis the point is closest to leaving
// through, and the sign of p picks which of that axis's two faces.
int roomFaceData(vec3 p, vec3 halfSize){
    vec3 d = abs(p) - halfSize;

    if(d.y >= d.x && d.y >= d.z){
        return (p.y > 0.) ? ROOM_CEILING : ROOM_FLOOR;
    }
    if(d.x >= d.z){
        return (p.x > 0.) ? ROOM_RIGHT : ROOM_LEFT;
    }
    return (p.z > 0.) ? ROOM_BACK : ROOM_FRONT;
}


struct Line2D  { vec2 point; vec2 dir; };
struct Conic2D { float c0, c1, c2, c3, c4, c5; };


// Auto-generated blowup diagram data (2D scene).
// Assumes: struct Line2D { vec2 point; vec2 dir; };
// Assumes: struct Conic2D { float a, b, c, d, e, f; };
//   represents a*x^2 + b*xy + c*x + d*y^2 + e*y + f = 0

const vec2 POINTS[6] = vec2[6](
  vec2(-0.69999999, -0.50000000),
  vec2(0.35566583, 0.08955224),
  vec2(0.20000000, 0.89999998),
  vec2(-0.69644332, 0.02442334),
  vec2(0.28287840, -0.76255089),
  vec2(-0.89999998, 0.10000000)
);

const Line2D PLANE_LINES[15] = Line2D[15](
  Line2D(vec2(-0.69999999, -0.50000000), vec2(0.87307681, 0.48758270)),
  Line2D(vec2(-0.69999999, -0.50000000), vec2(0.54075759, 0.84117847)),
  Line2D(vec2(-0.69999999, -0.50000000), vec2(0.00678190, 0.99997700)),
  Line2D(vec2(-0.69999999, -0.50000000), vec2(0.96612473, -0.25807558)),
  Line2D(vec2(-0.69999999, -0.50000000), vec2(-0.31622775, 0.94868330)),
  Line2D(vec2(0.35566583, 0.08955224), vec2(-0.18862595, 0.98204901)),
  Line2D(vec2(0.35566583, 0.08955224), vec2(-0.99808949, -0.06178491)),
  Line2D(vec2(0.35566583, 0.08955224), vec2(-0.08511097, -0.99637148)),
  Line2D(vec2(0.35566583, 0.08955224), vec2(-0.99996539, 0.00832021)),
  Line2D(vec2(0.20000000, 0.89999998), vec2(-0.71538382, -0.69873170)),
  Line2D(vec2(0.20000000, 0.89999998), vec2(0.04978832, -0.99875979)),
  Line2D(vec2(0.20000000, 0.89999998), vec2(-0.80873609, -0.58817169)),
  Line2D(vec2(-0.69644332, 0.02442334), vec2(0.77950144, -0.62640043)),
  Line2D(vec2(-0.69644332, 0.02442334), vec2(-0.93747050, 0.34806473)),
  Line2D(vec2(0.28287840, -0.76255089), vec2(-0.80799602, 0.58918795))
);

const Conic2D PLANE_CONICS[6] = Conic2D[6](
  Conic2D(-4.05495405, -12.39428616, -0.98176360, -1.36032701, 2.99043012, 1.00000000),
  Conic2D(2.42081380, 1.97098136, 3.07525420, -2.67358398, 0.10993669, 1.00000000),
  Conic2D(246.22955322, -267.97973633, 151.82333374, -1203.99597168, -758.83148193, 1.00000000),
  Conic2D(-3.16287756, -0.98534220, -1.62567866, -0.64199936, 0.16559105, 1.00000000),
  Conic2D(-1.79446745, -13.80975819, 0.32837322, 8.24482441, -5.76271915, 1.00000000),
  Conic2D(-4.00074482, 0.24726184, -1.36191034, -0.59938115, -0.14066280, 1.00000000)
);


//the conic Q(x,z), and its gradient lifted to 3D. Q does not involve y, so
//the y component of the gradient is 0 — which is exactly what makes
//opCurveTube's projection step a no-op here and the maths reduce to the
//original's sqrt(dConic^2 + y^2).
float plateConicVal(vec2 xz, Conic2D c){
    float x = xz.x, z = xz.y;
    return c.c0*x*x + c.c1*x*z + c.c2*x + c.c3*z*z + c.c4*z + c.c5;
}
vec3 plateConicGrad(vec2 xz, Conic2D c){
    float x = xz.x, z = xz.y;
    return vec3(2.0*c.c0*x + c.c1*z + c.c2,
                0.0,
                c.c1*x + 2.0*c.c3*z + c.c4);
}

//the square column the diagram is cut to (infinite in y: the tubes are thin
//around y = 0 anyway, and the plate itself is a box)
float plateRegion(vec3 p, float halfWidth){
    vec2 d = abs(p.xz) - vec2(halfWidth);
    return max(d.x, d.y);
}

//nearest of the 15 lines through pairs of the six points, tubed. Each lies
//flat in y = 0, so an ordinary 3D line does the job.
float plateLineDist(vec3 p, float r){
    float d = 1.0e6;
    for(int i = 0; i < 15; i++){
        Line2D l = PLANE_LINES[i];
        d = min(d, lineDistance(p, vec3(l.point.x, 0.0, l.point.y),
                                   vec3(l.dir.x,   0.0, l.dir.y), r));
    }
    return d;
}

//nearest of the 6 conics, as a tube around {Q = 0} intersect {y = 0}
float plateConicDist(vec3 p, float r){
    float d = 1.0e6;
    for(int i = 0; i < 6; i++){
        Conic2D c = PLANE_CONICS[i];
        d = min(d, opCurveTube(plateConicVal(p.xz, c), plateConicGrad(p.xz, c),
                               p.y, vec3(0.0, 1.0, 0.0), r));
    }
    return d;
}

//the six blown-up points, as checkers standing on the plate. cylinderDistance
//adds its fillet to the HEIGHT (see primitives/cylinder.glsl), so the height
//argument is the true half-height minus the rounding.
float plateCheckerDist(vec3 p, float r, float halfH, float rnd, float yOff){
    float d = 1.0e6;
    for(int i = 0; i < 6; i++){
        vec3 c = p - vec3(POINTS[i].x, yOff, POINTS[i].y);
        d = min(d, cylinderDistance(c, r, halfH - rnd, rnd));
    }
    return d;
}


//--- the objects, in declaration order (= containment priority, inner to outer)
const int ID_PLATE    = 0;
const int ID_CHECKERS = 1;
const int ID_LINES    = 2;
const int ID_CONICS   = 3;
const int ID_KEY      = 4;
const int ID_ROOM     = 5;

const int N_OBJ = 6;
float gSDF[N_OBJ];


//--- placement and shape parameters ----------------------------------
const vec3 DIAGRAM_P = vec3(0.0);
const float PLATE_HALF  = 2.0;    //the plate's xz half-width
const float PLATE_THICK = 0.05;   //and its half-thickness
const float PLATE_ROUND = 0.02;   //edge fillet (inflates, as the old Box did)
const float PLATE_TOP   = 0.05;   //curves ride the plate's top face
const float CHECK_HALF  = 0.03;   //checker half-height
const float CHECK_ROUND = 0.01;
const float CHECK_Y     = 0.08;   //checkers sit above the plate

const vec3  KEY_P      = vec3(-12.0, 8.0, 2.0);
const float KEY_RADIUS = 1.5;

const vec3 ROOM_P        = vec3(-5.75, 5.75, -3.0);
const vec3 ROOM_HALFSIZE = vec3(14.25, 8.25, 17.0);


//---------------------------------------------------------------------
// the region sdfs
//---------------------------------------------------------------------

void sdf_diagram(vec3 p, out float plate, out float checkers, out float lines, out float conics){
    vec3  q = p - DIAGRAM_P;
    float region = plateRegion(q, PLATE_HALF);

    //the glass plate: a rounded slab. The old Box subtracted its
    //rounding from the distance, so the fillet INFLATES the extents.
    plate = boxDistance(q, vec3(PLATE_HALF, PLATE_THICK, PLATE_HALF)) - PLATE_ROUND;

    //the six points
    checkers = plateCheckerDist(q, checkerRadius, CHECK_HALF, CHECK_ROUND, CHECK_Y);

    //the 15 lines and 6 conics, riding the plate's top face and cut
    //to the plate's outline
    vec3 top = q - vec3(0.0, PLATE_TOP, 0.0);
    lines  = max(plateLineDist(top,  curveRadius), region);
    conics = max(plateConicDist(top, curveRadius), region);
}

//single-region entry points, for the 4-tap normals
float sdf_plate(vec3 p){ float plate, checkers, lines, conics; sdf_diagram(p, plate, checkers, lines, conics); return plate; }
float sdf_checkers(vec3 p){ float plate, checkers, lines, conics; sdf_diagram(p, plate, checkers, lines, conics); return checkers; }
float sdf_lines(vec3 p){ float plate, checkers, lines, conics; sdf_diagram(p, plate, checkers, lines, conics); return lines; }
float sdf_conics(vec3 p){ float plate, checkers, lines, conics; sdf_diagram(p, plate, checkers, lines, conics); return conics; }

float sdf_key(vec3 p){
    return sphereDistance(p - KEY_P, KEY_RADIUS);
}

//the room SOLID is everything outside the box, so its interior is open air and
//regionAt() returns ID_NONE there
float sdf_room(vec3 p){
    return roomDistance(p - ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the bounds — the acceleration structure (sdf_Scene only; sdfAll stays exact)
//---------------------------------------------------------------------

float bound_diagram(vec3 p){
    vec3 q = p - DIAGRAM_P;
    return length(q - vec3(0.0, 0.05, 0.0)) - 2.95;
}


//---------------------------------------------------------------------
// the normals — the 4-tap of each region's own sdf, in world coordinates
//---------------------------------------------------------------------
const float NRM_E = 0.0002;

Vector normal_plate(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_plate(p + k.xyy*NRM_E) + k.yyx*sdf_plate(p + k.yyx*NRM_E)
                              + k.yxy*sdf_plate(p + k.yxy*NRM_E) + k.xxx*sdf_plate(p + k.xxx*NRM_E) ));
}

Vector normal_checkers(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_checkers(p + k.xyy*NRM_E) + k.yyx*sdf_checkers(p + k.yyx*NRM_E)
                              + k.yxy*sdf_checkers(p + k.yxy*NRM_E) + k.xxx*sdf_checkers(p + k.xxx*NRM_E) ));
}

Vector normal_lines(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_lines(p + k.xyy*NRM_E) + k.yyx*sdf_lines(p + k.yyx*NRM_E)
                              + k.yxy*sdf_lines(p + k.yxy*NRM_E) + k.xxx*sdf_lines(p + k.xxx*NRM_E) ));
}

Vector normal_conics(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_conics(p + k.xyy*NRM_E) + k.yyx*sdf_conics(p + k.yyx*NRM_E)
                              + k.yxy*sdf_conics(p + k.yxy*NRM_E) + k.xxx*sdf_conics(p + k.xxx*NRM_E) ));
}

Vector normal_key(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_key(p + k.xyy*NRM_E) + k.yyx*sdf_key(p + k.yyx*NRM_E)
                              + k.yxy*sdf_key(p + k.yxy*NRM_E) + k.xxx*sdf_key(p + k.xxx*NRM_E) ));
}

Vector normal_room(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_room(p + k.xyy*NRM_E) + k.yyx*sdf_room(p + k.yyx*NRM_E)
                              + k.yxy*sdf_room(p + k.yxy*NRM_E) + k.xxx*sdf_room(p + k.xxx*NRM_E) ));
}


//---------------------------------------------------------------------
// the materials
//  material_ gives the Surface plus this object's own Medium; medium_ gives
//  only the Medium, for when the object is merely the far side
//---------------------------------------------------------------------

Medium medium_plate(vec3 p){
    Medium m = defaultMedium();
    m.ior    = 1.5;
    m.absorb = vec3(0.5, 0.3, 0.1);
    return m;
}
Material material_plate(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //glass
    m.interior = medium_plate(p);
    m.surf.transmit = 1.0;
    return m;
}

Material material_checkers(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //metal
    m.surf.diffuse   = vec3(0.9, 0.25, 0.2);
    m.surf.specular  = vec3(0.9, 0.25, 0.2);
    m.surf.roughness = 0.1;
    m.surf.gloss     = 0.8;
    return m;
}
Medium   medium_checkers  (vec3 p){ return defaultMedium(); }

Material material_lines(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //metal
    m.surf.diffuse   = vec3(0.55);
    m.surf.specular  = vec3(0.55);
    m.surf.roughness = 0.1;
    m.surf.gloss     = 0.8;
    return m;
}
Medium   medium_lines  (vec3 p){ return defaultMedium(); }

Material material_conics(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //metal
    m.surf.diffuse   = vec3(0.2, 0.45, 0.9);
    m.surf.specular  = vec3(0.2, 0.45, 0.9);
    m.surf.roughness = 0.1;
    m.surf.gloss     = 0.8;
    return m;
}
Medium   medium_conics  (vec3 p){ return defaultMedium(); }

Material material_key(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //light
    m.surf.emit = 60.0*vec3(1.0);
    return m;
}
Medium   medium_key  (vec3 p){ return defaultMedium(); }

Material material_room(vec3 p, inout Vector n){
    vec3 q = p - ROOM_P;
    int faceData = roomFaceData(q, ROOM_HALFSIZE);
    if(faceData == ROOM_CEILING){ return makeLight(vec3(1.0), roomLight); }
    if(faceData == ROOM_FLOOR)  { return makeGloss(floorColor, 0.0, wallRough); }
    if(faceData == ROOM_LEFT)   { return makeGloss(warmColor,  0.0, wallRough); }
    if(faceData == ROOM_RIGHT)  { return makeGloss(coolColor,  0.0, wallRough); }
    return makeGloss(wallColor, 0.0, wallRough);
}
Medium medium_room(vec3 p){ return defaultMedium(); }


//---------------------------------------------------------------------
// the analytic intersections
//---------------------------------------------------------------------

float trace_key(Vector tv){
    return sphereTrace(tv, KEY_P, KEY_RADIUS);
}

float trace_room(Vector tv){
    return roomTrace(tv, ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the dispatchers
//---------------------------------------------------------------------

void sdfAll(vec3 p){
    sdf_diagram(p, gSDF[ID_PLATE], gSDF[ID_CHECKERS], gSDF[ID_LINES], gSDF[ID_CONICS]);
    gSDF[ID_KEY     ] = sdf_key(p);
    gSDF[ID_ROOM    ] = sdf_room(p);
}

Vector normalOf(int id, vec3 p){
    if(id == ID_PLATE   ){ return normal_plate(p); }
    if(id == ID_CHECKERS){ return normal_checkers(p); }
    if(id == ID_LINES   ){ return normal_lines(p); }
    if(id == ID_CONICS  ){ return normal_conics(p); }
    if(id == ID_KEY     ){ return normal_key(p); }
    return normal_room(p);
}

//no sheets in this scene: every object is a region with an interior
bool isSheet(int id){ return false; }

Material materialOf(int id, vec3 p, inout Vector n, bool front){
    if(id == ID_PLATE   ){ return material_plate(p, n); }
    if(id == ID_CHECKERS){ return material_checkers(p, n); }
    if(id == ID_LINES   ){ return material_lines(p, n); }
    if(id == ID_CONICS  ){ return material_conics(p, n); }
    if(id == ID_KEY     ){ return material_key(p, n); }
    return material_room(p, n);
}

Medium mediumOf(int id, vec3 p){
    if(id == ID_PLATE   ){ return medium_plate(p); }
    if(id == ID_CHECKERS){ return medium_checkers(p); }
    if(id == ID_LINES   ){ return medium_lines(p); }
    if(id == ID_CONICS  ){ return medium_conics(p); }
    if(id == ID_KEY     ){ return medium_key(p); }
    if(id == ID_ROOM    ){ return medium_room(p); }
    return defaultMedium();      //ID_NONE: open air
}


//---------------------------------------------------------------------
// the entry points
//---------------------------------------------------------------------

void buildScene(){}

float sdf_Scene(Vector tv){
    vec3 p = tv.pos;
    float d = maxDist;

    float b_diagram = bound_diagram(p);
    if(b_diagram > BOUND_MARGIN){ d = min(d, b_diagram); }
    else{
        float plate, checkers, lines, conics;
        sdf_diagram(p, plate, checkers, lines, conics);
        d = min(d, min(min(min(plate, checkers), lines), conics));
    }

    return d;
}

float trace_Scene(Vector tv){
    float d = maxDist;
    d = min(d, trace_key(tv));
    d = min(d, trace_room(tv));
    return d;
}
