//=====================================================================
// generated by scenegen from src/scene.js — do not edit by hand
//=====================================================================


//--- library: glsl/shapes/primitives/line.glsl ---
//----------------------------------------------------------------------------
// LINE — an infinite straight line thickened to `radius`: a cylinder of
// unbounded length about an arbitrary axis.
//
// `point` is any point on the axis and `dir` its direction, which MUST be unit
// length (the caller's job — normalizing here would cost a sqrt on every line of
// every march step, and the data that drives this is normalized once upstream).
//
// UNBOUNDED, so it has no <stem>Bound and never will: clip it, or use it inside
// something that is already clipped. The cubic-surface scene min's 27 of these
// and intersects the result with its bounding sphere.
//
// glsl/shapes/primitives/ holds the exact closed forms; this one is CONTENT
// rather than vocabulary (it is not in _vocabulary.glsl), so it is inlined only
// into scenes that name it — via lib.line, or via uses: [lib.line] from an
// authored body that calls it with its own per-line data.
//----------------------------------------------------------------------------


// p is in the line's own coordinates. dir must be unit length.
float lineDistance(vec3 p, vec3 point, vec3 dir, float radius){
    vec3 d = p - point;
    return length(d - dot(d, dir)*dir) - radius;
}


//--- library: glsl/shapes/environments/room.glsl ---
//----------------------------------------------------------------------------
// ROOM — a closed box, seen from the inside.
//
// The room is ONE region whose solid is everything OUTSIDE the box, so the
// interior is open air and regionAt() returns ID_NONE there. Its six walls are
// not six objects: they are a material FIELD over that one region, read off by
// asking which face a point is nearest. roomFace() answers that.
//
// glsl/shapes/ is the math-only library: plain functions of a point and some
// floats. No structs, no Frame, no Material.
//----------------------------------------------------------------------------


const int ROOM_FLOOR   = 0;
const int ROOM_CEILING = 1;
const int ROOM_LEFT    = 2;
const int ROOM_RIGHT   = 3;
const int ROOM_FRONT   = 4;
const int ROOM_BACK    = 5;


// p is in the room's own coordinates (origin at the box centre).
// Negative in the WALLS, positive in the open interior — the sign convention
// every other region uses, just turned inside out.
float roomDistance(vec3 p, vec3 halfSize){
    return -boxDistance(p, halfSize);
}


// Exact ray intersection, in world coordinates. The ray is inside the box, so
// this is simply the distance at which it leaves: the nearest of the three
// far slab crossings.
float roomTrace(Vector tv, vec3 centre, vec3 halfSize){
    vec3  o  = tv.pos - centre;
    vec3  tm = max((-halfSize - o)/tv.dir, (halfSize - o)/tv.dir);
    float t  = min(tm.x, min(tm.y, tm.z));
    if(t < 0.){ return maxDist; }
    return min(t, maxDist);
}


// Which wall p is on (or nearest to) — a shape DATA output (docs/shape-data.md):
// a material that reads `faceData` gets it injected. d is negative inside the
// room, so its LARGEST component names the axis the point is closest to leaving
// through, and the sign of p picks which of that axis's two faces.
int roomFaceData(vec3 p, vec3 halfSize){
    vec3 d = abs(p) - halfSize;

    if(d.y >= d.x && d.y >= d.z){
        return (p.y > 0.) ? ROOM_CEILING : ROOM_FLOOR;
    }
    if(d.x >= d.z){
        return (p.x > 0.) ? ROOM_RIGHT : ROOM_LEFT;
    }
    return (p.z > 0.) ? ROOM_BACK : ROOM_FRONT;
}


struct Line { vec3 point; vec3 dir; };


// Auto-generated cubic surface data (3D scene).
// Assumes: struct Line { vec3 point; vec3 dir; };

const float C[20] = float[20](
  0.00000000,
  -0.00000000,
  -22.59033526,
  9.55038426,
  22.59033526,
  -6.64154207,
  -36.20846137,
  45.06034515,
  -9.77803069,
  -1.54492667,
  -2.90884219,
  -8.85188378,
  5.05671272,
  4.72131797,
  15.37675180,
  -1.00000000,
  -13.83182514,
  1.00000000,
  0.00000000,
  0.00000000
);

const Line PAIR_LINES[15] = Line[15](
  Line(vec3(-0.22200667, 0.16547733, -0.66459422), vec3(0.35761336, -0.24884481, 0.90010496)),
  Line(vec3(-0.06368645, 0.10061345, -0.15870238), vec3(0.32222609, 0.29608952, 0.89916703)),
  Line(vec3(0.16834240, 1.66149503, 0.43826031), vec3(0.99995262, 0.00973379, 0.00009438)),
  Line(vec3(-0.39048088, 0.71440074, -0.87968795), vec3(0.20920202, -0.76552498, 0.60844558)),
  Line(vec3(-0.05686488, 1.47060935, -0.21353384), vec3(0.94928104, -0.28660778, 0.12931159)),
  Line(vec3(-3.16904340, -1.00867855, -1.50698045), vec3(-0.87178774, -0.39721548, -0.28671589)),
  Line(vec3(0.00024691, 0.00302516, 0.06782025), vec3(0.03910042, 0.98247944, -0.18222323)),
  Line(vec3(1.62877836, 0.09420336, 0.89529842), vec3(0.97039620, -0.23126281, 0.06963278)),
  Line(vec3(0.00600502, 0.03326661, 0.09767457), vec3(0.20226364, 0.95862598, 0.20031386)),
  Line(vec3(0.33741080, 0.53217906, 0.67065203), vec3(-0.24556495, 0.70136767, -0.66916459)),
  Line(vec3(-0.39319275, -0.13638928, 0.06292972), vec3(0.97902781, 0.19977640, 0.03992416)),
  Line(vec3(0.42802034, 0.68694405, 0.72056450), vec3(-0.01283781, 0.96062176, -0.27756265)),
  Line(vec3(-0.20046574, 0.09088177, -0.59501567), vec3(0.22457840, 0.93189702, 0.28483767)),
  Line(vec3(-0.13764955, 0.05554669, -0.31130124), vec3(-0.85060782, 0.00490164, -0.52577781)),
  Line(vec3(-0.18078446, 0.28395575, -0.57500970), vec3(-0.26371516, -0.77725646, -0.57125013))
);

const Line CONIC_LINES[6] = Line[6](
  Line(vec3(-0.07890923, 0.06590316, -0.30442113), vec3(-0.91741122, -0.36222414, -0.16477358)),
  Line(vec3(-0.44872276, 0.32323743, -1.23523362), vec3(0.35145449, 0.03846388, 0.93541449)),
  Line(vec3(-0.06359645, 0.10069616, -0.15845121), vec3(0.31914473, -0.50531255, 0.80175175)),
  Line(vec3(1.11371138, 1.67069739, 0.43834953), vec3(0.84385655, 0.13401118, 0.51956436)),
  Line(vec3(-0.13564562, -0.21810823, -0.13852211), vec3(-0.28823097, -0.54857187, -0.78485146)),
  Line(vec3(-0.97513880, 1.74785504, -0.33862158), vec3(0.85900843, -0.11696916, 0.49842023))
);

const Line EXCEPTIONAL_LINES[6] = Line[6](
  Line(vec3(-1.15364329, 0.81375551, -3.00950319), vec3(-0.33150350, -0.22508644, -0.91621041)),
  Line(vec3(-1.96818553, -0.46152780, -1.11203910), vec3(0.84282719, 0.16426478, 0.51250308)),
  Line(vec3(0.36962638, 0.44016683, 0.75843956), vec3(-0.85439117, -0.37808914, -0.35646083)),
  Line(vec3(-0.65816001, -1.80833877, -1.17551924), vec3(-0.24712570, -0.87867139, -0.40849171)),
  Line(vec3(-0.15960947, 0.34636547, -0.52914120), vec3(-0.86223820, 0.14878181, -0.48415831)),
  Line(vec3(0.08428510, 1.42799319, -0.19430630), vec3(-0.16336010, -0.98276534, -0.08652028))
);


float cubicF(vec3 p){
    float x = p.x, y = p.y, z = p.z;
    float x2 = x*x, y2 = y*y, z2 = z*z;

    return C[0]*x2*x   + C[1]*x2*y   + C[2]*x2*z   + C[3]*x2
         + C[4]*x*y2   + C[5]*x*y*z  + C[6]*x*y    + C[7]*x*z2
         + C[8]*x*z    + C[9]*x
         + C[10]*y2*y  + C[11]*y2*z  + C[12]*y2    + C[13]*y*z2
         + C[14]*y*z   + C[15]*y
         + C[16]*z2*z  + C[17]*z2    + C[18]*z     + C[19];
}

vec3 cubicGrad(vec3 p){
    float x = p.x, y = p.y, z = p.z;
    float x2 = x*x, y2 = y*y, z2 = z*z;

    float dx = 3.0*C[0]*x2   + 2.0*C[1]*x*y   + 2.0*C[2]*x*z + 2.0*C[3]*x
             +     C[4]*y2   +     C[5]*y*z   +     C[6]*y   +     C[7]*z2
             +     C[8]*z    +     C[9];

    float dy =     C[1]*x2   + 2.0*C[4]*x*y   +     C[5]*x*z +     C[6]*x
             + 3.0*C[10]*y2  + 2.0*C[11]*y*z  + 2.0*C[12]*y  +     C[13]*z2
             +     C[14]*z   +     C[15];

    float dz =     C[2]*x2   +     C[5]*x*y   + 2.0*C[7]*x*z +     C[8]*x
             +     C[11]*y2  + 2.0*C[13]*y*z  +     C[14]*y
             + 3.0*C[16]*z2  + 2.0*C[17]*z    +     C[18];

    return vec3(dx, dy, dz);
}

//nearest of a line class, already tubed (lineDistance is primitives/line.glsl)
float cubicPairDist(vec3 p, float r){
    float d = 1.0e6;
    for(int i = 0; i < 15; i++){ d = min(d, lineDistance(p, PAIR_LINES[i].point, PAIR_LINES[i].dir, r)); }
    return d;
}
float cubicConicDist(vec3 p, float r){
    float d = 1.0e6;
    for(int i = 0; i < 6; i++){ d = min(d, lineDistance(p, CONIC_LINES[i].point, CONIC_LINES[i].dir, r)); }
    return d;
}
float cubicExceptionalDist(vec3 p, float r){
    float d = 1.0e6;
    for(int i = 0; i < 6; i++){ d = min(d, lineDistance(p, EXCEPTIONAL_LINES[i].point, EXCEPTIONAL_LINES[i].dir, r)); }
    return d;
}


//--- the objects, in declaration order (= containment priority, inner to outer)
const int ID_SURFACE     = 0;
const int ID_PAIRS       = 1;
const int ID_CONICS      = 2;
const int ID_EXCEPTIONAL = 3;
const int ID_RING        = 4;
const int ID_KEY         = 5;
const int ID_ROOM        = 6;

const int N_OBJ = 7;
float gSDF[N_OBJ];


//--- placement and shape parameters ----------------------------------
const vec3 CUBIC_P = vec3(0.0);
const float CUBIC_BALL   = 2.0;    //the sphere the whole figure is cut to
const float CUBIC_ZOOM   = 1.0;    //the surface's internal scale
const float CUBIC_BLEND  = 0.05;   //how softly the surface meets the cut

const vec3  KEY_P      = vec3(-12.0, 8.0, 2.0);
const float KEY_RADIUS = 1.5;

const vec3 ROOM_P        = vec3(-5.75, 5.75, -3.0);
const vec3 ROOM_HALFSIZE = vec3(14.25, 8.25, 17.0);


//---------------------------------------------------------------------
// the region sdfs
//---------------------------------------------------------------------

void sdf_cubic(vec3 p, out float surface, out float pairs, out float conics, out float exceptional, out float ring){
    vec3  q = p - CUBIC_P;
    float ball = length(q) - CUBIC_BALL;
    vec3  s    = CUBIC_ZOOM*q;
    float val  = cubicF(s);
    vec3  grad = cubicGrad(s)*CUBIC_ZOOM;

    //the surface: a first-order distance estimate to {cubic = 0},
    //thickened into a shell, then cut to the ball
    float de = val/(length(grad) + 0.001);
    surface  = smax(abs(de + shellDepth) - shellDepth, ball, CUBIC_BLEND);

    //the 27 lines, by class, each cut to the same ball
    pairs       = max(cubicPairDist(q, lineRadius), ball);
    conics      = max(cubicConicDist(q, lineRadius), ball);
    exceptional = max(cubicExceptionalDist(q, lineRadius), ball);

    //the ring where the surface leaves the ball: a tube around the
    //curve {cubic = 0} ∩ {ball = 0}. The sphere's gradient is just
    //its radial direction (ops/curve.glsl).
    ring = opCurveTube(val, grad, ball, normalize(q), ringRadius);
}

//single-region entry points, for the 4-tap normals
float sdf_surface(vec3 p){ float surface, pairs, conics, exceptional, ring; sdf_cubic(p, surface, pairs, conics, exceptional, ring); return surface; }
float sdf_pairs(vec3 p){ float surface, pairs, conics, exceptional, ring; sdf_cubic(p, surface, pairs, conics, exceptional, ring); return pairs; }
float sdf_conics(vec3 p){ float surface, pairs, conics, exceptional, ring; sdf_cubic(p, surface, pairs, conics, exceptional, ring); return conics; }
float sdf_exceptional(vec3 p){ float surface, pairs, conics, exceptional, ring; sdf_cubic(p, surface, pairs, conics, exceptional, ring); return exceptional; }
float sdf_ring(vec3 p){ float surface, pairs, conics, exceptional, ring; sdf_cubic(p, surface, pairs, conics, exceptional, ring); return ring; }

float sdf_key(vec3 p){
    return sphereDistance(p - KEY_P, KEY_RADIUS);
}

//the room SOLID is everything outside the box, so its interior is open air and
//regionAt() returns ID_NONE there
float sdf_room(vec3 p){
    return roomDistance(p - ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the bounds — the acceleration structure (sdf_Scene only; sdfAll stays exact)
//---------------------------------------------------------------------

float bound_cubic(vec3 p){
    vec3 q = p - CUBIC_P;
    return length(q) - 2.5;
}


//---------------------------------------------------------------------
// the normals — the 4-tap of each region's own sdf, in world coordinates
//---------------------------------------------------------------------
const float NRM_E = 0.0002;

Vector normal_surface(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_surface(p + k.xyy*NRM_E) + k.yyx*sdf_surface(p + k.yyx*NRM_E)
                              + k.yxy*sdf_surface(p + k.yxy*NRM_E) + k.xxx*sdf_surface(p + k.xxx*NRM_E) ));
}

Vector normal_pairs(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_pairs(p + k.xyy*NRM_E) + k.yyx*sdf_pairs(p + k.yyx*NRM_E)
                              + k.yxy*sdf_pairs(p + k.yxy*NRM_E) + k.xxx*sdf_pairs(p + k.xxx*NRM_E) ));
}

Vector normal_conics(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_conics(p + k.xyy*NRM_E) + k.yyx*sdf_conics(p + k.yyx*NRM_E)
                              + k.yxy*sdf_conics(p + k.yxy*NRM_E) + k.xxx*sdf_conics(p + k.xxx*NRM_E) ));
}

Vector normal_exceptional(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_exceptional(p + k.xyy*NRM_E) + k.yyx*sdf_exceptional(p + k.yyx*NRM_E)
                              + k.yxy*sdf_exceptional(p + k.yxy*NRM_E) + k.xxx*sdf_exceptional(p + k.xxx*NRM_E) ));
}

Vector normal_ring(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_ring(p + k.xyy*NRM_E) + k.yyx*sdf_ring(p + k.yyx*NRM_E)
                              + k.yxy*sdf_ring(p + k.yxy*NRM_E) + k.xxx*sdf_ring(p + k.xxx*NRM_E) ));
}

Vector normal_key(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_key(p + k.xyy*NRM_E) + k.yyx*sdf_key(p + k.yyx*NRM_E)
                              + k.yxy*sdf_key(p + k.yxy*NRM_E) + k.xxx*sdf_key(p + k.xxx*NRM_E) ));
}

Vector normal_room(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_room(p + k.xyy*NRM_E) + k.yyx*sdf_room(p + k.yyx*NRM_E)
                              + k.yxy*sdf_room(p + k.yxy*NRM_E) + k.xxx*sdf_room(p + k.xxx*NRM_E) ));
}


//---------------------------------------------------------------------
// the materials
//  material_ gives the Surface plus this object's own Medium; medium_ gives
//  only the Medium, for when the object is merely the far side
//---------------------------------------------------------------------

Medium medium_surface(vec3 p){
    Medium m = defaultMedium();
    m.ior    = 1.5;
    m.absorb = vec3(0.5, 0.3, 0.1);
    return m;
}
Material material_surface(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //glass
    m.interior = medium_surface(p);
    m.surf.transmit = 1.0;
    return m;
}

Material material_pairs(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //metal
    m.surf.diffuse   = vec3(0.55);
    m.surf.specular  = vec3(0.55);
    m.surf.roughness = 0.1;
    m.surf.gloss     = 0.8;
    return m;
}
Medium   medium_pairs  (vec3 p){ return defaultMedium(); }

Material material_conics(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //metal
    m.surf.diffuse   = vec3(0.2, 0.45, 0.9);
    m.surf.specular  = vec3(0.2, 0.45, 0.9);
    m.surf.roughness = 0.1;
    m.surf.gloss     = 0.8;
    return m;
}
Medium   medium_conics  (vec3 p){ return defaultMedium(); }

Material material_exceptional(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //metal
    m.surf.diffuse   = vec3(0.9, 0.25, 0.2);
    m.surf.specular  = vec3(0.9, 0.25, 0.2);
    m.surf.roughness = 0.1;
    m.surf.gloss     = 0.8;
    return m;
}
Medium   medium_exceptional  (vec3 p){ return defaultMedium(); }

Material material_ring(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //metal
    m.surf.diffuse   = vec3(0.1);
    m.surf.specular  = vec3(0.1);
    m.surf.roughness = 0.2;
    m.surf.gloss     = 0.6;
    return m;
}
Medium   medium_ring  (vec3 p){ return defaultMedium(); }

Material material_key(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //light
    m.surf.emit = 60.0*vec3(1.0);
    return m;
}
Medium   medium_key  (vec3 p){ return defaultMedium(); }

Material material_room(vec3 p, inout Vector n){
    vec3 q = p - ROOM_P;
    int faceData = roomFaceData(q, ROOM_HALFSIZE);
    if(faceData == ROOM_CEILING){ return makeLight(vec3(1.0), roomLight); }
    if(faceData == ROOM_FLOOR)  { return makeGloss(floorColor, 0.0, wallRough); }
    if(faceData == ROOM_LEFT)   { return makeGloss(warmColor,  0.0, wallRough); }
    if(faceData == ROOM_RIGHT)  { return makeGloss(coolColor,  0.0, wallRough); }
    return makeGloss(wallColor, 0.0, wallRough);
}
Medium medium_room(vec3 p){ return defaultMedium(); }


//---------------------------------------------------------------------
// the analytic intersections
//---------------------------------------------------------------------

float trace_key(Vector tv){
    return sphereTrace(tv, KEY_P, KEY_RADIUS);
}

float trace_room(Vector tv){
    return roomTrace(tv, ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the dispatchers
//---------------------------------------------------------------------

void sdfAll(vec3 p){
    sdf_cubic(p, gSDF[ID_SURFACE], gSDF[ID_PAIRS], gSDF[ID_CONICS], gSDF[ID_EXCEPTIONAL], gSDF[ID_RING]);
    gSDF[ID_KEY        ] = sdf_key(p);
    gSDF[ID_ROOM       ] = sdf_room(p);
}

Vector normalOf(int id, vec3 p){
    if(id == ID_SURFACE    ){ return normal_surface(p); }
    if(id == ID_PAIRS      ){ return normal_pairs(p); }
    if(id == ID_CONICS     ){ return normal_conics(p); }
    if(id == ID_EXCEPTIONAL){ return normal_exceptional(p); }
    if(id == ID_RING       ){ return normal_ring(p); }
    if(id == ID_KEY        ){ return normal_key(p); }
    return normal_room(p);
}

//no sheets in this scene: every object is a region with an interior
bool isSheet(int id){ return false; }

Material materialOf(int id, vec3 p, inout Vector n, bool front){
    if(id == ID_SURFACE    ){ return material_surface(p, n); }
    if(id == ID_PAIRS      ){ return material_pairs(p, n); }
    if(id == ID_CONICS     ){ return material_conics(p, n); }
    if(id == ID_EXCEPTIONAL){ return material_exceptional(p, n); }
    if(id == ID_RING       ){ return material_ring(p, n); }
    if(id == ID_KEY        ){ return material_key(p, n); }
    return material_room(p, n);
}

Medium mediumOf(int id, vec3 p){
    if(id == ID_SURFACE    ){ return medium_surface(p); }
    if(id == ID_PAIRS      ){ return medium_pairs(p); }
    if(id == ID_CONICS     ){ return medium_conics(p); }
    if(id == ID_EXCEPTIONAL){ return medium_exceptional(p); }
    if(id == ID_RING       ){ return medium_ring(p); }
    if(id == ID_KEY        ){ return medium_key(p); }
    if(id == ID_ROOM       ){ return medium_room(p); }
    return defaultMedium();      //ID_NONE: open air
}


//---------------------------------------------------------------------
// the entry points
//---------------------------------------------------------------------

void buildScene(){}

float sdf_Scene(Vector tv){
    vec3 p = tv.pos;
    float d = maxDist;

    float b_cubic = bound_cubic(p);
    if(b_cubic > BOUND_MARGIN){ d = min(d, b_cubic); }
    else{
        float surface, pairs, conics, exceptional, ring;
        sdf_cubic(p, surface, pairs, conics, exceptional, ring);
        d = min(d, min(min(min(min(surface, pairs), conics), exceptional), ring));
    }

    return d;
}

float trace_Scene(Vector tv){
    float d = maxDist;
    d = min(d, trace_key(tv));
    d = min(d, trace_room(tv));
    return d;
}
