//=====================================================================
// generated by scenegen from src/scene.js — do not edit by hand
//=====================================================================


//--- library: glsl/shapes/primitives/line.glsl ---
//----------------------------------------------------------------------------
// LINE — an infinite straight line thickened to `radius`: a cylinder of
// unbounded length about an arbitrary axis.
//
// `point` is any point on the axis and `dir` its direction, which MUST be unit
// length (the caller's job — normalizing here would cost a sqrt on every line of
// every march step, and the data that drives this is normalized once upstream).
//
// UNBOUNDED, so it has no <stem>Bound and never will: clip it, or use it inside
// something that is already clipped. The cubic-surface scene min's 27 of these
// and intersects the result with its bounding sphere.
//
// glsl/shapes/primitives/ holds the exact closed forms; this one is CONTENT
// rather than vocabulary (it is not in _vocabulary.glsl), so it is inlined only
// into scenes that name it — via lib.line, or via uses: [lib.line] from an
// authored body that calls it with its own per-line data.
//----------------------------------------------------------------------------


// p is in the line's own coordinates. dir must be unit length.
float lineDistance(vec3 p, vec3 point, vec3 dir, float radius){
    vec3 d = p - point;
    return length(d - dot(d, dir)*dir) - radius;
}


//--- library: glsl/shapes/environments/room.glsl ---
//----------------------------------------------------------------------------
// ROOM — a closed box, seen from the inside.
//
// The room is ONE region whose solid is everything OUTSIDE the box, so the
// interior is open air and regionAt() returns ID_NONE there. Its six walls are
// not six objects: they are a material FIELD over that one region, read off by
// asking which face a point is nearest. roomFace() answers that.
//
// glsl/shapes/ is the math-only library: plain functions of a point and some
// floats. No structs, no Frame, no Material.
//----------------------------------------------------------------------------


const int ROOM_FLOOR   = 0;
const int ROOM_CEILING = 1;
const int ROOM_LEFT    = 2;
const int ROOM_RIGHT   = 3;
const int ROOM_FRONT   = 4;
const int ROOM_BACK    = 5;


// p is in the room's own coordinates (origin at the box centre).
// Negative in the WALLS, positive in the open interior — the sign convention
// every other region uses, just turned inside out.
float roomDistance(vec3 p, vec3 halfSize){
    return -boxDistance(p, halfSize);
}


// Exact ray intersection, in world coordinates. The ray is inside the box, so
// this is simply the distance at which it leaves: the nearest of the three
// far slab crossings.
float roomTrace(Vector tv, vec3 centre, vec3 halfSize){
    vec3  o  = tv.pos - centre;
    vec3  tm = max((-halfSize - o)/tv.dir, (halfSize - o)/tv.dir);
    float t  = min(tm.x, min(tm.y, tm.z));
    if(t < 0.){ return maxDist; }
    return min(t, maxDist);
}


// Which wall p is on (or nearest to) — a shape DATA output (docs/shape-data.md):
// a material that reads `faceData` gets it injected. d is negative inside the
// room, so its LARGEST component names the axis the point is closest to leaving
// through, and the sign of p picks which of that axis's two faces.
int roomFaceData(vec3 p, vec3 halfSize){
    vec3 d = abs(p) - halfSize;

    if(d.y >= d.x && d.y >= d.z){
        return (p.y > 0.) ? ROOM_CEILING : ROOM_FLOOR;
    }
    if(d.x >= d.z){
        return (p.x > 0.) ? ROOM_RIGHT : ROOM_LEFT;
    }
    return (p.z > 0.) ? ROOM_BACK : ROOM_FRONT;
}


struct Line     { vec3 point; vec3 dir; };
struct Line2D   { vec2 point; vec2 dir; };
struct Conic2D  { float c0, c1, c2, c3, c4, c5; };


// Auto-generated cubic surface data (3D scene).
// Assumes: struct Line { vec3 point; vec3 dir; };

const float C[20] = float[20](
  0.00000000,
  -0.00000000,
  -22.59033526,
  9.55038426,
  22.59033526,
  -6.64154207,
  -36.20846137,
  45.06034515,
  -9.77803069,
  -1.54492667,
  -2.90884219,
  -8.85188378,
  5.05671272,
  4.72131797,
  15.37675180,
  -1.00000000,
  -13.83182514,
  1.00000000,
  0.00000000,
  0.00000000
);

const Line PAIR_LINES[15] = Line[15](
  Line(vec3(-0.22200667, 0.16547733, -0.66459422), vec3(0.35761336, -0.24884481, 0.90010496)),
  Line(vec3(-0.06368645, 0.10061345, -0.15870238), vec3(0.32222609, 0.29608952, 0.89916703)),
  Line(vec3(0.16834240, 1.66149503, 0.43826031), vec3(0.99995262, 0.00973379, 0.00009438)),
  Line(vec3(-0.39048088, 0.71440074, -0.87968795), vec3(0.20920202, -0.76552498, 0.60844558)),
  Line(vec3(-0.05686488, 1.47060935, -0.21353384), vec3(0.94928104, -0.28660778, 0.12931159)),
  Line(vec3(-3.16904340, -1.00867855, -1.50698045), vec3(-0.87178774, -0.39721548, -0.28671589)),
  Line(vec3(0.00024691, 0.00302516, 0.06782025), vec3(0.03910042, 0.98247944, -0.18222323)),
  Line(vec3(1.62877836, 0.09420336, 0.89529842), vec3(0.97039620, -0.23126281, 0.06963278)),
  Line(vec3(0.00600502, 0.03326661, 0.09767457), vec3(0.20226364, 0.95862598, 0.20031386)),
  Line(vec3(0.33741080, 0.53217906, 0.67065203), vec3(-0.24556495, 0.70136767, -0.66916459)),
  Line(vec3(-0.39319275, -0.13638928, 0.06292972), vec3(0.97902781, 0.19977640, 0.03992416)),
  Line(vec3(0.42802034, 0.68694405, 0.72056450), vec3(-0.01283781, 0.96062176, -0.27756265)),
  Line(vec3(-0.20046574, 0.09088177, -0.59501567), vec3(0.22457840, 0.93189702, 0.28483767)),
  Line(vec3(-0.13764955, 0.05554669, -0.31130124), vec3(-0.85060782, 0.00490164, -0.52577781)),
  Line(vec3(-0.18078446, 0.28395575, -0.57500970), vec3(-0.26371516, -0.77725646, -0.57125013))
);

const Line CONIC_LINES[6] = Line[6](
  Line(vec3(-0.07890923, 0.06590316, -0.30442113), vec3(-0.91741122, -0.36222414, -0.16477358)),
  Line(vec3(-0.44872276, 0.32323743, -1.23523362), vec3(0.35145449, 0.03846388, 0.93541449)),
  Line(vec3(-0.06359645, 0.10069616, -0.15845121), vec3(0.31914473, -0.50531255, 0.80175175)),
  Line(vec3(1.11371138, 1.67069739, 0.43834953), vec3(0.84385655, 0.13401118, 0.51956436)),
  Line(vec3(-0.13564562, -0.21810823, -0.13852211), vec3(-0.28823097, -0.54857187, -0.78485146)),
  Line(vec3(-0.97513880, 1.74785504, -0.33862158), vec3(0.85900843, -0.11696916, 0.49842023))
);

const Line EXCEPTIONAL_LINES[6] = Line[6](
  Line(vec3(-1.15364329, 0.81375551, -3.00950319), vec3(-0.33150350, -0.22508644, -0.91621041)),
  Line(vec3(-1.96818553, -0.46152780, -1.11203910), vec3(0.84282719, 0.16426478, 0.51250308)),
  Line(vec3(0.36962638, 0.44016683, 0.75843956), vec3(-0.85439117, -0.37808914, -0.35646083)),
  Line(vec3(-0.65816001, -1.80833877, -1.17551924), vec3(-0.24712570, -0.87867139, -0.40849171)),
  Line(vec3(-0.15960947, 0.34636547, -0.52914120), vec3(-0.86223820, 0.14878181, -0.48415831)),
  Line(vec3(0.08428510, 1.42799319, -0.19430630), vec3(-0.16336010, -0.98276534, -0.08652028))
);


// Auto-generated blowup diagram data (2D scene).
// Assumes: struct Line2D { vec2 point; vec2 dir; };
// Assumes: struct Conic2D { float a, b, c, d, e, f; };
//   represents a*x^2 + b*xy + c*x + d*y^2 + e*y + f = 0

const vec2 POINTS[6] = vec2[6](
  vec2(-0.69999999, -0.50000000),
  vec2(0.35566583, 0.08955224),
  vec2(0.20000000, 0.89999998),
  vec2(-0.69644332, 0.02442334),
  vec2(0.28287840, -0.76255089),
  vec2(-0.89999998, 0.10000000)
);

const Line2D PLANE_LINES[15] = Line2D[15](
  Line2D(vec2(-0.69999999, -0.50000000), vec2(0.87307681, 0.48758270)),
  Line2D(vec2(-0.69999999, -0.50000000), vec2(0.54075759, 0.84117847)),
  Line2D(vec2(-0.69999999, -0.50000000), vec2(0.00678190, 0.99997700)),
  Line2D(vec2(-0.69999999, -0.50000000), vec2(0.96612473, -0.25807558)),
  Line2D(vec2(-0.69999999, -0.50000000), vec2(-0.31622775, 0.94868330)),
  Line2D(vec2(0.35566583, 0.08955224), vec2(-0.18862595, 0.98204901)),
  Line2D(vec2(0.35566583, 0.08955224), vec2(-0.99808949, -0.06178491)),
  Line2D(vec2(0.35566583, 0.08955224), vec2(-0.08511097, -0.99637148)),
  Line2D(vec2(0.35566583, 0.08955224), vec2(-0.99996539, 0.00832021)),
  Line2D(vec2(0.20000000, 0.89999998), vec2(-0.71538382, -0.69873170)),
  Line2D(vec2(0.20000000, 0.89999998), vec2(0.04978832, -0.99875979)),
  Line2D(vec2(0.20000000, 0.89999998), vec2(-0.80873609, -0.58817169)),
  Line2D(vec2(-0.69644332, 0.02442334), vec2(0.77950144, -0.62640043)),
  Line2D(vec2(-0.69644332, 0.02442334), vec2(-0.93747050, 0.34806473)),
  Line2D(vec2(0.28287840, -0.76255089), vec2(-0.80799602, 0.58918795))
);

const Conic2D PLANE_CONICS[6] = Conic2D[6](
  Conic2D(-4.05495405, -12.39428616, -0.98176360, -1.36032701, 2.99043012, 1.00000000),
  Conic2D(2.42081380, 1.97098136, 3.07525420, -2.67358398, 0.10993669, 1.00000000),
  Conic2D(246.22955322, -267.97973633, 151.82333374, -1203.99597168, -758.83148193, 1.00000000),
  Conic2D(-3.16287756, -0.98534220, -1.62567866, -0.64199936, 0.16559105, 1.00000000),
  Conic2D(-1.79446745, -13.80975819, 0.32837322, 8.24482441, -5.76271915, 1.00000000),
  Conic2D(-4.00074482, 0.24726184, -1.36191034, -0.59938115, -0.14066280, 1.00000000)
);


float cubicF(vec3 p){
    float x = p.x, y = p.y, z = p.z;
    float x2 = x*x, y2 = y*y, z2 = z*z;

    return C[0]*x2*x   + C[1]*x2*y   + C[2]*x2*z   + C[3]*x2
         + C[4]*x*y2   + C[5]*x*y*z  + C[6]*x*y    + C[7]*x*z2
         + C[8]*x*z    + C[9]*x
         + C[10]*y2*y  + C[11]*y2*z  + C[12]*y2    + C[13]*y*z2
         + C[14]*y*z   + C[15]*y
         + C[16]*z2*z  + C[17]*z2    + C[18]*z     + C[19];
}

vec3 cubicGrad(vec3 p){
    float x = p.x, y = p.y, z = p.z;
    float x2 = x*x, y2 = y*y, z2 = z*z;

    float dx = 3.0*C[0]*x2   + 2.0*C[1]*x*y   + 2.0*C[2]*x*z + 2.0*C[3]*x
             +     C[4]*y2   +     C[5]*y*z   +     C[6]*y   +     C[7]*z2
             +     C[8]*z    +     C[9];

    float dy =     C[1]*x2   + 2.0*C[4]*x*y   +     C[5]*x*z +     C[6]*x
             + 3.0*C[10]*y2  + 2.0*C[11]*y*z  + 2.0*C[12]*y  +     C[13]*z2
             +     C[14]*z   +     C[15];

    float dz =     C[2]*x2   +     C[5]*x*y   + 2.0*C[7]*x*z +     C[8]*x
             +     C[11]*y2  + 2.0*C[13]*y*z  +     C[14]*y
             + 3.0*C[16]*z2  + 2.0*C[17]*z    +     C[18];

    return vec3(dx, dy, dz);
}

//the surface group's own spin, about the y axis. Written out rather than
//using rot2() so the direction matches the original exactly.
vec3 cubicSpin(vec3 p, float turns){
    float a = turns*6.2832;
    float ca = cos(a), sa = sin(a);
    vec2  r  = mat2(ca, sa, -sa, ca)*p.xz;
    return vec3(r.x, p.y, r.y);
}

float cubicPairDist(vec3 p, float r){
    float d = 1.0e6;
    for(int i = 0; i < 15; i++){ d = min(d, lineDistance(p, PAIR_LINES[i].point, PAIR_LINES[i].dir, r)); }
    return d;
}
float cubicConicDist(vec3 p, float r){
    float d = 1.0e6;
    for(int i = 0; i < 6; i++){ d = min(d, lineDistance(p, CONIC_LINES[i].point, CONIC_LINES[i].dir, r)); }
    return d;
}
float cubicExceptionalDist(vec3 p, float r){
    float d = 1.0e6;
    for(int i = 0; i < 6; i++){ d = min(d, lineDistance(p, EXCEPTIONAL_LINES[i].point, EXCEPTIONAL_LINES[i].dir, r)); }
    return d;
}


float plateConicVal(vec2 xz, Conic2D c){
    float x = xz.x, z = xz.y;
    return c.c0*x*x + c.c1*x*z + c.c2*x + c.c3*z*z + c.c4*z + c.c5;
}
//no y dependence, so the y component of the gradient is 0 — which makes
//opCurveTube's projection a no-op and reduces it to the original's
//sqrt(dConic^2 + y^2)
vec3 plateConicGrad(vec2 xz, Conic2D c){
    float x = xz.x, z = xz.y;
    return vec3(2.0*c.c0*x + c.c1*z + c.c2, 0.0, c.c1*x + 2.0*c.c3*z + c.c4);
}

float plateRegion(vec3 p, float halfWidth){
    vec2 d = abs(p.xz) - vec2(halfWidth);
    return max(d.x, d.y);
}

//the plate's 15 lines lie flat in y = 0, so an ordinary 3D line does the job
float plateLineDist(vec3 p, float r){
    float d = 1.0e6;
    for(int i = 0; i < 15; i++){
        Line2D l = PLANE_LINES[i];
        d = min(d, lineDistance(p, vec3(l.point.x, 0.0, l.point.y),
                                   vec3(l.dir.x,   0.0, l.dir.y), r));
    }
    return d;
}

//each conic as a tube around {Q = 0} intersect {y = 0}
float plateConicDist(vec3 p, float r){
    float d = 1.0e6;
    for(int i = 0; i < 6; i++){
        Conic2D c = PLANE_CONICS[i];
        d = min(d, opCurveTube(plateConicVal(p.xz, c), plateConicGrad(p.xz, c),
                               p.y, vec3(0.0, 1.0, 0.0), r));
    }
    return d;
}

//cylinderDistance adds its fillet to the HEIGHT (primitives/cylinder.glsl),
//so the height argument is the true half-height minus the rounding
float plateCheckerDist(vec3 p, float r, float halfH, float rnd, float yOff){
    float d = 1.0e6;
    for(int i = 0; i < 6; i++){
        vec3 c = p - vec3(POINTS[i].x, yOff, POINTS[i].y);
        d = min(d, cylinderDistance(c, r, halfH - rnd, rnd));
    }
    return d;
}


//--- the objects, in declaration order (= containment priority, inner to outer)
const int ID_SURFACE          = 0;
const int ID_PAIRLINES        = 1;
const int ID_CONICLINES       = 2;
const int ID_EXCEPTIONALLINES = 3;
const int ID_RING             = 4;
const int ID_PLATE            = 5;
const int ID_CHECKERS         = 6;
const int ID_PLATELINES       = 7;
const int ID_PLATECONICS      = 8;
const int ID_KEY              = 9;
const int ID_ROOM             = 10;

const int N_OBJ = 11;
float gSDF[N_OBJ];


//--- placement and shape parameters ----------------------------------
const vec3 SURFACEGROUP_P = vec3(3.5, 0.0, 0.0);
const float CUBIC_BALL  = 2.0;
const float CUBIC_ZOOM  = 1.0;
const float CUBIC_SHELL = 0.01;   //inward shell depth
const float CUBIC_BLEND = 0.05;
const float CUBIC_LINE  = 0.02;
const float CUBIC_RING  = 0.05;

const vec3 PLATEGROUP_P = vec3(-1.0, -2.4, 0.0);
const float PLATE_HALF  = 1.2;
const float PLATE_THICK = 0.05;
const float PLATE_ROUND = 0.02;
const float PLATE_TOP   = 0.05;
const float PLATE_CURVE = 0.02;
const float CHECK_R     = 0.06;
const float CHECK_HALF  = 0.02;
const float CHECK_ROUND = 0.008;
const float CHECK_Y     = 0.07;

const vec3  KEY_P      = vec3(-12.0, 8.0, 2.0);
const float KEY_RADIUS = 1.5;

const vec3 ROOM_P        = vec3(0.0, 5.75, -5.0);
const vec3 ROOM_HALFSIZE = vec3(20.0, 8.25, 15.0);


//---------------------------------------------------------------------
// the region sdfs
//---------------------------------------------------------------------

void sdf_surfaceGroup(vec3 p, out float surface, out float pairLines, out float conicLines, out float exceptionalLines, out float ring){
    vec3  q = p - SURFACEGROUP_P;
    //the group's spin. No normal fixup follows: normals are a 4-tap
    //of the world sdf, so the chain rule carries this for free.
    vec3 t = cubicSpin(q, rotation);

    float ball = length(t) - CUBIC_BALL;
    vec3  s    = CUBIC_ZOOM*t;
    float val  = cubicF(s);
    vec3  grad = cubicGrad(s)*CUBIC_ZOOM;

    float de = val/(length(grad) + 0.001);
    surface  = smax(abs(de + CUBIC_SHELL) - CUBIC_SHELL, ball, CUBIC_BLEND);

    pairLines       = max(cubicPairDist(t, CUBIC_LINE), ball);
    conicLines      = max(cubicConicDist(t, CUBIC_LINE), ball);
    exceptionalLines = max(cubicExceptionalDist(t, CUBIC_LINE), ball);

    ring = opCurveTube(val, grad, ball, normalize(t), CUBIC_RING);
}

//single-region entry points, for the 4-tap normals
float sdf_surface(vec3 p){ float surface, pairLines, conicLines, exceptionalLines, ring; sdf_surfaceGroup(p, surface, pairLines, conicLines, exceptionalLines, ring); return surface; }
float sdf_pairLines(vec3 p){ float surface, pairLines, conicLines, exceptionalLines, ring; sdf_surfaceGroup(p, surface, pairLines, conicLines, exceptionalLines, ring); return pairLines; }
float sdf_conicLines(vec3 p){ float surface, pairLines, conicLines, exceptionalLines, ring; sdf_surfaceGroup(p, surface, pairLines, conicLines, exceptionalLines, ring); return conicLines; }
float sdf_exceptionalLines(vec3 p){ float surface, pairLines, conicLines, exceptionalLines, ring; sdf_surfaceGroup(p, surface, pairLines, conicLines, exceptionalLines, ring); return exceptionalLines; }
float sdf_ring(vec3 p){ float surface, pairLines, conicLines, exceptionalLines, ring; sdf_surfaceGroup(p, surface, pairLines, conicLines, exceptionalLines, ring); return ring; }

void sdf_plateGroup(vec3 p, out float plate, out float checkers, out float plateLines, out float plateConics){
    vec3  q = p - PLATEGROUP_P;
    float region = plateRegion(q, PLATE_HALF);

    //the old Box subtracted its rounding from the distance, so the
    //fillet INFLATES the extents
    plate = boxDistance(q, vec3(PLATE_HALF, PLATE_THICK, PLATE_HALF)) - PLATE_ROUND;

    checkers = plateCheckerDist(q, CHECK_R, CHECK_HALF, CHECK_ROUND, CHECK_Y);

    vec3 top = q - vec3(0.0, PLATE_TOP, 0.0);
    plateLines  = max(plateLineDist(top,  PLATE_CURVE), region);
    plateConics = max(plateConicDist(top, PLATE_CURVE), region);
}

//single-region entry points, for the 4-tap normals
float sdf_plate(vec3 p){ float plate, checkers, plateLines, plateConics; sdf_plateGroup(p, plate, checkers, plateLines, plateConics); return plate; }
float sdf_checkers(vec3 p){ float plate, checkers, plateLines, plateConics; sdf_plateGroup(p, plate, checkers, plateLines, plateConics); return checkers; }
float sdf_plateLines(vec3 p){ float plate, checkers, plateLines, plateConics; sdf_plateGroup(p, plate, checkers, plateLines, plateConics); return plateLines; }
float sdf_plateConics(vec3 p){ float plate, checkers, plateLines, plateConics; sdf_plateGroup(p, plate, checkers, plateLines, plateConics); return plateConics; }

float sdf_key(vec3 p){
    return sphereDistance(p - KEY_P, KEY_RADIUS);
}

//the room SOLID is everything outside the box, so its interior is open air and
//regionAt() returns ID_NONE there
float sdf_room(vec3 p){
    return roomDistance(p - ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the bounds — the acceleration structure (sdf_Scene only; sdfAll stays exact)
//---------------------------------------------------------------------

float bound_surfaceGroup(vec3 p){
    vec3 q = p - SURFACEGROUP_P;
    return length(q) - 2.6;
}

float bound_plateGroup(vec3 p){
    vec3 q = p - PLATEGROUP_P;
    return boxDistance(q, vec3(1.2, 0.15, 1.2));
}


//---------------------------------------------------------------------
// the normals — the 4-tap of each region's own sdf, in world coordinates
//---------------------------------------------------------------------
const float NRM_E = 0.0002;

Vector normal_surface(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_surface(p + k.xyy*NRM_E) + k.yyx*sdf_surface(p + k.yyx*NRM_E)
                              + k.yxy*sdf_surface(p + k.yxy*NRM_E) + k.xxx*sdf_surface(p + k.xxx*NRM_E) ));
}

Vector normal_pairLines(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_pairLines(p + k.xyy*NRM_E) + k.yyx*sdf_pairLines(p + k.yyx*NRM_E)
                              + k.yxy*sdf_pairLines(p + k.yxy*NRM_E) + k.xxx*sdf_pairLines(p + k.xxx*NRM_E) ));
}

Vector normal_conicLines(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_conicLines(p + k.xyy*NRM_E) + k.yyx*sdf_conicLines(p + k.yyx*NRM_E)
                              + k.yxy*sdf_conicLines(p + k.yxy*NRM_E) + k.xxx*sdf_conicLines(p + k.xxx*NRM_E) ));
}

Vector normal_exceptionalLines(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_exceptionalLines(p + k.xyy*NRM_E) + k.yyx*sdf_exceptionalLines(p + k.yyx*NRM_E)
                              + k.yxy*sdf_exceptionalLines(p + k.yxy*NRM_E) + k.xxx*sdf_exceptionalLines(p + k.xxx*NRM_E) ));
}

Vector normal_ring(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_ring(p + k.xyy*NRM_E) + k.yyx*sdf_ring(p + k.yyx*NRM_E)
                              + k.yxy*sdf_ring(p + k.yxy*NRM_E) + k.xxx*sdf_ring(p + k.xxx*NRM_E) ));
}

Vector normal_plate(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_plate(p + k.xyy*NRM_E) + k.yyx*sdf_plate(p + k.yyx*NRM_E)
                              + k.yxy*sdf_plate(p + k.yxy*NRM_E) + k.xxx*sdf_plate(p + k.xxx*NRM_E) ));
}

Vector normal_checkers(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_checkers(p + k.xyy*NRM_E) + k.yyx*sdf_checkers(p + k.yyx*NRM_E)
                              + k.yxy*sdf_checkers(p + k.yxy*NRM_E) + k.xxx*sdf_checkers(p + k.xxx*NRM_E) ));
}

Vector normal_plateLines(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_plateLines(p + k.xyy*NRM_E) + k.yyx*sdf_plateLines(p + k.yyx*NRM_E)
                              + k.yxy*sdf_plateLines(p + k.yxy*NRM_E) + k.xxx*sdf_plateLines(p + k.xxx*NRM_E) ));
}

Vector normal_plateConics(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_plateConics(p + k.xyy*NRM_E) + k.yyx*sdf_plateConics(p + k.yyx*NRM_E)
                              + k.yxy*sdf_plateConics(p + k.yxy*NRM_E) + k.xxx*sdf_plateConics(p + k.xxx*NRM_E) ));
}

Vector normal_key(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_key(p + k.xyy*NRM_E) + k.yyx*sdf_key(p + k.yyx*NRM_E)
                              + k.yxy*sdf_key(p + k.yxy*NRM_E) + k.xxx*sdf_key(p + k.xxx*NRM_E) ));
}

Vector normal_room(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_room(p + k.xyy*NRM_E) + k.yyx*sdf_room(p + k.yyx*NRM_E)
                              + k.yxy*sdf_room(p + k.yxy*NRM_E) + k.xxx*sdf_room(p + k.xxx*NRM_E) ));
}


//---------------------------------------------------------------------
// the materials
//  material_ gives the Surface plus this object's own Medium; medium_ gives
//  only the Medium, for when the object is merely the far side
//---------------------------------------------------------------------

Medium medium_surface(vec3 p){
    Medium m = defaultMedium();
    m.ior    = 1.5;
    m.absorb = vec3(0.6, 0.1, 0.4);
    return m;
}
Material material_surface(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //glass
    m.interior = medium_surface(p);
    m.surf.transmit = 1.0;
    return m;
}

Material material_pairLines(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //metal
    m.surf.diffuse   = vec3(0.4);
    m.surf.specular  = vec3(0.4);
    m.surf.roughness = 0.4;
    m.surf.gloss     = 0.3;
    return m;
}
Medium   medium_pairLines  (vec3 p){ return defaultMedium(); }

Material material_conicLines(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //metal
    m.surf.diffuse   = vec3(0.1, 0.2, 0.7);
    m.surf.specular  = vec3(0.1, 0.2, 0.7);
    m.surf.roughness = 0.4;
    m.surf.gloss     = 0.3;
    return m;
}
Medium   medium_conicLines  (vec3 p){ return defaultMedium(); }

Material material_exceptionalLines(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //metal
    m.surf.diffuse   = vec3(0.7, 0.1, 0.1);
    m.surf.specular  = vec3(0.7, 0.1, 0.1);
    m.surf.roughness = 0.4;
    m.surf.gloss     = 0.3;
    return m;
}
Medium   medium_exceptionalLines  (vec3 p){ return defaultMedium(); }

Material material_ring(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //metal
    m.surf.diffuse   = vec3(0.1);
    m.surf.specular  = vec3(0.1);
    m.surf.roughness = 0.4;
    m.surf.gloss     = 0.3;
    return m;
}
Medium   medium_ring  (vec3 p){ return defaultMedium(); }

Medium medium_plate(vec3 p){
    Medium m = defaultMedium();
    m.ior    = 1.5;
    m.absorb = vec3(0.3, 0.05, 0.2);
    return m;
}
Material material_plate(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //glass
    m.interior = medium_plate(p);
    m.surf.transmit = 1.0;
    return m;
}

Material material_checkers(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //metal
    m.surf.diffuse   = vec3(0.7, 0.1, 0.1);
    m.surf.specular  = vec3(0.7, 0.1, 0.1);
    m.surf.roughness = 0.4;
    m.surf.gloss     = 0.3;
    return m;
}
Medium   medium_checkers  (vec3 p){ return defaultMedium(); }

Material material_plateLines(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //metal
    m.surf.diffuse   = vec3(0.4);
    m.surf.specular  = vec3(0.4);
    m.surf.roughness = 0.4;
    m.surf.gloss     = 0.3;
    return m;
}
Medium   medium_plateLines  (vec3 p){ return defaultMedium(); }

Material material_plateConics(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //metal
    m.surf.diffuse   = vec3(0.1, 0.2, 0.7);
    m.surf.specular  = vec3(0.1, 0.2, 0.7);
    m.surf.roughness = 0.4;
    m.surf.gloss     = 0.3;
    return m;
}
Medium   medium_plateConics  (vec3 p){ return defaultMedium(); }

Material material_key(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //light
    m.surf.emit = 60.0*vec3(1.0);
    return m;
}
Medium   medium_key  (vec3 p){ return defaultMedium(); }

Material material_room(vec3 p, inout Vector n){
    vec3 q = p - ROOM_P;
    int faceData = roomFaceData(q, ROOM_HALFSIZE);
    if(faceData == ROOM_CEILING){ return makeLight(vec3(1.0), roomLight); }
    if(faceData == ROOM_FLOOR)  { return makeGloss(floorColor, 0.0, wallRough); }
    if(faceData == ROOM_LEFT)   { return makeGloss(warmColor,  0.0, wallRough); }
    if(faceData == ROOM_RIGHT)  { return makeGloss(coolColor,  0.0, wallRough); }
    return makeGloss(wallColor, 0.0, wallRough);
}
Medium medium_room(vec3 p){ return defaultMedium(); }


//---------------------------------------------------------------------
// the analytic intersections
//---------------------------------------------------------------------

float trace_key(Vector tv){
    return sphereTrace(tv, KEY_P, KEY_RADIUS);
}

float trace_room(Vector tv){
    return roomTrace(tv, ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the dispatchers
//---------------------------------------------------------------------

void sdfAll(vec3 p){
    sdf_surfaceGroup(p, gSDF[ID_SURFACE], gSDF[ID_PAIRLINES], gSDF[ID_CONICLINES], gSDF[ID_EXCEPTIONALLINES], gSDF[ID_RING]);
    sdf_plateGroup(p, gSDF[ID_PLATE], gSDF[ID_CHECKERS], gSDF[ID_PLATELINES], gSDF[ID_PLATECONICS]);
    gSDF[ID_KEY             ] = sdf_key(p);
    gSDF[ID_ROOM            ] = sdf_room(p);
}

Vector normalOf(int id, vec3 p){
    if(id == ID_SURFACE         ){ return normal_surface(p); }
    if(id == ID_PAIRLINES       ){ return normal_pairLines(p); }
    if(id == ID_CONICLINES      ){ return normal_conicLines(p); }
    if(id == ID_EXCEPTIONALLINES){ return normal_exceptionalLines(p); }
    if(id == ID_RING            ){ return normal_ring(p); }
    if(id == ID_PLATE           ){ return normal_plate(p); }
    if(id == ID_CHECKERS        ){ return normal_checkers(p); }
    if(id == ID_PLATELINES      ){ return normal_plateLines(p); }
    if(id == ID_PLATECONICS     ){ return normal_plateConics(p); }
    if(id == ID_KEY             ){ return normal_key(p); }
    return normal_room(p);
}

//no sheets in this scene: every object is a region with an interior
bool isSheet(int id){ return false; }

Material materialOf(int id, vec3 p, inout Vector n, bool front){
    if(id == ID_SURFACE         ){ return material_surface(p, n); }
    if(id == ID_PAIRLINES       ){ return material_pairLines(p, n); }
    if(id == ID_CONICLINES      ){ return material_conicLines(p, n); }
    if(id == ID_EXCEPTIONALLINES){ return material_exceptionalLines(p, n); }
    if(id == ID_RING            ){ return material_ring(p, n); }
    if(id == ID_PLATE           ){ return material_plate(p, n); }
    if(id == ID_CHECKERS        ){ return material_checkers(p, n); }
    if(id == ID_PLATELINES      ){ return material_plateLines(p, n); }
    if(id == ID_PLATECONICS     ){ return material_plateConics(p, n); }
    if(id == ID_KEY             ){ return material_key(p, n); }
    return material_room(p, n);
}

Medium mediumOf(int id, vec3 p){
    if(id == ID_SURFACE         ){ return medium_surface(p); }
    if(id == ID_PAIRLINES       ){ return medium_pairLines(p); }
    if(id == ID_CONICLINES      ){ return medium_conicLines(p); }
    if(id == ID_EXCEPTIONALLINES){ return medium_exceptionalLines(p); }
    if(id == ID_RING            ){ return medium_ring(p); }
    if(id == ID_PLATE           ){ return medium_plate(p); }
    if(id == ID_CHECKERS        ){ return medium_checkers(p); }
    if(id == ID_PLATELINES      ){ return medium_plateLines(p); }
    if(id == ID_PLATECONICS     ){ return medium_plateConics(p); }
    if(id == ID_KEY             ){ return medium_key(p); }
    if(id == ID_ROOM            ){ return medium_room(p); }
    return defaultMedium();      //ID_NONE: open air
}


//---------------------------------------------------------------------
// the entry points
//---------------------------------------------------------------------

void buildScene(){}

float sdf_Scene(Vector tv){
    vec3 p = tv.pos;
    float d = maxDist;

    float b_surfaceGroup = bound_surfaceGroup(p);
    if(b_surfaceGroup > BOUND_MARGIN){ d = min(d, b_surfaceGroup); }
    else{
        float surface, pairLines, conicLines, exceptionalLines, ring;
        sdf_surfaceGroup(p, surface, pairLines, conicLines, exceptionalLines, ring);
        d = min(d, min(min(min(min(surface, pairLines), conicLines), exceptionalLines), ring));
    }

    float b_plateGroup = bound_plateGroup(p);
    if(b_plateGroup > BOUND_MARGIN){ d = min(d, b_plateGroup); }
    else{
        float plate, checkers, plateLines, plateConics;
        sdf_plateGroup(p, plate, checkers, plateLines, plateConics);
        d = min(d, min(min(min(plate, checkers), plateLines), plateConics));
    }

    return d;
}

float trace_Scene(Vector tv){
    float d = maxDist;
    d = min(d, trace_key(tv));
    d = min(d, trace_room(tv));
    return d;
}
