//=====================================================================
// generated by scenegen from src/scene.js — do not edit by hand
//=====================================================================


//--- library: glsl/shapes/gem.glsl ---
//----------------------------------------------------------------------------
// GEM — a brilliant-ish cut stone, girdle radius `size`.
//
// 8 crown facets rising to an octagonal table, 8 pavilion facets falling to the
// culet point, offset half a sector so the rings alternate (the classic
// brilliant look), plus an octagonal girdle band. Built as an exact convex
// intersection of planes: folding the angle into one wedge makes r*cos(folded)
// the support function of every rotated facet copy, so max() over the plane set
// is a true convex sdf that sphere-traces cleanly. Unit proportions: girdle
// radius 1, table at y=0.38, culet at (0,-0.85).
//
// glsl/shapes/ is the math-only library: plain functions of a point and floats.
//----------------------------------------------------------------------------


//fold the angle into the +/- sector/2 wedge about phase, and return the folded
//radial support r*cos(a) (file-private helper)
float gem_support(float r, float ang, float sector, float phase){
    float a = mod(ang + phase + 0.5*sector, sector) - 0.5*sector;
    return r*cos(a);
}


// p is in the gem's own coordinates (origin at the girdle centre)
float gemDistance(vec3 p, float size){
    p /= size;
    float r   = length(p.xz);
    float ang = atan(p.z, p.x);
    const float sector = 2.*PI/8.;

    float rc = gem_support(r, ang, sector, 0.);            //crown + girdle wedge
    float rp = gem_support(r, ang, sector, 0.5*sector);    //pavilion wedge (alternates)

    float table    = p.y - 0.38;
    float girdle   = rc - 1.;
    float crown    = dot(vec2(rc, p.y), vec2(0.5547, 0.8321)) - 0.6213;
    float pavilion = dot(vec2(rp, p.y), vec2(0.6247, -0.7809)) - 0.6637;

    return size * max( max(table, girdle), max(crown, pavilion) );
}


// bounding sphere: girdle polygon corners reach r = 1.082, all else is inside
float gemBound(vec3 p, float size){
    return length(p) - 1.15*size;
}


//--- library: glsl/shapes/sphere.glsl ---
//----------------------------------------------------------------------------
// SPHERE
//
// glsl/shapes/ is the math-only library: plain functions of a point and some
// floats. No structs, no Frame, no Material, no at()/inside()/setData().
// Placement, materials and the region interface are emitted by the scene.
//----------------------------------------------------------------------------


// p is in the sphere's own coordinates (origin at the centre)
float sphereDistance(vec3 p, float radius){
    return length(p) - radius;
}


// Exact ray intersection, in world coordinates: the distance along tv to the
// sphere, or maxDist if it is not in front of us. tv.dir is unit length.
//
// A ray STARTING INSIDE takes the far root — glass needs that, since a
// transmitted ray has to find the far wall of the object it just entered.
float sphereTrace(Vector tv, vec3 centre, float radius){
    vec3  oc = tv.pos - centre;
    float b  = dot(oc, tv.dir);
    float c  = dot(oc, oc) - radius*radius;
    float disc = b*b - c;
    if(disc < 0.){ return maxDist; }

    float s = sqrt(disc);
    float t = -b - s;
    if(t < 0.){ t = -b + s; }
    if(t < 0.){ return maxDist; }
    return min(t, maxDist);
}


//--- library: glsl/shapes/room.glsl ---
//----------------------------------------------------------------------------
// ROOM — a closed box, seen from the inside.
//
// The room is ONE region whose solid is everything OUTSIDE the box, so the
// interior is open air and regionAt() returns ID_NONE there. Its six walls are
// not six objects: they are a material FIELD over that one region, read off by
// asking which face a point is nearest. roomFace() answers that.
//
// glsl/shapes/ is the math-only library: plain functions of a point and some
// floats. No structs, no Frame, no Material.
//----------------------------------------------------------------------------


const int ROOM_FLOOR   = 0;
const int ROOM_CEILING = 1;
const int ROOM_LEFT    = 2;
const int ROOM_RIGHT   = 3;
const int ROOM_FRONT   = 4;
const int ROOM_BACK    = 5;


// p is in the room's own coordinates (origin at the box centre).
// Negative in the WALLS, positive in the open interior — the sign convention
// every other region uses, just turned inside out.
float roomDistance(vec3 p, vec3 halfSize){
    return -bBox(p, halfSize);
}


// Exact ray intersection, in world coordinates. The ray is inside the box, so
// this is simply the distance at which it leaves: the nearest of the three
// far slab crossings.
float roomTrace(Vector tv, vec3 centre, vec3 halfSize){
    vec3  o  = tv.pos - centre;
    vec3  tm = max((-halfSize - o)/tv.dir, (halfSize - o)/tv.dir);
    float t  = min(tm.x, min(tm.y, tm.z));
    if(t < 0.){ return maxDist; }
    return min(t, maxDist);
}


// Which wall p is on (or nearest to). d is negative inside the room, so its
// LARGEST component names the axis the point is closest to leaving through,
// and the sign of p picks which of that axis's two faces.
int roomFace(vec3 p, vec3 halfSize){
    vec3 d = abs(p) - halfSize;

    if(d.y >= d.x && d.y >= d.z){
        return (p.y > 0.) ? ROOM_CEILING : ROOM_FLOOR;
    }
    if(d.x >= d.z){
        return (p.x > 0.) ? ROOM_RIGHT : ROOM_LEFT;
    }
    return (p.z > 0.) ? ROOM_BACK : ROOM_FRONT;
}


//--- the objects, in declaration order (= containment priority, inner to outer)
const int ID_STONE    = 0;
const int ID_KEYLIGHT = 1;
const int ID_RIMLIGHT = 2;
const int ID_ROOM     = 3;

const int N_OBJ = 4;
float gSDF[N_OBJ];


//--- placement and shape parameters ----------------------------------
const vec3  STONE_P    = vec3(0.0, 2.3, 0.0);
const vec3  STONE_AXIS = vec3(0.0, 0.0, 1.0);
const float STONE_SIZE = 2.0;

const vec3  KEYLIGHT_P      = vec3(6.0, 10.0, -7.0);
const float KEYLIGHT_RADIUS = 0.7;

const vec3  RIMLIGHT_P      = vec3(-8.0, 6.0, 4.0);
const float RIMLIGHT_RADIUS = 0.5;

const vec3 ROOM_P        = vec3(0.0, 11.0, 0.0);
const vec3 ROOM_HALFSIZE = vec3(16.0, 11.0, 16.0);


//---------------------------------------------------------------------
// the region sdfs
//---------------------------------------------------------------------

vec3 toLocal_stone(vec3 p){
    mat3 rot = rot3AxisAngle(normalize(STONE_AXIS), gemTilt);
    return (p - STONE_P) * rot;
}

float sdf_stone(vec3 p){
    float d = gemDistance(toLocal_stone(p), STONE_SIZE);
    return d;
}

float sdf_keyLight(vec3 p){
    return sphereDistance(p - KEYLIGHT_P, KEYLIGHT_RADIUS);
}

float sdf_rimLight(vec3 p){
    return sphereDistance(p - RIMLIGHT_P, RIMLIGHT_RADIUS);
}

//the room SOLID is everything outside the box, so its interior is open air and
//regionAt() returns ID_NONE there
float sdf_room(vec3 p){
    return roomDistance(p - ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the normals — the 4-tap of each region's own sdf, in world coordinates
//---------------------------------------------------------------------
const float NRM_E = 0.0002;

Vector normal_stone(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_stone(p + k.xyy*NRM_E) + k.yyx*sdf_stone(p + k.yyx*NRM_E)
                              + k.yxy*sdf_stone(p + k.yxy*NRM_E) + k.xxx*sdf_stone(p + k.xxx*NRM_E) ));
}

Vector normal_keyLight(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_keyLight(p + k.xyy*NRM_E) + k.yyx*sdf_keyLight(p + k.yyx*NRM_E)
                              + k.yxy*sdf_keyLight(p + k.yxy*NRM_E) + k.xxx*sdf_keyLight(p + k.xxx*NRM_E) ));
}

Vector normal_rimLight(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_rimLight(p + k.xyy*NRM_E) + k.yyx*sdf_rimLight(p + k.yyx*NRM_E)
                              + k.yxy*sdf_rimLight(p + k.yxy*NRM_E) + k.xxx*sdf_rimLight(p + k.xxx*NRM_E) ));
}

Vector normal_room(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_room(p + k.xyy*NRM_E) + k.yyx*sdf_room(p + k.yyx*NRM_E)
                              + k.yxy*sdf_room(p + k.yxy*NRM_E) + k.xxx*sdf_room(p + k.xxx*NRM_E) ));
}


//---------------------------------------------------------------------
// the materials
//  material_ gives the Surface plus this object's own Medium; medium_ gives
//  only the Medium, for when the object is merely the far side
//---------------------------------------------------------------------

Medium medium_stone(vec3 p){
    Medium m = defaultMedium();
    m.ior    = ior;
    m.absorb = vec3(0.0);
    return m;
}
Material material_stone(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //glass
    m.interior = medium_stone(p);
    m.surf.transmit = 1.0;
    return m;
}

Material material_keyLight(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //light
    m.surf.emit = lightPower*vec3(1.0);
    return m;
}
Medium   medium_keyLight  (vec3 p){ return defaultMedium(); }

Material material_rimLight(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //light
    m.surf.emit = 0.4*lightPower*vec3(1.0);
    return m;
}
Medium   medium_rimLight  (vec3 p){ return defaultMedium(); }

Material material_room(vec3 p, inout Vector n){
    vec3 q = p - ROOM_P;
    int face = roomFace(q, /*half*/vec3(16.0, 11.0, 16.0));

    if(face == ROOM_CEILING){ return makeLight(vec3(1.0), roomLight); }
    if(face == ROOM_FLOOR)  { return makeGloss(floorColor, 0.0, wallRough); }
    if(face == ROOM_LEFT)   { return makeGloss(warmColor,  0.0, wallRough); }
    if(face == ROOM_RIGHT)  { return makeGloss(coolColor,  0.0, wallRough); }
    return makeGloss(wallColor, 0.0, wallRough);
}
Medium medium_room(vec3 p){ return defaultMedium(); }


//---------------------------------------------------------------------
// the analytic intersections
//---------------------------------------------------------------------

float trace_keyLight(Vector tv){
    return sphereTrace(tv, KEYLIGHT_P, KEYLIGHT_RADIUS);
}

float trace_rimLight(Vector tv){
    return sphereTrace(tv, RIMLIGHT_P, RIMLIGHT_RADIUS);
}

float trace_room(Vector tv){
    return roomTrace(tv, ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the dispatchers
//---------------------------------------------------------------------

void sdfAll(vec3 p){
    gSDF[ID_STONE   ] = sdf_stone(p);
    gSDF[ID_KEYLIGHT] = sdf_keyLight(p);
    gSDF[ID_RIMLIGHT] = sdf_rimLight(p);
    gSDF[ID_ROOM    ] = sdf_room(p);
}

Vector normalOf(int id, vec3 p){
    if(id == ID_STONE   ){ return normal_stone(p); }
    if(id == ID_KEYLIGHT){ return normal_keyLight(p); }
    if(id == ID_RIMLIGHT){ return normal_rimLight(p); }
    return normal_room(p);
}

//no sheets in this scene: every object is a region with an interior
bool isSheet(int id){ return false; }

Material materialOf(int id, vec3 p, inout Vector n, bool front){
    if(id == ID_STONE   ){ return material_stone(p, n); }
    if(id == ID_KEYLIGHT){ return material_keyLight(p, n); }
    if(id == ID_RIMLIGHT){ return material_rimLight(p, n); }
    return material_room(p, n);
}

Medium mediumOf(int id, vec3 p){
    if(id == ID_STONE   ){ return medium_stone(p); }
    if(id == ID_KEYLIGHT){ return medium_keyLight(p); }
    if(id == ID_RIMLIGHT){ return medium_rimLight(p); }
    if(id == ID_ROOM    ){ return medium_room(p); }
    return defaultMedium();      //ID_NONE: open air
}


//---------------------------------------------------------------------
// the entry points
//---------------------------------------------------------------------

void buildScene(){}

float sdf_Scene(Vector tv){
    vec3 p = tv.pos;
    float d = maxDist;

    d = min(d, sdf_stone(p));

    return d;
}

float trace_Scene(Vector tv){
    float d = maxDist;
    d = min(d, trace_keyLight(tv));
    d = min(d, trace_rimLight(tv));
    d = min(d, trace_room(tv));
    return d;
}
