//=====================================================================
// generated by scenegen from src/scene.js — do not edit by hand
//=====================================================================


//--- library: glsl/shapes/sphere.glsl ---
//----------------------------------------------------------------------------
// SPHERE
//
// glsl/shapes/ is the math-only library: plain functions of a point and some
// floats. No structs, no Frame, no Material, no at()/inside()/setData().
// Placement, materials and the region interface are emitted by the scene.
//----------------------------------------------------------------------------


// p is in the sphere's own coordinates (origin at the centre)
float sphereDistance(vec3 p, float radius){
    return length(p) - radius;
}


// Exact ray intersection, in world coordinates: the distance along tv to the
// sphere, or maxDist if it is not in front of us. tv.dir is unit length.
//
// A ray STARTING INSIDE takes the far root — glass needs that, since a
// transmitted ray has to find the far wall of the object it just entered.
float sphereTrace(Vector tv, vec3 centre, float radius){
    vec3  oc = tv.pos - centre;
    float b  = dot(oc, tv.dir);
    float c  = dot(oc, oc) - radius*radius;
    float disc = b*b - c;
    if(disc < 0.){ return maxDist; }

    float s = sqrt(disc);
    float t = -b - s;
    if(t < 0.){ t = -b + s; }
    if(t < 0.){ return maxDist; }
    return min(t, maxDist);
}


//--- library: glsl/shapes/variety.glsl ---
//@noshape — helpers, not a catalogue shape: the variety builder is its own
//           (carefully designed) piece of the generator, still to come
//----------------------------------------------------------------------------
// ALGEBRAIC VARIETIES
//
// A variety is not authored as a distance function. It is authored as an
// EQUATION — `T eqn(T x, T y, T z)` in dual numbers, from the catalogue in
// glsl/objects/varieties/formulas/ — and everything else is derived:
//
//   1. the gradient        three dual-number evaluations, one per partial.
//                          GENERATED per equation: it is four lines of glue
//                          from the equation's name and nothing else.
//   2. the distance        DE(value, |gradient|) — a first-order estimate of the
//                          distance to the zero set (1Setup/dualNumbers.glsl).
//   3. finite extent       the zero set is unbounded, so it is CLIPPED to some
//                          shape with smax.
//   4. thickness           a level set is infinitely thin. Left alone it is a
//                          SHEET; thickened it becomes a REGION with an inside.
//
// So the author supplies: an equation, a clip shape, a thickness (or none), and
// a bound. That is the whole of a variety object.
//
// This file holds 2 and 4. The gradient is generated; the clip and the bound are
// ordinary shapes from elsewhere in glsl/shapes/.
//----------------------------------------------------------------------------


// data.xyz = gradient, data.w = value, both at the SCALED point. `scale` is the
// variety's internal zoom: the chain rule puts it on the gradient, which keeps
// the returned distance in the object's own local units.
float varietyDistance(vec4 data, float scale){
    return DE(data.w, length(data.xyz)*scale);
}


// Thicken a level set into a shell with a real inside. `inner` pushes the
// surface inward, `outer` outward, so the shell's total thickness is
// inner + outer — keep that comfortably above 2*AT_THRESH or the classifier
// cannot tell the two faces apart.
//
// Leave this OFF to keep the variety a sheet: infinitely thin, two-sided, no
// interior and no refraction.
float varietyShell(float dist, float inner, float outer){
    return abs(dist + inner) - inner - outer;
}


//--- library: glsl/objects/varieties/formulas/misc.glsl ---
//-------------------------------------------------
// VARIETY FORMULAS — misc
// dual-number defining equations T eqn(T x,T y,T z[,T w]); the engine (T
// arithmetic, DE, invStereo) lives in glsl/tracer/1Setup/dualNumbers.glsl.
// #include this file in a scene's objects.glsl to use: gyroid, chmutov, kleinBottleVariety, riemannTwoBranch, enneper, goldman, mobiusStripVariety, mobiusStrip3TwistVariety, ellipticFibration, elliptic.
//-------------------------------------------------

T gyroid(T x, T y, T z){
    T term1 = tmul(tsin(x),tcos(y));
    T term2 = tmul(tsin(y), tcos(z));
    T term3 = tmul(tsin(z),tcos(x));
    return 1.*(term1 + term2 + term3);
}


T chmutov(T x, T y, T z) {
    int n = 2;
    return tcheb(x,n)+tcheb(y,n)+tcheb(z,n)+tfloat(1.0);
}


T kleinBottleVariety(T x, T y, T z){
    //order of input variables should be y,x,z for it laying on its side
    //ian stewart
   // (x^2+y^2+z^2+2*y-1)*((x^2+y^2+z^2-2*y-1)^2-8*z^2) +16*x*z*(x^2+y^2+z^2-2*y-1)=0
    T x2 = tsqr(x);
    T y2 = tsqr(y);
    T z2 = tsqr(z);
    T r2 =  x2 + y2 + z2;
    T term1 = r2 + 2.*y - T(1,0);
    T term2 = r2 - 2.*y - T(1,0);

    return tmul(term1, tsqr(term2) - 8.*z2) + 16.*tmul(x,z,term2);
}


T riemannTwoBranch(T x, T y, T z){
    //z^2*x^2+(z^2+1)*y^2=5*(z^4+z^2)

    T x2 = tsqr(x);
    T y2 = tsqr(y);
    T z2 = tsqr(z);
    T z4 = tsqr(z2);

    return tmul(z2,x2) + tmul(z2+T(1,0), y2) - 5.*(z4+z2);
}


T enneper(T x, T y, T z){

        //doesn't work well as a thickened surface, if we use the variety to thicken it
        //it gets unnaturally thick near the xy plane
        float a = 1.;
        float a2 = a*a;
        float a3 = a*a*a;
        T x2 = tsqr(x);
        T y2 = tsqr(y);
        T z2 = tsqr(z);
        T z3 = tmul(z2,z);

    T term1 = a/2.*(y2-x2) + 2./9.* z3 + 2./3.*a2*z;
    T term2 = a/4.*(y2-x2) - 1./4.*tmul(z,x2+y2+8./9.*z2) + 2./9.*a2*z;

    return -tmul(term1,term1,term1) + 6.*a3*tmul(z,term2,term2);

}





T goldman(T x, T y, T z){

    //free parameters, wired to the GUI scratch knobs
    float a = 2.*scratch1;
    float b = 2.*scratch2;
    float c = 2.*scratch3;
    float d = 2.*scratch4;
    float k = 4.-a*a-b*b-c*c-a*b*c*d;

    T x2 = tsqr(x);
    T y2 = tsqr(y);
    T z2 = tsqr(z);
    T xyz = tmul(x,tmul(y,z));


    T term1 = (a*b+c*d)*x + (a*d+b*c)*y + (a*c+b*d)*z + T(k,0);
    T term2 =x2 + y2 + z2 + xyz;

    return term2-term1;

}


//================================
// MOBIUS BANDS
//================================


T mobiusStripVariety(T x, T y, T z){

    //https://www.imaginary.org/sites/default/files/moebiusband.pdf

    float a = 0.02;
    float b = 0.6;
    T x2 = tsqr(x);
    T y2 = tsqr(y);
    T z2 = tsqr(z);
    T t2 = x2+y2;

    T term1 = (a-b)*(tmul(x,t2-z2+T(1,0))-2.*tmul(y,z));
    T term2 = (2.*a + 2.*b + a*b)*t2;
    T term3 = (a+b)*(t2+z2+T(1,0));
    T term4 = 2.*(a-b)*(tmul(y,z)-x);

    T side1 = term1-term2;
    T side2 = (term3+term4);

    return -tsqr(side1)+tmul(t2,tsqr(side2));

}


T mobiusStrip3TwistVariety(T x, T y, T z){

    //https://www.imaginary.org/sites/default/files/moebiusband.pdf

    float a = 0.01;
    float b = 0.33;
    T x2 = tsqr(x);
    T y2 = tsqr(y);
    T z2 = tsqr(z);
    T t2 = x2+y2;
    T t4 = tsqr(t2);

    T comp1 = 3.*tmul(x2,y)-tmul(y2,y);
    T comp2 = tmul(x,x2)-3.*tmul(x,y2);

    T term1 = -2.*(a+b)*t4+(a-b)*(tmul(comp1, t2-z2+T(1,0))-2.*tmul(comp2,z));
    T term2 = (a+b)*tmul(t2, (t2+z2+T(1,0))) - 2.*(a-b)*(comp1 - tmul(z,comp2)) - 2.*a*b*t2;

    return - tsqr(term1) + tmul(t2,tsqr(term2));

}








T ellipticFibration(T x, T y, T t){
    //from nadir, universal family over X15
    //t x^2 - x^3 - t y + (1 - t) x y + y^2 = 0



    //map xy into a disk:
    float lengthScale = 3.5;
    T r = tsqrt(tsqr(x)+tsqr(y));
    T scalingFactor = tsqr(texp(r/lengthScale))+tsqr(texp(-r/lengthScale));
    scalingFactor -= T(2,0);
    x = tmul(x,scalingFactor);
    y = tmul(y,scalingFactor);


    t = tmul(t,t,t);
    t = t/10.;



    T x2 = tsqr(x);
    T x3 = tmul(x,x2);
    T y2 = tsqr(y);

    return tmul(t, x2) - x3 - tmul(t,y) + tmul(T(1,0)-t,x,y) + y2;
}




T elliptic(T x, T y, T t){
    //from nadir, universal family over X15
    //t x^2z - x^3 - t yz^2 + (1 - t) x yz + y^2z = 0

    //expand out the t-axis, shrinking the importance of larger values
    //T newT = tmul(t,t,t);
   // newT *= 10.;

    //shrink in the t axis from infinity: for t between -pi/2 and pi/2 shows whole line
    T newT = ttan(t);

    //use inverse stereographic projection to draw double cover
    //then, see only one piece by drawing only the lower hemisphere: where (x,y) is in the unit disk
    //for this to work both scale and bounding box should be set to size 1
    T X, Y, Z;
    invStereo(x,y,X,Y,Z);

    T X2 = tsqr(X);
    T Y2 = tsqr(Y);
    T Z2 = tsqr(Z);
    T X3 = tmul(X,X2);


    // // a test: a trivial family of ellptic curves
    // // and its inverse stereographic projection
    //return tsqr(y) - tmul(x,x,x)-tmul(x,x);
    //return -(tmul(Y2, Z) - X3 - tmul(X2,Z));

    //nadir's family
    return -(tmul(newT,X2,Z) - X3 - tmul(newT, Y, Z2) + tmul(T(1,0)-newT,tmul(X,Y,Z)) + tmul(Y2,Z));
}


//--- library: glsl/shapes/room.glsl ---
//----------------------------------------------------------------------------
// ROOM — a closed box, seen from the inside.
//
// The room is ONE region whose solid is everything OUTSIDE the box, so the
// interior is open air and regionAt() returns ID_NONE there. Its six walls are
// not six objects: they are a material FIELD over that one region, read off by
// asking which face a point is nearest. roomFace() answers that.
//
// glsl/shapes/ is the math-only library: plain functions of a point and some
// floats. No structs, no Frame, no Material.
//----------------------------------------------------------------------------


const int ROOM_FLOOR   = 0;
const int ROOM_CEILING = 1;
const int ROOM_LEFT    = 2;
const int ROOM_RIGHT   = 3;
const int ROOM_FRONT   = 4;
const int ROOM_BACK    = 5;


// p is in the room's own coordinates (origin at the box centre).
// Negative in the WALLS, positive in the open interior — the sign convention
// every other region uses, just turned inside out.
float roomDistance(vec3 p, vec3 halfSize){
    return -bBox(p, halfSize);
}


// Exact ray intersection, in world coordinates. The ray is inside the box, so
// this is simply the distance at which it leaves: the nearest of the three
// far slab crossings.
float roomTrace(Vector tv, vec3 centre, vec3 halfSize){
    vec3  o  = tv.pos - centre;
    vec3  tm = max((-halfSize - o)/tv.dir, (halfSize - o)/tv.dir);
    float t  = min(tm.x, min(tm.y, tm.z));
    if(t < 0.){ return maxDist; }
    return min(t, maxDist);
}


// Which wall p is on (or nearest to) — a shape DATA output (docs/shape-data.md):
// a material that reads `faceData` gets it injected. d is negative inside the
// room, so its LARGEST component names the axis the point is closest to leaving
// through, and the sign of p picks which of that axis's two faces.
int roomFaceData(vec3 p, vec3 halfSize){
    vec3 d = abs(p) - halfSize;

    if(d.y >= d.x && d.y >= d.z){
        return (p.y > 0.) ? ROOM_CEILING : ROOM_FLOOR;
    }
    if(d.x >= d.z){
        return (p.x > 0.) ? ROOM_RIGHT : ROOM_LEFT;
    }
    return (p.z > 0.) ? ROOM_BACK : ROOM_FRONT;
}


//--- the objects, in declaration order (= containment priority, inner to outer)
const int ID_VEIL   = 0;
const int ID_MARBLE = 1;
const int ID_LAMP   = 2;
const int ID_ROOM   = 3;

const int N_OBJ = 4;
float gSDF[N_OBJ];


//--- placement and shape parameters ----------------------------------
const vec3  VEIL_P           = vec3(0.0, 1.5, 0.0);
const float VEIL_CLIP_RADIUS = 1.15;
const float VEIL_CLIP_BLEND  = 0.04;

const vec3  MARBLE_P      = vec3(0.0, 1.5, 0.0);
const float MARBLE_RADIUS = 1.25;

const vec3  LAMP_P      = vec3(-4.0, 8.5, 5.0);
const float LAMP_RADIUS = 1.4;

const vec3 ROOM_P        = vec3(0.0, 6.0, 0.0);
const vec3 ROOM_HALFSIZE = vec3(10.0, 6.0, 10.0);


//---------------------------------------------------------------------
// the region sdfs
//---------------------------------------------------------------------

vec4 data_veil(vec3 p){
    T vx = enneper(T(p.x, 1.0), T(p.y, 0.0), T(p.z, 0.0));
    T vy = enneper(T(p.x, 0.0), T(p.y, 1.0), T(p.z, 0.0));
    T vz = enneper(T(p.x, 0.0), T(p.y, 0.0), T(p.z, 1.0));
    return vec4(vx.y, vy.y, vz.y, vx.x);
}

float sdf_veil(vec3 p){
    float d = varietyDistance(data_veil(veilScale*(p - VEIL_P)), veilScale);
    return smax(d, sphereDistance(p - VEIL_P, VEIL_CLIP_RADIUS), VEIL_CLIP_BLEND);
}

//the marched form: abs stops the ray on {s=0}; the hard max keeps the
//cut cap over {s<0} undrawn. sdf_veil stays signed for faces/normals.
float march_veil(vec3 p){
    float d = varietyDistance(data_veil(veilScale*(p - VEIL_P)), veilScale);
    return max(abs(d), sphereDistance(p - VEIL_P, VEIL_CLIP_RADIUS));
}

float sdf_marble(vec3 p){
    return sphereDistance(p - MARBLE_P, MARBLE_RADIUS);
}

float sdf_lamp(vec3 p){
    return sphereDistance(p - LAMP_P, LAMP_RADIUS);
}

//the room SOLID is everything outside the box, so its interior is open air and
//regionAt() returns ID_NONE there
float sdf_room(vec3 p){
    return roomDistance(p - ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the bounds — the acceleration structure (sdf_Scene only; sdfAll stays exact)
//---------------------------------------------------------------------

float bound_veil(vec3 p){
    return sphereDistance(p - VEIL_P, VEIL_CLIP_RADIUS) - VEIL_CLIP_BLEND;
}


//---------------------------------------------------------------------
// the normals — the 4-tap of each region's own sdf, in world coordinates
//---------------------------------------------------------------------
const float NRM_E = 0.0002;

Vector normal_veil(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_veil(p + k.xyy*NRM_E) + k.yyx*sdf_veil(p + k.yyx*NRM_E)
                              + k.yxy*sdf_veil(p + k.yxy*NRM_E) + k.xxx*sdf_veil(p + k.xxx*NRM_E) ));
}

Vector normal_marble(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_marble(p + k.xyy*NRM_E) + k.yyx*sdf_marble(p + k.yyx*NRM_E)
                              + k.yxy*sdf_marble(p + k.yxy*NRM_E) + k.xxx*sdf_marble(p + k.xxx*NRM_E) ));
}

Vector normal_lamp(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_lamp(p + k.xyy*NRM_E) + k.yyx*sdf_lamp(p + k.yyx*NRM_E)
                              + k.yxy*sdf_lamp(p + k.yxy*NRM_E) + k.xxx*sdf_lamp(p + k.xxx*NRM_E) ));
}

Vector normal_room(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_room(p + k.xyy*NRM_E) + k.yyx*sdf_room(p + k.yyx*NRM_E)
                              + k.yxy*sdf_room(p + k.yxy*NRM_E) + k.xxx*sdf_room(p + k.xxx*NRM_E) ));
}


//---------------------------------------------------------------------
// the materials
//  material_ gives the Surface plus this object's own Medium; medium_ gives
//  only the Medium, for when the object is merely the far side
//---------------------------------------------------------------------

Material material_veil(vec3 p, inout Vector n, bool front){
    if(front){ return makeGloss(frontColor, veilGloss, 0.2); }
    return makeGloss(backColor, veilGloss, 0.2);
}
Medium medium_veil(vec3 p){ return defaultMedium(); }

Medium medium_marble(vec3 p){
    Medium m = defaultMedium();
    m.ior    = 1.5;
    m.absorb = absorbFor(vec3(0.78, 0.86, 0.95), 2.5);
    return m;
}
Material material_marble(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //glass
    m.interior = medium_marble(p);
    m.surf.transmit = 1.0;
    return m;
}

Material material_lamp(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //light
    m.surf.emit = lampPower*vec3(1.0, 0.95, 0.88);
    return m;
}
Medium   medium_lamp  (vec3 p){ return defaultMedium(); }

Material material_room(vec3 p, inout Vector n){
    vec3 q = p - ROOM_P;
    int faceData = roomFaceData(q, ROOM_HALFSIZE);
    if(faceData == ROOM_CEILING){ return makeLight(vec3(1.0), roomLight); }
    if(faceData == ROOM_FLOOR)  { return makeGloss(floorColor, 0.0, wallRough); }
    if(faceData == ROOM_LEFT)   { return makeGloss(warmColor,  0.0, wallRough); }
    if(faceData == ROOM_RIGHT)  { return makeGloss(coolColor,  0.0, wallRough); }
    return makeGloss(wallColor, 0.0, wallRough);
}
Medium medium_room(vec3 p){ return defaultMedium(); }


//---------------------------------------------------------------------
// the analytic intersections
//---------------------------------------------------------------------

float trace_marble(Vector tv){
    return sphereTrace(tv, MARBLE_P, MARBLE_RADIUS);
}

float trace_lamp(Vector tv){
    return sphereTrace(tv, LAMP_P, LAMP_RADIUS);
}

float trace_room(Vector tv){
    return roomTrace(tv, ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the dispatchers
//---------------------------------------------------------------------

void sdfAll(vec3 p){
    gSDF[ID_VEIL  ] = sdf_veil(p);
    gSDF[ID_MARBLE] = sdf_marble(p);
    gSDF[ID_LAMP  ] = sdf_lamp(p);
    gSDF[ID_ROOM  ] = sdf_room(p);
}

Vector normalOf(int id, vec3 p){
    if(id == ID_VEIL  ){ return normal_veil(p); }
    if(id == ID_MARBLE){ return normal_marble(p); }
    if(id == ID_LAMP  ){ return normal_lamp(p); }
    return normal_room(p);
}

//sheets: two-sided surfaces with no interior, excluded from containment
bool isSheet(int id){ return id == ID_VEIL; }

Material materialOf(int id, vec3 p, inout Vector n, bool front){
    if(id == ID_VEIL  ){ return material_veil(p, n, front); }
    if(id == ID_MARBLE){ return material_marble(p, n); }
    if(id == ID_LAMP  ){ return material_lamp(p, n); }
    return material_room(p, n);
}

Medium mediumOf(int id, vec3 p){
    if(id == ID_VEIL  ){ return medium_veil(p); }
    if(id == ID_MARBLE){ return medium_marble(p); }
    if(id == ID_LAMP  ){ return medium_lamp(p); }
    if(id == ID_ROOM  ){ return medium_room(p); }
    return defaultMedium();      //ID_NONE: open air
}


//---------------------------------------------------------------------
// the entry points
//---------------------------------------------------------------------

void buildScene(){}

float sdf_Scene(Vector tv){
    vec3 p = tv.pos;
    float d = maxDist;

    float b_veil = bound_veil(p);
    d = min(d, (b_veil > BOUND_MARGIN) ? b_veil : march_veil(p));

    return d;
}

float trace_Scene(Vector tv){
    float d = maxDist;
    d = min(d, trace_marble(tv));
    d = min(d, trace_lamp(tv));
    d = min(d, trace_room(tv));
    return d;
}
