//=====================================================================
// generated by scenegen from src/scene.js — do not edit by hand
//=====================================================================


//--- the objects, in declaration order (= containment priority, inner to outer)
const int ID_CHROMEBALL = 0;
const int ID_GLASSBALL  = 1;
const int ID_GOLDBALL   = 2;
const int ID_MATTEBALL  = 3;
const int ID_GROUND     = 4;

const int N_OBJ = 5;
float gSDF[N_OBJ];


//--- placement and shape parameters ----------------------------------
const vec3  CHROMEBALL_P      = vec3(-3.3, 1.0, 0.0);
const float CHROMEBALL_RADIUS = 1.0;

const vec3  GLASSBALL_P      = vec3(-1.1, 1.0, 0.0);
const float GLASSBALL_RADIUS = 1.0;

const vec3  GOLDBALL_P      = vec3(1.1, 1.0, 0.0);
const float GOLDBALL_RADIUS = 1.0;

const vec3  MATTEBALL_P      = vec3(3.3, 1.0, 0.0);
const float MATTEBALL_RADIUS = 1.0;

const vec3 GROUND_P      = vec3(0.0);
const vec3 GROUND_NORMAL = vec3(0.0, 1.0, 0.0);


//---------------------------------------------------------------------
// the region sdfs
//---------------------------------------------------------------------

float sdf_chromeBall(vec3 p){
    return sphereDistance(p - CHROMEBALL_P, CHROMEBALL_RADIUS);
}

float sdf_glassBall(vec3 p){
    return sphereDistance(p - GLASSBALL_P, GLASSBALL_RADIUS);
}

float sdf_goldBall(vec3 p){
    return sphereDistance(p - GOLDBALL_P, GOLDBALL_RADIUS);
}

float sdf_matteBall(vec3 p){
    return sphereDistance(p - MATTEBALL_P, MATTEBALL_RADIUS);
}

float sdf_ground(vec3 p){
    return planeDistance(p - GROUND_P, GROUND_NORMAL);
}


//---------------------------------------------------------------------
// the normals — the 4-tap of each region's own sdf, in world coordinates
//---------------------------------------------------------------------
const float NRM_E = 0.0002;

Vector normal_chromeBall(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_chromeBall(p + k.xyy*NRM_E) + k.yyx*sdf_chromeBall(p + k.yyx*NRM_E)
                              + k.yxy*sdf_chromeBall(p + k.yxy*NRM_E) + k.xxx*sdf_chromeBall(p + k.xxx*NRM_E) ));
}

Vector normal_glassBall(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_glassBall(p + k.xyy*NRM_E) + k.yyx*sdf_glassBall(p + k.yyx*NRM_E)
                              + k.yxy*sdf_glassBall(p + k.yxy*NRM_E) + k.xxx*sdf_glassBall(p + k.xxx*NRM_E) ));
}

Vector normal_goldBall(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_goldBall(p + k.xyy*NRM_E) + k.yyx*sdf_goldBall(p + k.yyx*NRM_E)
                              + k.yxy*sdf_goldBall(p + k.yxy*NRM_E) + k.xxx*sdf_goldBall(p + k.xxx*NRM_E) ));
}

Vector normal_matteBall(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_matteBall(p + k.xyy*NRM_E) + k.yyx*sdf_matteBall(p + k.yyx*NRM_E)
                              + k.yxy*sdf_matteBall(p + k.yxy*NRM_E) + k.xxx*sdf_matteBall(p + k.xxx*NRM_E) ));
}

Vector normal_ground(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_ground(p + k.xyy*NRM_E) + k.yyx*sdf_ground(p + k.yyx*NRM_E)
                              + k.yxy*sdf_ground(p + k.yxy*NRM_E) + k.xxx*sdf_ground(p + k.xxx*NRM_E) ));
}


//---------------------------------------------------------------------
// the materials
//  material_ gives the Surface plus this object's own Medium; medium_ gives
//  only the Medium, for when the object is merely the far side
//---------------------------------------------------------------------

Material material_chromeBall(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //chrome
    m.surf.diffuse   = vec3(0.55, 0.556, 0.554);
    m.surf.specular  = vec3(0.55, 0.556, 0.554);
    m.surf.roughness = 0.02;
    m.surf.gloss     = 1.0;
    return m;
}
Medium   medium_chromeBall  (vec3 p){ return defaultMedium(); }

Medium medium_glassBall(vec3 p){
    Medium m = defaultMedium();
    m.ior    = 1.5;
    m.absorb = absorbFor(vec3(0.94, 0.97, 0.98), 2.0);
    return m;
}
Material material_glassBall(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //glass
    m.interior = medium_glassBall(p);
    m.surf.transmit = 1.0;
    return m;
}

Material material_goldBall(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //gold
    m.surf.diffuse   = vec3(1.0, 0.766, 0.336);
    m.surf.specular  = vec3(1.0, 0.766, 0.336);
    m.surf.roughness = 0.25;
    m.surf.gloss     = 1.0;
    return m;
}
Medium   medium_goldBall  (vec3 p){ return defaultMedium(); }

Material material_matteBall(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //matte
    m.surf.diffuse = vec3(0.8);
    return m;
}
Medium   medium_matteBall  (vec3 p){ return defaultMedium(); }

Material material_ground(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //matte
    m.surf.diffuse = vec3(0.45);
    return m;
}
Medium   medium_ground  (vec3 p){ return defaultMedium(); }


//---------------------------------------------------------------------
// the analytic intersections
//---------------------------------------------------------------------

float trace_chromeBall(Vector tv){
    return sphereTrace(tv, CHROMEBALL_P, CHROMEBALL_RADIUS);
}

float trace_glassBall(Vector tv){
    return sphereTrace(tv, GLASSBALL_P, GLASSBALL_RADIUS);
}

float trace_goldBall(Vector tv){
    return sphereTrace(tv, GOLDBALL_P, GOLDBALL_RADIUS);
}

float trace_matteBall(Vector tv){
    return sphereTrace(tv, MATTEBALL_P, MATTEBALL_RADIUS);
}

float trace_ground(Vector tv){
    return planeTrace(tv, GROUND_P, GROUND_NORMAL);
}


//---------------------------------------------------------------------
// the dispatchers
//---------------------------------------------------------------------

void sdfAll(vec3 p){
    gSDF[ID_CHROMEBALL] = sdf_chromeBall(p);
    gSDF[ID_GLASSBALL ] = sdf_glassBall(p);
    gSDF[ID_GOLDBALL  ] = sdf_goldBall(p);
    gSDF[ID_MATTEBALL ] = sdf_matteBall(p);
    gSDF[ID_GROUND    ] = sdf_ground(p);
}

Vector normalOf(int id, vec3 p){
    if(id == ID_CHROMEBALL){ return normal_chromeBall(p); }
    if(id == ID_GLASSBALL ){ return normal_glassBall(p); }
    if(id == ID_GOLDBALL  ){ return normal_goldBall(p); }
    if(id == ID_MATTEBALL ){ return normal_matteBall(p); }
    return normal_ground(p);
}

//no sheets in this scene: every object is a region with an interior
bool isSheet(int id){ return false; }

Material materialOf(int id, vec3 p, inout Vector n, bool front){
    if(id == ID_CHROMEBALL){ return material_chromeBall(p, n); }
    if(id == ID_GLASSBALL ){ return material_glassBall(p, n); }
    if(id == ID_GOLDBALL  ){ return material_goldBall(p, n); }
    if(id == ID_MATTEBALL ){ return material_matteBall(p, n); }
    return material_ground(p, n);
}

Medium mediumOf(int id, vec3 p){
    if(id == ID_CHROMEBALL){ return medium_chromeBall(p); }
    if(id == ID_GLASSBALL ){ return medium_glassBall(p); }
    if(id == ID_GOLDBALL  ){ return medium_goldBall(p); }
    if(id == ID_MATTEBALL ){ return medium_matteBall(p); }
    if(id == ID_GROUND    ){ return medium_ground(p); }
    return defaultMedium();      //ID_NONE: open air
}


//---------------------------------------------------------------------
// the entry points
//---------------------------------------------------------------------

void buildScene(){}

//nothing marches: every surface here has a closed-form intersection
float sdf_Scene(Vector tv){
    return maxDist;
}

float trace_Scene(Vector tv){
    float d = maxDist;
    d = min(d, trace_chromeBall(tv));
    d = min(d, trace_glassBall(tv));
    d = min(d, trace_goldBall(tv));
    d = min(d, trace_matteBall(tv));
    d = min(d, trace_ground(tv));
    return d;
}


//---------------------------------------------------------------------
// the lights — emissive spheres a diffuse bounce may aim at (aimLights.glsl)
//---------------------------------------------------------------------

int numLights(){ return 0; }

void lightSphere(int i, out vec3 c, out float r){
    c = vec3(0.); r = 0.;
}
