//=====================================================================
// generated by scenegen from src/scene.js — do not edit by hand
//=====================================================================


//--- library: glsl/shapes/models/hypDod.glsl ---
//----------------------------------------------------------------------------
// HYPERBOLIC DODECAHEDRON — the right-angled dodecahedron of H^3, drawn in the
// BALL (Poincare) model.
//
// The construction is the whole idea: in the ball model a hyperbolic PLANE is a
// Euclidean sphere meeting the unit sphere orthogonally. So the solid is the unit
// ball with twelve such spheres carved out of it, one per face — and the carving
// is `max(dist, -faceSphere)`, an intersection of the twelve outsides.
//
// Orthogonality fixes the geometry with no freedom left: a face sphere at
// distance d from the origin with radius r must satisfy d^2 = r^2 + 1, and for
// the right-angled dodecahedron c = 2/phi gives r = sqrt(c), d = sqrt(c+1).
// That is why this shape has no size parameter — it is THE right-angled
// dodecahedron, not a family.
//
// The face directions are the icosahedron's vertex directions, (0, ±1, ±phi)
// cycled, since the dodecahedron's faces point at its dual's vertices — the same
// duality primitives/dodecahedron.glsl uses.
//
// `rCent` carves a sphere out of the middle, turning the solid into a shell;
// rCent <= 0 leaves it solid.
//
// glsl/shapes/ is the math-only library: plain functions of a point and floats.
//----------------------------------------------------------------------------


// the six face directions, up to sign: (0, 1, phi) cycled over the axes.
// phi = 1.6180340, |(0, 1, phi)| = 1.9021130. The legacy normalized a truncated
// 1.618 instead of phi, which tilted every face by ~8e-6 — below anything
// visible, but these are the directions that actually make the solid
// right-angled, so the port uses exact phi.
const vec3 HYPDOD_FACES[6] = vec3[6](
    vec3( 0.0,        0.5257311,  0.8506508),
    vec3( 0.8506508,  0.0,        0.5257311),
    vec3( 0.5257311,  0.8506508,  0.0),
    vec3( 0.0,       -0.5257311,  0.8506508),
    vec3( 0.8506508,  0.0,       -0.5257311),
    vec3(-0.5257311,  0.8506508,  0.0)
);


// p is in the solid's own coordinates (origin at the centre of the ball model)
float hypDodDistance(vec3 p, float rCent){
    //c = 2/phi; the orthogonality condition d^2 = r^2 + 1 then gives both
    const float HYPDOD_R = 1.1117859;                    // sqrt(c),     c = 2/phi
    const float HYPDOD_D = 1.4953488;                    // sqrt(c + 1)

    float dist = length(p) - 1.0;                        //the unit ball

    //carve the twelve face spheres: each direction and its antipode
    for(int i = 0; i < 6; i++){
        vec3 v = HYPDOD_FACES[i];
        dist = max(dist, -(length(p - HYPDOD_D*v) - HYPDOD_R));
        dist = max(dist, -(length(p + HYPDOD_D*v) - HYPDOD_R));
    }

    //hollow out the middle, if asked
    if(rCent > 0.0){
        dist = smax(dist, rCent - length(p), 0.1);
    }
    return dist;
}


// the sdf starts at length(p) - 1 and is only ever max()'d LARGER (carving
// spheres out of the unit ball), so the solid is contained in the unit sphere
// and the ball's own first term is provably conservative.
float hypDodBound(vec3 p, float rCent){
    return length(p) - 1.0;
}


//--- library: glsl/shapes/models/hypCoxCube.glsl ---
//----------------------------------------------------------------------------
// HYPERBOLIC COXETER CUBE — a cube in H^3 whose dihedral angle is 2*pi/dihedral,
// drawn in the BALL (Poincare) model.
//
// Same construction as models/hypDod.glsl: in the ball model a hyperbolic plane
// is a Euclidean sphere orthogonal to the unit sphere, so the solid is the unit
// ball with six such spheres carved out, one per face, along the coordinate axes.
//
// Unlike the dodecahedron this IS a family, parametrized by `dihedral`. With
// theta2 = pi/dihedral, orthogonality (d^2 = r^2 + 1) plus the dihedral condition
// give the face-sphere geometry:
//     d = 1/sqrt(1 - 1/(2 sin^2(theta2))),    r = sqrt(d*d - 1)
//
// VALID RANGE: dihedral < 4, strictly. The root needs 2 sin^2(theta2) > 1, i.e.
// theta2 > pi/4, i.e. dihedral < 4; at exactly 4 the radicand is 0 and d blows up
// (the flat, Euclidean limit), and above 4 it is negative — no such solid. Useful
// values are around 2 to 3.9; d grows fast near the top (dihedral 3.99 puts the
// face spheres out at d = 16).
//
// A cross-check worth knowing: dihedral = 2.5 reproduces the right-angled
// dodecahedron's face spheres exactly, d = 5^(1/4) = 1.4953488 and r = 1.1117859
// — the same pair models/hypDod.glsl bakes in, since 1 + 2/phi = 2 phi - 1 = sqrt 5.
//
// FLAGGING FOR REVIEW: the legacy file called this parameter "the number of cubes
// fitting around a vertex" and treated theta2 as HALF the dihedral angle, which
// would make the hyperbolic (sub-right-angle) cases dihedral > 4 — exactly the
// range where the formula has no real solution. The formula and that description
// disagree, so the parameter's geometric name is left unclaimed here rather than
// guessed. The math is carried over unchanged.
//
// `rCent` carves a sphere out of the middle, turning the solid into a shell;
// rCent <= 0 leaves it solid.
//
// glsl/shapes/ is the math-only library: plain functions of a point and floats.
//----------------------------------------------------------------------------


// p is in the solid's own coordinates (origin at the centre of the ball model)
float hypCoxCubeDistance(vec3 p, float dihedral, float rCent){
    float theta2 = PI/dihedral;                          //half the dihedral angle
    float denom  = 2.*sin(theta2)*sin(theta2);
    float d      = 1./sqrt(1. - 1./denom);               //face-sphere centre distance
    float r      = sqrt(d*d - 1.);                       //and its radius (orthogonality)

    float dist = length(p) - 1.0;                        //the unit ball

    //carve the six face spheres, along +/- each coordinate axis
    for(int i = 0; i < 3; i++){
        vec3 v = vec3(i == 0 ? 1.0 : 0.0, i == 1 ? 1.0 : 0.0, i == 2 ? 1.0 : 0.0);
        dist = max(dist, -(length(p - d*v) - r));
        dist = max(dist, -(length(p + d*v) - r));
    }

    //hollow out the middle, if asked (a HARD max here, unlike the dodecahedron's
    //smooth one — preserved from the original)
    if(rCent > 0.0){
        dist = max(dist, rCent - length(p));
    }
    return dist;
}


// the sdf starts at length(p) - 1 and is only ever max()'d LARGER (carving
// spheres out of the unit ball), so the solid is contained in the unit sphere
// and the ball's own first term is provably conservative.
float hypCoxCubeBound(vec3 p, float dihedral, float rCent){
    return length(p) - 1.0;
}


//--- library: glsl/shapes/environments/room.glsl ---
//----------------------------------------------------------------------------
// ROOM — a closed box, seen from the inside.
//
// The room is ONE region whose solid is everything OUTSIDE the box, so the
// interior is open air and regionAt() returns ID_NONE there. Its six walls are
// not six objects: they are a material FIELD over that one region, read off by
// asking which face a point is nearest. roomFace() answers that.
//
// glsl/shapes/ is the math-only library: plain functions of a point and some
// floats. No structs, no Frame, no Material.
//----------------------------------------------------------------------------


const int ROOM_FLOOR   = 0;
const int ROOM_CEILING = 1;
const int ROOM_LEFT    = 2;
const int ROOM_RIGHT   = 3;
const int ROOM_FRONT   = 4;
const int ROOM_BACK    = 5;


// p is in the room's own coordinates (origin at the box centre).
// Negative in the WALLS, positive in the open interior — the sign convention
// every other region uses, just turned inside out.
float roomDistance(vec3 p, vec3 halfSize){
    return -boxDistance(p, halfSize);
}


// Exact ray intersection, in world coordinates. The ray is inside the box, so
// this is simply the distance at which it leaves: the nearest of the three
// far slab crossings.
float roomTrace(Vector tv, vec3 centre, vec3 halfSize){
    vec3  o  = tv.pos - centre;
    vec3  tm = max((-halfSize - o)/tv.dir, (halfSize - o)/tv.dir);
    float t  = min(tm.x, min(tm.y, tm.z));
    if(t < 0.){ return maxDist; }
    return min(t, maxDist);
}


// Which wall p is on (or nearest to) — a shape DATA output (docs/shape-data.md):
// a material that reads `faceData` gets it injected. d is negative inside the
// room, so its LARGEST component names the axis the point is closest to leaving
// through, and the sign of p picks which of that axis's two faces.
int roomFaceData(vec3 p, vec3 halfSize){
    vec3 d = abs(p) - halfSize;

    if(d.y >= d.x && d.y >= d.z){
        return (p.y > 0.) ? ROOM_CEILING : ROOM_FLOOR;
    }
    if(d.x >= d.z){
        return (p.x > 0.) ? ROOM_RIGHT : ROOM_LEFT;
    }
    return (p.z > 0.) ? ROOM_BACK : ROOM_FRONT;
}


//--- the objects, in declaration order (= containment priority, inner to outer)
const int ID_DODEC   = 0;
const int ID_COXCUBE = 1;
const int ID_KEY     = 2;
const int ID_ROOM    = 3;

const int N_OBJ = 4;
float gSDF[N_OBJ];


//--- placement and shape parameters ----------------------------------
const vec3 DODEC_P     = vec3(-3.0, 4.2, 0.0);
const vec3 DODEC_SCALE = vec3(3.2);

const vec3 COXCUBE_P     = vec3(3.0, 4.2, 0.0);
const vec3 COXCUBE_SCALE = vec3(3.2);

const vec3  KEY_P      = vec3(7.0, 15.0, 11.0);
const float KEY_RADIUS = 3.0;

const vec3 ROOM_P        = vec3(0.0, 11.0, 0.0);
const vec3 ROOM_HALFSIZE = vec3(15.0, 11.0, 28.0);


//---------------------------------------------------------------------
// the region sdfs
//---------------------------------------------------------------------

vec3 toLocal_dodec(vec3 p){
    return (p - DODEC_P) / DODEC_SCALE;
}

float sdf_dodec(vec3 p){
    float d = hypDodDistance(toLocal_dodec(p), coreRadius);
    return d * min(DODEC_SCALE.x, min(DODEC_SCALE.y, DODEC_SCALE.z));
}

vec3 toLocal_coxcube(vec3 p){
    return (p - COXCUBE_P) / COXCUBE_SCALE;
}

float sdf_coxcube(vec3 p){
    float d = hypCoxCubeDistance(toLocal_coxcube(p), dihedral, coreRadius);
    return d * min(COXCUBE_SCALE.x, min(COXCUBE_SCALE.y, COXCUBE_SCALE.z));
}

float sdf_key(vec3 p){
    return sphereDistance(p - KEY_P, KEY_RADIUS);
}

//the room SOLID is everything outside the box, so its interior is open air and
//regionAt() returns ID_NONE there
float sdf_room(vec3 p){
    return roomDistance(p - ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the normals — the 4-tap of each region's own sdf, in world coordinates
//---------------------------------------------------------------------
const float NRM_E = 0.0002;

Vector normal_dodec(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_dodec(p + k.xyy*NRM_E) + k.yyx*sdf_dodec(p + k.yyx*NRM_E)
                              + k.yxy*sdf_dodec(p + k.yxy*NRM_E) + k.xxx*sdf_dodec(p + k.xxx*NRM_E) ));
}

Vector normal_coxcube(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_coxcube(p + k.xyy*NRM_E) + k.yyx*sdf_coxcube(p + k.yyx*NRM_E)
                              + k.yxy*sdf_coxcube(p + k.yxy*NRM_E) + k.xxx*sdf_coxcube(p + k.xxx*NRM_E) ));
}

Vector normal_key(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_key(p + k.xyy*NRM_E) + k.yyx*sdf_key(p + k.yyx*NRM_E)
                              + k.yxy*sdf_key(p + k.yxy*NRM_E) + k.xxx*sdf_key(p + k.xxx*NRM_E) ));
}

Vector normal_room(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_room(p + k.xyy*NRM_E) + k.yyx*sdf_room(p + k.yyx*NRM_E)
                              + k.yxy*sdf_room(p + k.yxy*NRM_E) + k.xxx*sdf_room(p + k.xxx*NRM_E) ));
}


//---------------------------------------------------------------------
// the materials
//  material_ gives the Surface plus this object's own Medium; medium_ gives
//  only the Medium, for when the object is merely the far side
//---------------------------------------------------------------------

Material material_dodec(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //matte
    m.surf.diffuse = vec3(0.78, 0.74, 0.68);
    return m;
}
Medium   medium_dodec  (vec3 p){ return defaultMedium(); }

Material material_coxcube(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //matte
    m.surf.diffuse = vec3(0.78, 0.74, 0.68);
    return m;
}
Medium   medium_coxcube  (vec3 p){ return defaultMedium(); }

Material material_key(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //light
    m.surf.emit = 3800.0*vec3(0.9);
    return m;
}
Medium   medium_key  (vec3 p){ return defaultMedium(); }

Material material_room(vec3 p, inout Vector n){
    vec3 q = p - ROOM_P;
    int faceData = roomFaceData(q, ROOM_HALFSIZE);
    if(faceData == ROOM_CEILING){ return makeLight(vec3(1.0), roomLight); }
    if(faceData == ROOM_FLOOR)  { return makeGloss(floorColor, 0.0, wallRough); }
    if(faceData == ROOM_LEFT)   { return makeGloss(warmColor,  0.0, wallRough); }
    if(faceData == ROOM_RIGHT)  { return makeGloss(coolColor,  0.0, wallRough); }
    return makeGloss(wallColor, 0.0, wallRough);
}
Medium medium_room(vec3 p){ return defaultMedium(); }


//---------------------------------------------------------------------
// the analytic intersections
//---------------------------------------------------------------------

float trace_key(Vector tv){
    return sphereTrace(tv, KEY_P, KEY_RADIUS);
}

float trace_room(Vector tv){
    return roomTrace(tv, ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the dispatchers
//---------------------------------------------------------------------

void sdfAll(vec3 p){
    gSDF[ID_DODEC  ] = sdf_dodec(p);
    gSDF[ID_COXCUBE] = sdf_coxcube(p);
    gSDF[ID_KEY    ] = sdf_key(p);
    gSDF[ID_ROOM   ] = sdf_room(p);
}

Vector normalOf(int id, vec3 p){
    if(id == ID_DODEC  ){ return normal_dodec(p); }
    if(id == ID_COXCUBE){ return normal_coxcube(p); }
    if(id == ID_KEY    ){ return normal_key(p); }
    return normal_room(p);
}

//no sheets in this scene: every object is a region with an interior
bool isSheet(int id){ return false; }

Material materialOf(int id, vec3 p, inout Vector n, bool front){
    if(id == ID_DODEC  ){ return material_dodec(p, n); }
    if(id == ID_COXCUBE){ return material_coxcube(p, n); }
    if(id == ID_KEY    ){ return material_key(p, n); }
    return material_room(p, n);
}

Medium mediumOf(int id, vec3 p){
    if(id == ID_DODEC  ){ return medium_dodec(p); }
    if(id == ID_COXCUBE){ return medium_coxcube(p); }
    if(id == ID_KEY    ){ return medium_key(p); }
    if(id == ID_ROOM   ){ return medium_room(p); }
    return defaultMedium();      //ID_NONE: open air
}


//---------------------------------------------------------------------
// the entry points
//---------------------------------------------------------------------

void buildScene(){}

float sdf_Scene(Vector tv){
    vec3 p = tv.pos;
    float d = maxDist;

    d = min(d, sdf_dodec(p));

    d = min(d, sdf_coxcube(p));

    return d;
}

float trace_Scene(Vector tv){
    float d = maxDist;
    d = min(d, trace_key(tv));
    d = min(d, trace_room(tv));
    return d;
}
