//=====================================================================
// generated by scenegen from src/scene.js — do not edit by hand
//=====================================================================


//--- library: glsl/shapes/models/kleinBottle.glsl ---
//----------------------------------------------------------------------------
// KLEIN BOTTLE — the figure-8 immersion, as a hollow surface of wall thickness
// `thickness`, overall scale `size`. After shadertoy 4ltSW8.
//
// Assembled from four pieces, unioned: a SIDE HANDLE (a stretched cylinder about
// xz), a LOWER BASE (half a torus, forming the open mouth), a MID BASE (a
// stretched torus), and an UPPER HANDLE (half a torus about xy, cut off at a
// fixed height). Each is hollowed by the same `abs(...) - thickness` shell trick,
// so the result is a surface with a wall rather than a solid.
//
// The pieces are shaped by `y`, a squared sine of height, which is what tapers
// the handle and the mid base together so they meet without a seam.
//
// glsl/shapes/ is the math-only library: plain functions of a point and floats.
//----------------------------------------------------------------------------


//the bottle at unit scale (file-private). `thickness` is the wall half-width.
float kleinBottle_sd(vec3 p, float thickness){
    float d = maxDist;

    p.y += 0.5;
    p.xy *= rot2(PI/2.);

    vec3  q = p + vec3(1. - cos((1. - p.y)/3.*PI), 0, 0);
    float y = pow(sin((1. - p.y)/3.*PI/2.), 2.);

    // SIDE HANDLE (stretched xz cylinder), hollowed
    float sideHandle = max(max(abs(length(q.xz) - 0.5 + 0.25*y) - thickness, q.y - 1.0), -q.y - 2.0);
    d = min(d, sideHandle);

    // LOWER BASE: the opening (half an xz torus)
    q = p - vec3(0, 1, 0);
    float lowerBase = max(abs(length(vec2(length(q.xz) - 1.0, q.y)) - 0.5) - thickness, -q.y);
    d = min(d, lowerBase);

    // MID BASE (stretched xz torus)
    q = p;
    float midBase = max(max(abs(length(q.xz) - 1.5 + 1.25*y), q.y - 1.0), -q.y - 2.0) - thickness;
    d = min(d, midBase);

    // UPPER HANDLE (half an xy torus), cut off at a fixed height
    q = p + vec3(1, 2, 0);
    float upperHandle = abs(length(vec2(length(q.xy) - 1.0, q.z)) - 0.25) - thickness;
    upperHandle = max(upperHandle, q.y);
    d = min(d, upperHandle);

    return 0.8*d;
}


// p is in the bottle's own coordinates. The axis permutation is baked into the
// shape (it is how the immersion is oriented), not a placement choice.
// `thickness` is RELATIVE — a fraction of the unit bottle — so it scales with
// size rather than fighting it. 0.05 is a good wall.
//
// FIXED IN THE PORT: the legacy divided p by size but never scaled the returned
// distance back, so for size < 1 it overestimated distance and the marcher could
// tunnel. Its only scene used size = 1.0, where every scaling is the identity,
// so the bug was never exercised — this is byte-identical there and correct
// elsewhere.
float kleinBottleDistance(vec3 p, float size, float thickness){
    vec3 q = vec3(-p.y, p.z, p.x)/size;
    return size*kleinBottle_sd(q, thickness);
}


// bounding sphere: the bottle lies within radius 5.9 at unit scale, and the axis
// permutation preserves length
float kleinBottleBound(vec3 p, float size){
    return length(p) - 5.9*size;
}


//--- library: glsl/shapes/environments/room.glsl ---
//----------------------------------------------------------------------------
// ROOM — a closed box, seen from the inside.
//
// The room is ONE region whose solid is everything OUTSIDE the box, so the
// interior is open air and regionAt() returns ID_NONE there. Its six walls are
// not six objects: they are a material FIELD over that one region, read off by
// asking which face a point is nearest. roomFace() answers that.
//
// glsl/shapes/ is the math-only library: plain functions of a point and some
// floats. No structs, no Frame, no Material.
//----------------------------------------------------------------------------


const int ROOM_FLOOR   = 0;
const int ROOM_CEILING = 1;
const int ROOM_LEFT    = 2;
const int ROOM_RIGHT   = 3;
const int ROOM_FRONT   = 4;
const int ROOM_BACK    = 5;


// p is in the room's own coordinates (origin at the box centre).
// Negative in the WALLS, positive in the open interior — the sign convention
// every other region uses, just turned inside out.
float roomDistance(vec3 p, vec3 halfSize){
    return -boxDistance(p, halfSize);
}


// Exact ray intersection, in world coordinates. The ray is inside the box, so
// this is simply the distance at which it leaves: the nearest of the three
// far slab crossings.
float roomTrace(Vector tv, vec3 centre, vec3 halfSize){
    vec3  o  = tv.pos - centre;
    vec3  tm = max((-halfSize - o)/tv.dir, (halfSize - o)/tv.dir);
    float t  = min(tm.x, min(tm.y, tm.z));
    if(t < 0.){ return maxDist; }
    return min(t, maxDist);
}


// Which wall p is on (or nearest to) — a shape DATA output (docs/shape-data.md):
// a material that reads `faceData` gets it injected. d is negative inside the
// room, so its LARGEST component names the axis the point is closest to leaving
// through, and the sign of p picks which of that axis's two faces.
int roomFaceData(vec3 p, vec3 halfSize){
    vec3 d = abs(p) - halfSize;

    if(d.y >= d.x && d.y >= d.z){
        return (p.y > 0.) ? ROOM_CEILING : ROOM_FLOOR;
    }
    if(d.x >= d.z){
        return (p.x > 0.) ? ROOM_RIGHT : ROOM_LEFT;
    }
    return (p.z > 0.) ? ROOM_BACK : ROOM_FRONT;
}


//--- the objects, in declaration order (= containment priority, inner to outer)
const int ID_KLEIN = 0;
const int ID_KEY   = 1;
const int ID_ROOM  = 2;

const int N_OBJ = 3;
float gSDF[N_OBJ];


//--- placement and shape parameters ----------------------------------
const vec3 KLEIN_P    = vec3(-1.4, 3.0, 0.0);
const vec3 KLEIN_AXIS = vec3(0.0, 1.0, 0.0);

const vec3  KEY_P      = vec3(7.0, 13.0, 10.0);
const float KEY_RADIUS = 3.0;

const vec3 ROOM_P        = vec3(0.0, 10.0, 0.0);
const vec3 ROOM_HALFSIZE = vec3(14.0, 10.0, 22.0);


//---------------------------------------------------------------------
// the region sdfs
//---------------------------------------------------------------------

vec3 toLocal_klein(vec3 p){
    mat3 rot = rot3AxisAngle(normalize(KLEIN_AXIS), 60.0);
    return (p - KLEIN_P) * rot;
}

float sdf_klein(vec3 p){
    float d = kleinBottleDistance(toLocal_klein(p), bottleSize, wallThick);
    return d;
}

float sdf_key(vec3 p){
    return sphereDistance(p - KEY_P, KEY_RADIUS);
}

//the room SOLID is everything outside the box, so its interior is open air and
//regionAt() returns ID_NONE there
float sdf_room(vec3 p){
    return roomDistance(p - ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the normals — the 4-tap of each region's own sdf, in world coordinates
//---------------------------------------------------------------------
const float NRM_E = 0.0002;

Vector normal_klein(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_klein(p + k.xyy*NRM_E) + k.yyx*sdf_klein(p + k.yyx*NRM_E)
                              + k.yxy*sdf_klein(p + k.yxy*NRM_E) + k.xxx*sdf_klein(p + k.xxx*NRM_E) ));
}

Vector normal_key(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_key(p + k.xyy*NRM_E) + k.yyx*sdf_key(p + k.yyx*NRM_E)
                              + k.yxy*sdf_key(p + k.yxy*NRM_E) + k.xxx*sdf_key(p + k.xxx*NRM_E) ));
}

Vector normal_room(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_room(p + k.xyy*NRM_E) + k.yyx*sdf_room(p + k.yyx*NRM_E)
                              + k.yxy*sdf_room(p + k.yxy*NRM_E) + k.xxx*sdf_room(p + k.xxx*NRM_E) ));
}


//---------------------------------------------------------------------
// the materials
//  material_ gives the Surface plus this object's own Medium; medium_ gives
//  only the Medium, for when the object is merely the far side
//---------------------------------------------------------------------

Material material_klein(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //matte
    m.surf.diffuse = vec3(0.8, 0.74, 0.64);
    return m;
}
Medium   medium_klein  (vec3 p){ return defaultMedium(); }

Material material_key(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //light
    m.surf.emit = 3200.0*vec3(0.9);
    return m;
}
Medium   medium_key  (vec3 p){ return defaultMedium(); }

Material material_room(vec3 p, inout Vector n){
    vec3 q = p - ROOM_P;
    int faceData = roomFaceData(q, ROOM_HALFSIZE);
    if(faceData == ROOM_CEILING){ return makeLight(vec3(1.0), roomLight); }
    if(faceData == ROOM_FLOOR)  { return makeGloss(floorColor, 0.0, wallRough); }
    if(faceData == ROOM_LEFT)   { return makeGloss(warmColor,  0.0, wallRough); }
    if(faceData == ROOM_RIGHT)  { return makeGloss(coolColor,  0.0, wallRough); }
    return makeGloss(wallColor, 0.0, wallRough);
}
Medium medium_room(vec3 p){ return defaultMedium(); }


//---------------------------------------------------------------------
// the analytic intersections
//---------------------------------------------------------------------

float trace_key(Vector tv){
    return sphereTrace(tv, KEY_P, KEY_RADIUS);
}

float trace_room(Vector tv){
    return roomTrace(tv, ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the dispatchers
//---------------------------------------------------------------------

void sdfAll(vec3 p){
    gSDF[ID_KLEIN] = sdf_klein(p);
    gSDF[ID_KEY  ] = sdf_key(p);
    gSDF[ID_ROOM ] = sdf_room(p);
}

Vector normalOf(int id, vec3 p){
    if(id == ID_KLEIN){ return normal_klein(p); }
    if(id == ID_KEY  ){ return normal_key(p); }
    return normal_room(p);
}

//no sheets in this scene: every object is a region with an interior
bool isSheet(int id){ return false; }

Material materialOf(int id, vec3 p, inout Vector n, bool front){
    if(id == ID_KLEIN){ return material_klein(p, n); }
    if(id == ID_KEY  ){ return material_key(p, n); }
    return material_room(p, n);
}

Medium mediumOf(int id, vec3 p){
    if(id == ID_KLEIN){ return medium_klein(p); }
    if(id == ID_KEY  ){ return medium_key(p); }
    if(id == ID_ROOM ){ return medium_room(p); }
    return defaultMedium();      //ID_NONE: open air
}


//---------------------------------------------------------------------
// the entry points
//---------------------------------------------------------------------

void buildScene(){}

float sdf_Scene(Vector tv){
    vec3 p = tv.pos;
    float d = maxDist;

    d = min(d, sdf_klein(p));

    return d;
}

float trace_Scene(Vector tv){
    float d = maxDist;
    d = min(d, trace_key(tv));
    d = min(d, trace_room(tv));
    return d;
}
