//=====================================================================
// generated by scenegen from src/scene.js — do not edit by hand
//=====================================================================


//--- library: glsl/shapes/environments/room.glsl ---
//----------------------------------------------------------------------------
// ROOM — a closed box, seen from the inside.
//
// The room is ONE region whose solid is everything OUTSIDE the box, so the
// interior is open air and regionAt() returns ID_NONE there. Its six walls are
// not six objects: they are a material FIELD over that one region, read off by
// asking which face a point is nearest. roomFace() answers that.
//
// glsl/shapes/ is the math-only library: plain functions of a point and some
// floats. No structs, no Frame, no Material.
//----------------------------------------------------------------------------


const int ROOM_FLOOR   = 0;
const int ROOM_CEILING = 1;
const int ROOM_LEFT    = 2;
const int ROOM_RIGHT   = 3;
const int ROOM_FRONT   = 4;
const int ROOM_BACK    = 5;


// p is in the room's own coordinates (origin at the box centre).
// Negative in the WALLS, positive in the open interior — the sign convention
// every other region uses, just turned inside out.
float roomDistance(vec3 p, vec3 halfSize){
    return -boxDistance(p, halfSize);
}


// Exact ray intersection, in world coordinates. Inside the box this is simply
// the distance at which the ray leaves: the nearest of the three far slab
// crossings. A camera may also sit OUTSIDE (behind the see-through fourth wall,
// as about half the scenes do): then the far crossing is only a wall if the ray
// actually passes through the box; a ray that misses it sees the sky, rather
// than landing on a point that is on no wall (nothing claims it).
float roomTrace(Vector tv, vec3 centre, vec3 halfSize){
    vec3  o  = tv.pos - centre;
    vec3  t0 = (-halfSize - o)/tv.dir;
    vec3  t1 = ( halfSize - o)/tv.dir;
    vec3  tm = max(t0, t1);
    vec3  tn = min(t0, t1);
    float t  = min(tm.x, min(tm.y, tm.z));
    if(t < 0. || max(tn.x, max(tn.y, tn.z)) > t){ return maxDist; }
    return min(t, maxDist);
}


// Which wall p is on (or nearest to) — a shape DATA output (docs/shape-data.md):
// a material that reads `faceData` gets it injected. d is negative inside the
// room, so its LARGEST component names the axis the point is closest to leaving
// through, and the sign of p picks which of that axis's two faces.
int roomFaceData(vec3 p, vec3 halfSize){
    vec3 d = abs(p) - halfSize;

    if(d.y >= d.x && d.y >= d.z){
        return (p.y > 0.) ? ROOM_CEILING : ROOM_FLOOR;
    }
    if(d.x >= d.z){
        return (p.x > 0.) ? ROOM_RIGHT : ROOM_LEFT;
    }
    return (p.z > 0.) ? ROOM_BACK : ROOM_FRONT;
}


//--- the objects, in declaration order (= containment priority, inner to outer)
const int ID_BALL0 = 0;
const int ID_BALL1 = 1;
const int ID_BALL2 = 2;
const int ID_BALL3 = 3;
const int ID_BALL4 = 4;
const int ID_BALL5 = 5;
const int ID_BALL6 = 6;
const int ID_DEEP0 = 7;
const int ID_DEEP1 = 8;
const int ID_DEEP2 = 9;
const int ID_DEEP3 = 10;
const int ID_FLOOR = 11;
const int ID_KEY   = 12;
const int ID_ROOM  = 13;

const int N_OBJ = 14;
float gSDF[N_OBJ];


//--- placement and shape parameters ----------------------------------
const vec3  BALL0_P      = vec3(-7.2, 0.7, -6.0);
const float BALL0_RADIUS = 0.7;

const vec3  BALL1_P      = vec3(-4.8, 0.7, -6.0);
const float BALL1_RADIUS = 0.7;

const vec3  BALL2_P      = vec3(-2.4, 0.7, -6.0);
const float BALL2_RADIUS = 0.7;

const vec3  BALL3_P      = vec3(0.0, 0.7, -6.0);
const float BALL3_RADIUS = 0.7;

const vec3  BALL4_P      = vec3(2.4, 0.7, -6.0);
const float BALL4_RADIUS = 0.7;

const vec3  BALL5_P      = vec3(4.8, 0.7, -6.0);
const float BALL5_RADIUS = 0.7;

const vec3  BALL6_P      = vec3(7.2, 0.7, -6.0);
const float BALL6_RADIUS = 0.7;

const vec3  DEEP0_P      = vec3(-1.2, 0.5, 3.0);
const float DEEP0_RADIUS = 0.5;

const vec3  DEEP1_P      = vec3(1.2, 0.5, -1.5);
const float DEEP1_RADIUS = 0.5;

const vec3  DEEP2_P      = vec3(-1.2, 0.5, -11.0);
const float DEEP2_RADIUS = 0.5;

const vec3  DEEP3_P      = vec3(1.2, 0.5, -16.0);
const float DEEP3_RADIUS = 0.5;

const vec3 FLOOR_P        = vec3(0.0, -0.049, -6.0);
const vec3 FLOOR_HALFSIZE = vec3(16.0, 0.05, 22.0);

const vec3  KEY_P      = vec3(-6.0, 10.0, 4.0);
const float KEY_RADIUS = 1.5;

const vec3 ROOM_P        = vec3(0.0, 8.0, -6.0);
const vec3 ROOM_HALFSIZE = vec3(16.0, 8.0, 22.0);


//---------------------------------------------------------------------
// the region sdfs
//---------------------------------------------------------------------

float sdf_ball0(vec3 p){
    return sphereDistance(p - BALL0_P, BALL0_RADIUS);
}

float sdf_ball1(vec3 p){
    return sphereDistance(p - BALL1_P, BALL1_RADIUS);
}

float sdf_ball2(vec3 p){
    return sphereDistance(p - BALL2_P, BALL2_RADIUS);
}

float sdf_ball3(vec3 p){
    return sphereDistance(p - BALL3_P, BALL3_RADIUS);
}

float sdf_ball4(vec3 p){
    return sphereDistance(p - BALL4_P, BALL4_RADIUS);
}

float sdf_ball5(vec3 p){
    return sphereDistance(p - BALL5_P, BALL5_RADIUS);
}

float sdf_ball6(vec3 p){
    return sphereDistance(p - BALL6_P, BALL6_RADIUS);
}

float sdf_deep0(vec3 p){
    return sphereDistance(p - DEEP0_P, DEEP0_RADIUS);
}

float sdf_deep1(vec3 p){
    return sphereDistance(p - DEEP1_P, DEEP1_RADIUS);
}

float sdf_deep2(vec3 p){
    return sphereDistance(p - DEEP2_P, DEEP2_RADIUS);
}

float sdf_deep3(vec3 p){
    return sphereDistance(p - DEEP3_P, DEEP3_RADIUS);
}

float sdf_floor(vec3 p){
    return boxDistance(p - FLOOR_P, FLOOR_HALFSIZE);
}

float sdf_key(vec3 p){
    return sphereDistance(p - KEY_P, KEY_RADIUS);
}

//the room SOLID is everything outside the box, so its interior is open air and
//regionAt() returns ID_NONE there
float sdf_room(vec3 p){
    return roomDistance(p - ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the normals — the 4-tap of each region's own sdf, in world coordinates
//---------------------------------------------------------------------
const float NRM_E = 0.0002;

Vector normal_ball0(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_ball0(p + k.xyy*NRM_E) + k.yyx*sdf_ball0(p + k.yyx*NRM_E)
                              + k.yxy*sdf_ball0(p + k.yxy*NRM_E) + k.xxx*sdf_ball0(p + k.xxx*NRM_E) ));
}

Vector normal_ball1(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_ball1(p + k.xyy*NRM_E) + k.yyx*sdf_ball1(p + k.yyx*NRM_E)
                              + k.yxy*sdf_ball1(p + k.yxy*NRM_E) + k.xxx*sdf_ball1(p + k.xxx*NRM_E) ));
}

Vector normal_ball2(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_ball2(p + k.xyy*NRM_E) + k.yyx*sdf_ball2(p + k.yyx*NRM_E)
                              + k.yxy*sdf_ball2(p + k.yxy*NRM_E) + k.xxx*sdf_ball2(p + k.xxx*NRM_E) ));
}

Vector normal_ball3(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_ball3(p + k.xyy*NRM_E) + k.yyx*sdf_ball3(p + k.yyx*NRM_E)
                              + k.yxy*sdf_ball3(p + k.yxy*NRM_E) + k.xxx*sdf_ball3(p + k.xxx*NRM_E) ));
}

Vector normal_ball4(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_ball4(p + k.xyy*NRM_E) + k.yyx*sdf_ball4(p + k.yyx*NRM_E)
                              + k.yxy*sdf_ball4(p + k.yxy*NRM_E) + k.xxx*sdf_ball4(p + k.xxx*NRM_E) ));
}

Vector normal_ball5(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_ball5(p + k.xyy*NRM_E) + k.yyx*sdf_ball5(p + k.yyx*NRM_E)
                              + k.yxy*sdf_ball5(p + k.yxy*NRM_E) + k.xxx*sdf_ball5(p + k.xxx*NRM_E) ));
}

Vector normal_ball6(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_ball6(p + k.xyy*NRM_E) + k.yyx*sdf_ball6(p + k.yyx*NRM_E)
                              + k.yxy*sdf_ball6(p + k.yxy*NRM_E) + k.xxx*sdf_ball6(p + k.xxx*NRM_E) ));
}

Vector normal_deep0(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_deep0(p + k.xyy*NRM_E) + k.yyx*sdf_deep0(p + k.yyx*NRM_E)
                              + k.yxy*sdf_deep0(p + k.yxy*NRM_E) + k.xxx*sdf_deep0(p + k.xxx*NRM_E) ));
}

Vector normal_deep1(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_deep1(p + k.xyy*NRM_E) + k.yyx*sdf_deep1(p + k.yyx*NRM_E)
                              + k.yxy*sdf_deep1(p + k.yxy*NRM_E) + k.xxx*sdf_deep1(p + k.xxx*NRM_E) ));
}

Vector normal_deep2(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_deep2(p + k.xyy*NRM_E) + k.yyx*sdf_deep2(p + k.yyx*NRM_E)
                              + k.yxy*sdf_deep2(p + k.yxy*NRM_E) + k.xxx*sdf_deep2(p + k.xxx*NRM_E) ));
}

Vector normal_deep3(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_deep3(p + k.xyy*NRM_E) + k.yyx*sdf_deep3(p + k.yyx*NRM_E)
                              + k.yxy*sdf_deep3(p + k.yxy*NRM_E) + k.xxx*sdf_deep3(p + k.xxx*NRM_E) ));
}

Vector normal_floor(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_floor(p + k.xyy*NRM_E) + k.yyx*sdf_floor(p + k.yyx*NRM_E)
                              + k.yxy*sdf_floor(p + k.yxy*NRM_E) + k.xxx*sdf_floor(p + k.xxx*NRM_E) ));
}

Vector normal_key(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_key(p + k.xyy*NRM_E) + k.yyx*sdf_key(p + k.yyx*NRM_E)
                              + k.yxy*sdf_key(p + k.yxy*NRM_E) + k.xxx*sdf_key(p + k.xxx*NRM_E) ));
}

Vector normal_room(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_room(p + k.xyy*NRM_E) + k.yyx*sdf_room(p + k.yyx*NRM_E)
                              + k.yxy*sdf_room(p + k.yxy*NRM_E) + k.xxx*sdf_room(p + k.xxx*NRM_E) ));
}


//---------------------------------------------------------------------
// the materials
//  material_ gives the Surface plus this object's own Medium; medium_ gives
//  only the Medium, for when the object is merely the far side
//---------------------------------------------------------------------

Material material_ball0(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //gloss
    m.surf.diffuse   = vec3(0.75, 0.25, 0.2);
    m.surf.roughness = 0.2;
    m.surf.gloss     = 0.04;
    return m;
}
Medium   medium_ball0  (vec3 p){ return defaultMedium(); }

Material material_ball1(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //gloss
    m.surf.diffuse   = vec3(0.8, 0.55, 0.2);
    m.surf.roughness = 0.2;
    m.surf.gloss     = 0.04;
    return m;
}
Medium   medium_ball1  (vec3 p){ return defaultMedium(); }

Material material_ball2(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //gloss
    m.surf.diffuse   = vec3(0.75, 0.7, 0.25);
    m.surf.roughness = 0.2;
    m.surf.gloss     = 0.04;
    return m;
}
Medium   medium_ball2  (vec3 p){ return defaultMedium(); }

Material material_ball3(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //gloss
    m.surf.diffuse   = vec3(0.35, 0.65, 0.3);
    m.surf.roughness = 0.2;
    m.surf.gloss     = 0.04;
    return m;
}
Medium   medium_ball3  (vec3 p){ return defaultMedium(); }

Material material_ball4(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //gloss
    m.surf.diffuse   = vec3(0.25, 0.55, 0.7);
    m.surf.roughness = 0.2;
    m.surf.gloss     = 0.04;
    return m;
}
Medium   medium_ball4  (vec3 p){ return defaultMedium(); }

Material material_ball5(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //gloss
    m.surf.diffuse   = vec3(0.35, 0.35, 0.75);
    m.surf.roughness = 0.2;
    m.surf.gloss     = 0.04;
    return m;
}
Medium   medium_ball5  (vec3 p){ return defaultMedium(); }

Material material_ball6(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //gloss
    m.surf.diffuse   = vec3(0.6, 0.3, 0.65);
    m.surf.roughness = 0.2;
    m.surf.gloss     = 0.04;
    return m;
}
Medium   medium_ball6  (vec3 p){ return defaultMedium(); }

Material material_deep0(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //gloss
    m.surf.diffuse   = vec3(0.85, 0.85, 0.82);
    m.surf.roughness = 0.2;
    m.surf.gloss     = 0.04;
    return m;
}
Medium   medium_deep0  (vec3 p){ return defaultMedium(); }

Material material_deep1(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //gloss
    m.surf.diffuse   = vec3(0.85, 0.85, 0.82);
    m.surf.roughness = 0.2;
    m.surf.gloss     = 0.04;
    return m;
}
Medium   medium_deep1  (vec3 p){ return defaultMedium(); }

Material material_deep2(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //gloss
    m.surf.diffuse   = vec3(0.85, 0.85, 0.82);
    m.surf.roughness = 0.2;
    m.surf.gloss     = 0.04;
    return m;
}
Medium   medium_deep2  (vec3 p){ return defaultMedium(); }

Material material_deep3(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //gloss
    m.surf.diffuse   = vec3(0.85, 0.85, 0.82);
    m.surf.roughness = 0.2;
    m.surf.gloss     = 0.04;
    return m;
}
Medium   medium_deep3  (vec3 p){ return defaultMedium(); }

Material material_floor(vec3 p, inout Vector n){
    vec3 q = p - FLOOR_P;
    return makeMatte(mod(floor(q.x) + floor(q.z), 2.0) < 1.0 ? vec3(0.7) : vec3(0.1));
}
Medium medium_floor(vec3 p){ return defaultMedium(); }

Material material_key(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //light
    m.surf.emit = 160.0*vec3(0.9);
    return m;
}
Medium   medium_key  (vec3 p){ return defaultMedium(); }

Material material_room(vec3 p, inout Vector n){
    vec3 q = p - ROOM_P;
    int faceData = roomFaceData(q, ROOM_HALFSIZE);
    if(faceData == ROOM_CEILING){ return makeLight(vec3(1.0), roomLight); }
    if(faceData == ROOM_FLOOR)  { return makeMatte(floorColor); }
    if(faceData == ROOM_LEFT)   { return makeMatte(warmColor); }
    if(faceData == ROOM_RIGHT)  { return makeMatte(coolColor); }
    return makeMatte(wallColor);
}
Medium medium_room(vec3 p){ return defaultMedium(); }


//---------------------------------------------------------------------
// the analytic intersections
//---------------------------------------------------------------------

float trace_ball0(Vector tv){
    return sphereTrace(tv, BALL0_P, BALL0_RADIUS);
}

float trace_ball1(Vector tv){
    return sphereTrace(tv, BALL1_P, BALL1_RADIUS);
}

float trace_ball2(Vector tv){
    return sphereTrace(tv, BALL2_P, BALL2_RADIUS);
}

float trace_ball3(Vector tv){
    return sphereTrace(tv, BALL3_P, BALL3_RADIUS);
}

float trace_ball4(Vector tv){
    return sphereTrace(tv, BALL4_P, BALL4_RADIUS);
}

float trace_ball5(Vector tv){
    return sphereTrace(tv, BALL5_P, BALL5_RADIUS);
}

float trace_ball6(Vector tv){
    return sphereTrace(tv, BALL6_P, BALL6_RADIUS);
}

float trace_deep0(Vector tv){
    return sphereTrace(tv, DEEP0_P, DEEP0_RADIUS);
}

float trace_deep1(Vector tv){
    return sphereTrace(tv, DEEP1_P, DEEP1_RADIUS);
}

float trace_deep2(Vector tv){
    return sphereTrace(tv, DEEP2_P, DEEP2_RADIUS);
}

float trace_deep3(Vector tv){
    return sphereTrace(tv, DEEP3_P, DEEP3_RADIUS);
}

float trace_floor(Vector tv){
    return boxTrace(tv, FLOOR_P, FLOOR_HALFSIZE);
}

float trace_key(Vector tv){
    return sphereTrace(tv, KEY_P, KEY_RADIUS);
}

float trace_room(Vector tv){
    return roomTrace(tv, ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the dispatchers
//---------------------------------------------------------------------

void sdfAll(vec3 p){
    gSDF[ID_BALL0] = sdf_ball0(p);
    gSDF[ID_BALL1] = sdf_ball1(p);
    gSDF[ID_BALL2] = sdf_ball2(p);
    gSDF[ID_BALL3] = sdf_ball3(p);
    gSDF[ID_BALL4] = sdf_ball4(p);
    gSDF[ID_BALL5] = sdf_ball5(p);
    gSDF[ID_BALL6] = sdf_ball6(p);
    gSDF[ID_DEEP0] = sdf_deep0(p);
    gSDF[ID_DEEP1] = sdf_deep1(p);
    gSDF[ID_DEEP2] = sdf_deep2(p);
    gSDF[ID_DEEP3] = sdf_deep3(p);
    gSDF[ID_FLOOR] = sdf_floor(p);
    gSDF[ID_KEY  ] = sdf_key(p);
    gSDF[ID_ROOM ] = sdf_room(p);
}

Vector normalOf(int id, vec3 p){
    if(id == ID_BALL0){ return normal_ball0(p); }
    if(id == ID_BALL1){ return normal_ball1(p); }
    if(id == ID_BALL2){ return normal_ball2(p); }
    if(id == ID_BALL3){ return normal_ball3(p); }
    if(id == ID_BALL4){ return normal_ball4(p); }
    if(id == ID_BALL5){ return normal_ball5(p); }
    if(id == ID_BALL6){ return normal_ball6(p); }
    if(id == ID_DEEP0){ return normal_deep0(p); }
    if(id == ID_DEEP1){ return normal_deep1(p); }
    if(id == ID_DEEP2){ return normal_deep2(p); }
    if(id == ID_DEEP3){ return normal_deep3(p); }
    if(id == ID_FLOOR){ return normal_floor(p); }
    if(id == ID_KEY  ){ return normal_key(p); }
    return normal_room(p);
}

//no sheets in this scene: every object is a region with an interior
bool isSheet(int id){ return false; }

Material materialOf(int id, vec3 p, inout Vector n, bool front){
    if(id == ID_BALL0){ return material_ball0(p, n); }
    if(id == ID_BALL1){ return material_ball1(p, n); }
    if(id == ID_BALL2){ return material_ball2(p, n); }
    if(id == ID_BALL3){ return material_ball3(p, n); }
    if(id == ID_BALL4){ return material_ball4(p, n); }
    if(id == ID_BALL5){ return material_ball5(p, n); }
    if(id == ID_BALL6){ return material_ball6(p, n); }
    if(id == ID_DEEP0){ return material_deep0(p, n); }
    if(id == ID_DEEP1){ return material_deep1(p, n); }
    if(id == ID_DEEP2){ return material_deep2(p, n); }
    if(id == ID_DEEP3){ return material_deep3(p, n); }
    if(id == ID_FLOOR){ return material_floor(p, n); }
    if(id == ID_KEY  ){ return material_key(p, n); }
    return material_room(p, n);
}

Medium mediumOf(int id, vec3 p){
    if(id == ID_BALL0){ return medium_ball0(p); }
    if(id == ID_BALL1){ return medium_ball1(p); }
    if(id == ID_BALL2){ return medium_ball2(p); }
    if(id == ID_BALL3){ return medium_ball3(p); }
    if(id == ID_BALL4){ return medium_ball4(p); }
    if(id == ID_BALL5){ return medium_ball5(p); }
    if(id == ID_BALL6){ return medium_ball6(p); }
    if(id == ID_DEEP0){ return medium_deep0(p); }
    if(id == ID_DEEP1){ return medium_deep1(p); }
    if(id == ID_DEEP2){ return medium_deep2(p); }
    if(id == ID_DEEP3){ return medium_deep3(p); }
    if(id == ID_FLOOR){ return medium_floor(p); }
    if(id == ID_KEY  ){ return medium_key(p); }
    if(id == ID_ROOM ){ return medium_room(p); }
    return defaultMedium();      //ID_NONE: open air
}


//---------------------------------------------------------------------
// the entry points
//---------------------------------------------------------------------

void buildScene(){}

//nothing marches: every surface here has a closed-form intersection
float sdf_Scene(Vector tv){
    return maxDist;
}

float trace_Scene(Vector tv){
    float d = maxDist;
    d = min(d, trace_ball0(tv));
    d = min(d, trace_ball1(tv));
    d = min(d, trace_ball2(tv));
    d = min(d, trace_ball3(tv));
    d = min(d, trace_ball4(tv));
    d = min(d, trace_ball5(tv));
    d = min(d, trace_ball6(tv));
    d = min(d, trace_deep0(tv));
    d = min(d, trace_deep1(tv));
    d = min(d, trace_deep2(tv));
    d = min(d, trace_deep3(tv));
    d = min(d, trace_floor(tv));
    d = min(d, trace_key(tv));
    d = min(d, trace_room(tv));
    return d;
}


//---------------------------------------------------------------------
// the lights — emissive spheres a diffuse bounce may aim at (aimLights.glsl)
//---------------------------------------------------------------------

int numLights(){ return 1; }

void lightSphere(int i, out vec3 c, out float r){
    c = KEY_P; r = KEY_RADIUS;
}
