//=====================================================================
// generated by scenegen from src/scene.js — do not edit by hand
//=====================================================================


//--- library: glsl/shapes/sphere.glsl ---
//----------------------------------------------------------------------------
// SPHERE
//
// glsl/shapes/ is the math-only library: plain functions of a point and some
// floats. No structs, no Frame, no Material, no at()/inside()/setData().
// Placement, materials and the region interface are emitted by the scene.
//----------------------------------------------------------------------------


// p is in the sphere's own coordinates (origin at the centre)
float sphereDistance(vec3 p, float radius){
    return length(p) - radius;
}


// Exact ray intersection, in world coordinates: the distance along tv to the
// sphere, or maxDist if it is not in front of us. tv.dir is unit length.
//
// A ray STARTING INSIDE takes the far root — glass needs that, since a
// transmitted ray has to find the far wall of the object it just entered.
float sphereTrace(Vector tv, vec3 centre, float radius){
    vec3  oc = tv.pos - centre;
    float b  = dot(oc, tv.dir);
    float c  = dot(oc, oc) - radius*radius;
    float disc = b*b - c;
    if(disc < 0.){ return maxDist; }

    float s = sqrt(disc);
    float t = -b - s;
    if(t < 0.){ t = -b + s; }
    if(t < 0.){ return maxDist; }
    return min(t, maxDist);
}


//--- library: glsl/shapes/plane.glsl ---
//----------------------------------------------------------------------------
// PLANE — a half-space, seen from the side its normal points toward.
//
// Exact and analytic, so a ray never marches toward it — worth having, since
// the marched step is the PERPENDICULAR distance, which crawls on a ray running
// nearly parallel to the plane, and a ground plane is used at exactly that angle.
//
// CAVEAT, learned the hard way: an analytic plane is NOT a drop-in replacement
// for a floor term inside a fractal's own DE. Folding `min(p.z - h, dFractal)`
// into the estimator makes the floor CAP the fractal — it hides everything
// below it. Split that floor out into a plane object and rays fall straight
// through into the infinitely fine detail underneath, and the plane is never
// reached. Use this for a floor the scene genuinely owns.
//
// glsl/shapes/ is the math-only library: plain functions of a point and some
// floats. No structs, no Frame, no Material.
//----------------------------------------------------------------------------


// p is in the plane's own coordinates (origin ON the plane). Negative in the
// solid half-space behind it, positive in the open half-space it faces.
float planeDistance(vec3 p, vec3 normal){
    return dot(p, normal);
}


// Exact ray intersection, in world coordinates: the distance along tv to the
// plane, or maxDist if it is not in front of us. A ray running away from the
// plane, or parallel to it, never meets it — and costs nothing to find out.
float planeTrace(Vector tv, vec3 centre, vec3 normal){
    float dn = dot(tv.dir, normal);
    if(abs(dn) < 1.0e-9){ return maxDist; }     //parallel
    float t = -dot(tv.pos - centre, normal)/dn;
    if(t < 0.){ return maxDist; }
    return min(t, maxDist);
}


//--- library: glsl/shapes/gem.glsl ---
//----------------------------------------------------------------------------
// GEM — a brilliant-ish cut stone, girdle radius `size`.
//
// 8 crown facets rising to an octagonal table, 8 pavilion facets falling to the
// culet point, offset half a sector so the rings alternate (the classic
// brilliant look), plus an octagonal girdle band. Built as an exact convex
// intersection of planes: folding the angle into one wedge makes r*cos(folded)
// the support function of every rotated facet copy, so max() over the plane set
// is a true convex sdf that sphere-traces cleanly. Unit proportions: girdle
// radius 1, table at y=0.38, culet at (0,-0.85).
//
// glsl/shapes/ is the math-only library: plain functions of a point and floats.
//----------------------------------------------------------------------------


//fold the angle into the +/- sector/2 wedge about phase, and return the folded
//radial support r*cos(a) (file-private helper)
float gem_support(float r, float ang, float sector, float phase){
    float a = mod(ang + phase + 0.5*sector, sector) - 0.5*sector;
    return r*cos(a);
}


// p is in the gem's own coordinates (origin at the girdle centre)
float gemDistance(vec3 p, float size){
    p /= size;
    float r   = length(p.xz);
    float ang = atan(p.z, p.x);
    const float sector = 2.*PI/8.;

    float rc = gem_support(r, ang, sector, 0.);            //crown + girdle wedge
    float rp = gem_support(r, ang, sector, 0.5*sector);    //pavilion wedge (alternates)

    float table    = p.y - 0.38;
    float girdle   = rc - 1.;
    float crown    = dot(vec2(rc, p.y), vec2(0.5547, 0.8321)) - 0.6213;
    float pavilion = dot(vec2(rp, p.y), vec2(0.6247, -0.7809)) - 0.6637;

    return size * max( max(table, girdle), max(crown, pavilion) );
}


// bounding sphere: girdle polygon corners reach r = 1.082, all else is inside
float gemBound(vec3 p, float size){
    return length(p) - 1.15*size;
}


//--- library: glsl/shapes/room.glsl ---
//----------------------------------------------------------------------------
// ROOM — a closed box, seen from the inside.
//
// The room is ONE region whose solid is everything OUTSIDE the box, so the
// interior is open air and regionAt() returns ID_NONE there. Its six walls are
// not six objects: they are a material FIELD over that one region, read off by
// asking which face a point is nearest. roomFace() answers that.
//
// glsl/shapes/ is the math-only library: plain functions of a point and some
// floats. No structs, no Frame, no Material.
//----------------------------------------------------------------------------


const int ROOM_FLOOR   = 0;
const int ROOM_CEILING = 1;
const int ROOM_LEFT    = 2;
const int ROOM_RIGHT   = 3;
const int ROOM_FRONT   = 4;
const int ROOM_BACK    = 5;


// p is in the room's own coordinates (origin at the box centre).
// Negative in the WALLS, positive in the open interior — the sign convention
// every other region uses, just turned inside out.
float roomDistance(vec3 p, vec3 halfSize){
    return -bBox(p, halfSize);
}


// Exact ray intersection, in world coordinates. The ray is inside the box, so
// this is simply the distance at which it leaves: the nearest of the three
// far slab crossings.
float roomTrace(Vector tv, vec3 centre, vec3 halfSize){
    vec3  o  = tv.pos - centre;
    vec3  tm = max((-halfSize - o)/tv.dir, (halfSize - o)/tv.dir);
    float t  = min(tm.x, min(tm.y, tm.z));
    if(t < 0.){ return maxDist; }
    return min(t, maxDist);
}


// Which wall p is on (or nearest to) — a shape DATA output (docs/shape-data.md):
// a material that reads `faceData` gets it injected. d is negative inside the
// room, so its LARGEST component names the axis the point is closest to leaving
// through, and the sign of p picks which of that axis's two faces.
int roomFaceData(vec3 p, vec3 halfSize){
    vec3 d = abs(p) - halfSize;

    if(d.y >= d.x && d.y >= d.z){
        return (p.y > 0.) ? ROOM_CEILING : ROOM_FLOOR;
    }
    if(d.x >= d.z){
        return (p.x > 0.) ? ROOM_RIGHT : ROOM_LEFT;
    }
    return (p.z > 0.) ? ROOM_BACK : ROOM_FRONT;
}


//--- the objects, in declaration order (= containment priority, inner to outer)
const int ID_DRILLED = 0;
const int ID_HALO    = 1;
const int ID_LAMP    = 2;
const int ID_ROOM    = 3;

const int N_OBJ = 4;
float gSDF[N_OBJ];


//--- placement and shape parameters ----------------------------------
const vec3  DRILLED_P      = vec3(-1.8, 1.0, 0.0);
const float DRILLED_RADIUS = 1.0;

const vec3  HALO_P          = vec3(1.9, 1.5, 0.4);
const vec3  HALO_CUT_NORMAL = vec3(0.0, 0.0, -1.0);
const float HALO_SIZE       = 1.3;

const vec3  LAMP_P      = vec3(-4.0, 8.5, 5.0);
const float LAMP_RADIUS = 1.4;

const vec3 ROOM_P        = vec3(0.0, 6.0, 0.0);
const vec3 ROOM_HALFSIZE = vec3(10.0, 6.0, 10.0);


//---------------------------------------------------------------------
// the region sdfs
//---------------------------------------------------------------------

float sdf_drilled(vec3 p){
    vec3  q = p - DRILLED_P;
    float d = sphereDistance(q, DRILLED_RADIUS);
    return smax(d, 0.45 - length(q.xz), bite);
}

float sdf_halo(vec3 p){
    vec3  q = p - HALO_P;
    float d = gemDistance(q, HALO_SIZE);
    d = min(d, abs(d - gap) - 0.04);
    return opSubtractDist(d, planeDistance(p - HALO_P, HALO_CUT_NORMAL));
}

float sdf_lamp(vec3 p){
    return sphereDistance(p - LAMP_P, LAMP_RADIUS);
}

//the room SOLID is everything outside the box, so its interior is open air and
//regionAt() returns ID_NONE there
float sdf_room(vec3 p){
    return roomDistance(p - ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the bounds — the acceleration structure (sdf_Scene only; sdfAll stays exact)
//---------------------------------------------------------------------

float bound_drilled(vec3 p){
    return sphereDistance(p - DRILLED_P, DRILLED_RADIUS);
}

float bound_halo(vec3 p){
    return gemBound(p - HALO_P, HALO_SIZE) - 0.64;
}


//---------------------------------------------------------------------
// the normals — the 4-tap of each region's own sdf, in world coordinates
//---------------------------------------------------------------------
const float NRM_E = 0.0002;

Vector normal_drilled(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_drilled(p + k.xyy*NRM_E) + k.yyx*sdf_drilled(p + k.yyx*NRM_E)
                              + k.yxy*sdf_drilled(p + k.yxy*NRM_E) + k.xxx*sdf_drilled(p + k.xxx*NRM_E) ));
}

Vector normal_halo(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_halo(p + k.xyy*NRM_E) + k.yyx*sdf_halo(p + k.yyx*NRM_E)
                              + k.yxy*sdf_halo(p + k.yxy*NRM_E) + k.xxx*sdf_halo(p + k.xxx*NRM_E) ));
}

Vector normal_lamp(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_lamp(p + k.xyy*NRM_E) + k.yyx*sdf_lamp(p + k.yyx*NRM_E)
                              + k.yxy*sdf_lamp(p + k.yxy*NRM_E) + k.xxx*sdf_lamp(p + k.xxx*NRM_E) ));
}

Vector normal_room(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_room(p + k.xyy*NRM_E) + k.yyx*sdf_room(p + k.yyx*NRM_E)
                              + k.yxy*sdf_room(p + k.yxy*NRM_E) + k.xxx*sdf_room(p + k.xxx*NRM_E) ));
}


//---------------------------------------------------------------------
// the materials
//  material_ gives the Surface plus this object's own Medium; medium_ gives
//  only the Medium, for when the object is merely the far side
//---------------------------------------------------------------------

Material material_drilled(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //gloss
    m.surf.diffuse   = vec3(0.72, 0.34, 0.22);
    m.surf.roughness = 0.3;
    m.surf.gloss     = 0.06;
    return m;
}
Medium   medium_drilled  (vec3 p){ return defaultMedium(); }

Material material_halo(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //gloss
    m.surf.diffuse   = vec3(0.32, 0.42, 0.58);
    m.surf.roughness = 0.35;
    m.surf.gloss     = 0.08;
    return m;
}
Medium   medium_halo  (vec3 p){ return defaultMedium(); }

Material material_lamp(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //light
    m.surf.emit = lampPower*vec3(1.0, 0.95, 0.88);
    return m;
}
Medium   medium_lamp  (vec3 p){ return defaultMedium(); }

Material material_room(vec3 p, inout Vector n){
    vec3 q = p - ROOM_P;
    int faceData = roomFaceData(q, ROOM_HALFSIZE);
    if(faceData == ROOM_CEILING){ return makeLight(vec3(1.0), roomLight); }
    if(faceData == ROOM_FLOOR)  { return makeGloss(floorColor, 0.0, wallRough); }
    if(faceData == ROOM_LEFT)   { return makeGloss(warmColor,  0.0, wallRough); }
    if(faceData == ROOM_RIGHT)  { return makeGloss(coolColor,  0.0, wallRough); }
    return makeGloss(wallColor, 0.0, wallRough);
}
Medium medium_room(vec3 p){ return defaultMedium(); }


//---------------------------------------------------------------------
// the analytic intersections
//---------------------------------------------------------------------

float trace_lamp(Vector tv){
    return sphereTrace(tv, LAMP_P, LAMP_RADIUS);
}

float trace_room(Vector tv){
    return roomTrace(tv, ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the dispatchers
//---------------------------------------------------------------------

void sdfAll(vec3 p){
    gSDF[ID_DRILLED] = sdf_drilled(p);
    gSDF[ID_HALO   ] = sdf_halo(p);
    gSDF[ID_LAMP   ] = sdf_lamp(p);
    gSDF[ID_ROOM   ] = sdf_room(p);
}

Vector normalOf(int id, vec3 p){
    if(id == ID_DRILLED){ return normal_drilled(p); }
    if(id == ID_HALO   ){ return normal_halo(p); }
    if(id == ID_LAMP   ){ return normal_lamp(p); }
    return normal_room(p);
}

//no sheets in this scene: every object is a region with an interior
bool isSheet(int id){ return false; }

Material materialOf(int id, vec3 p, inout Vector n, bool front){
    if(id == ID_DRILLED){ return material_drilled(p, n); }
    if(id == ID_HALO   ){ return material_halo(p, n); }
    if(id == ID_LAMP   ){ return material_lamp(p, n); }
    return material_room(p, n);
}

Medium mediumOf(int id, vec3 p){
    if(id == ID_DRILLED){ return medium_drilled(p); }
    if(id == ID_HALO   ){ return medium_halo(p); }
    if(id == ID_LAMP   ){ return medium_lamp(p); }
    if(id == ID_ROOM   ){ return medium_room(p); }
    return defaultMedium();      //ID_NONE: open air
}


//---------------------------------------------------------------------
// the entry points
//---------------------------------------------------------------------

void buildScene(){}

float sdf_Scene(Vector tv){
    vec3 p = tv.pos;
    float d = maxDist;

    float b_drilled = bound_drilled(p);
    d = min(d, (b_drilled > BOUND_MARGIN) ? b_drilled : sdf_drilled(p));

    float b_halo = bound_halo(p);
    d = min(d, (b_halo > BOUND_MARGIN) ? b_halo : sdf_halo(p));

    return d;
}

float trace_Scene(Vector tv){
    float d = maxDist;
    d = min(d, trace_lamp(tv));
    d = min(d, trace_room(tv));
    return d;
}
