//=====================================================================
// generated by scenegen from src/scene.js — do not edit by hand
//=====================================================================


//--- library: glsl/shapes/models/hypDod.glsl ---
//----------------------------------------------------------------------------
// HYPERBOLIC DODECAHEDRON — the right-angled dodecahedron of H^3, drawn in the
// BALL (Poincare) model.
//
// The construction is the whole idea: in the ball model a hyperbolic PLANE is a
// Euclidean sphere meeting the unit sphere orthogonally. So the solid is the unit
// ball with twelve such spheres carved out of it, one per face — and the carving
// is `max(dist, -faceSphere)`, an intersection of the twelve outsides.
//
// Orthogonality fixes the geometry with no freedom left: a face sphere at
// distance d from the origin with radius r must satisfy d^2 = r^2 + 1, and for
// the right-angled dodecahedron c = 2/phi gives r = sqrt(c), d = sqrt(c+1).
// That is why this shape has no size parameter — it is THE right-angled
// dodecahedron, not a family.
//
// The face directions are the icosahedron's vertex directions, (0, ±1, ±phi)
// cycled, since the dodecahedron's faces point at its dual's vertices — the same
// duality primitives/dodecahedron.glsl uses.
//
// `rCent` carves a sphere out of the middle, turning the solid into a shell;
// rCent <= 0 leaves it solid.
//
// glsl/shapes/ is the math-only library: plain functions of a point and floats.
//----------------------------------------------------------------------------


// the six face directions, up to sign: (0, 1, phi) cycled over the axes.
// phi = 1.6180340, |(0, 1, phi)| = 1.9021130. The legacy normalized a truncated
// 1.618 instead of phi, which tilted every face by ~8e-6 — below anything
// visible, but these are the directions that actually make the solid
// right-angled, so the port uses exact phi.
const vec3 HYPDOD_FACES[6] = vec3[6](
    vec3( 0.0,        0.5257311,  0.8506508),
    vec3( 0.8506508,  0.0,        0.5257311),
    vec3( 0.5257311,  0.8506508,  0.0),
    vec3( 0.0,       -0.5257311,  0.8506508),
    vec3( 0.8506508,  0.0,       -0.5257311),
    vec3(-0.5257311,  0.8506508,  0.0)
);


// p is in the solid's own coordinates (origin at the centre of the ball model)
float hypDodDistance(vec3 p, float rCent){
    //c = 2/phi; the orthogonality condition d^2 = r^2 + 1 then gives both
    const float HYPDOD_R = 1.1117859;                    // sqrt(c),     c = 2/phi
    const float HYPDOD_D = 1.4953488;                    // sqrt(c + 1)

    float dist = length(p) - 1.0;                        //the unit ball

    //carve the twelve face spheres: each direction and its antipode
    for(int i = 0; i < 6; i++){
        vec3 v = HYPDOD_FACES[i];
        dist = max(dist, -(length(p - HYPDOD_D*v) - HYPDOD_R));
        dist = max(dist, -(length(p + HYPDOD_D*v) - HYPDOD_R));
    }

    //hollow out the middle, if asked
    if(rCent > 0.0){
        dist = smax(dist, rCent - length(p), 0.1);
    }
    return dist;
}


// the sdf starts at length(p) - 1 and is only ever max()'d LARGER (carving
// spheres out of the unit ball), so the solid is contained in the unit sphere
// and the ball's own first term is provably conservative.
float hypDodBound(vec3 p, float rCent){
    return length(p) - 1.0;
}


//--- library: glsl/shapes/environments/room.glsl ---
//----------------------------------------------------------------------------
// ROOM — a closed box, seen from the inside.
//
// The room is ONE region whose solid is everything OUTSIDE the box, so the
// interior is open air and regionAt() returns ID_NONE there. Its six walls are
// not six objects: they are a material FIELD over that one region, read off by
// asking which face a point is nearest. roomFace() answers that.
//
// glsl/shapes/ is the math-only library: plain functions of a point and some
// floats. No structs, no Frame, no Material.
//----------------------------------------------------------------------------


const int ROOM_FLOOR   = 0;
const int ROOM_CEILING = 1;
const int ROOM_LEFT    = 2;
const int ROOM_RIGHT   = 3;
const int ROOM_FRONT   = 4;
const int ROOM_BACK    = 5;


// p is in the room's own coordinates (origin at the box centre).
// Negative in the WALLS, positive in the open interior — the sign convention
// every other region uses, just turned inside out.
float roomDistance(vec3 p, vec3 halfSize){
    return -boxDistance(p, halfSize);
}


// Exact ray intersection, in world coordinates. The ray is inside the box, so
// this is simply the distance at which it leaves: the nearest of the three
// far slab crossings.
float roomTrace(Vector tv, vec3 centre, vec3 halfSize){
    vec3  o  = tv.pos - centre;
    vec3  tm = max((-halfSize - o)/tv.dir, (halfSize - o)/tv.dir);
    float t  = min(tm.x, min(tm.y, tm.z));
    if(t < 0.){ return maxDist; }
    return min(t, maxDist);
}


// Which wall p is on (or nearest to) — a shape DATA output (docs/shape-data.md):
// a material that reads `faceData` gets it injected. d is negative inside the
// room, so its LARGEST component names the axis the point is closest to leaving
// through, and the sign of p picks which of that axis's two faces.
int roomFaceData(vec3 p, vec3 halfSize){
    vec3 d = abs(p) - halfSize;

    if(d.y >= d.x && d.y >= d.z){
        return (p.y > 0.) ? ROOM_CEILING : ROOM_FLOOR;
    }
    if(d.x >= d.z){
        return (p.x > 0.) ? ROOM_RIGHT : ROOM_LEFT;
    }
    return (p.z > 0.) ? ROOM_BACK : ROOM_FRONT;
}


//--- the objects, in declaration order (= containment priority, inner to outer)
const int ID_CORE   = 0;
const int ID_MARBLE = 1;
const int ID_KEY    = 2;
const int ID_ROOM   = 3;

const int N_OBJ = 4;
float gSDF[N_OBJ];


//--- placement and shape parameters ----------------------------------
const vec3 CORE_P     = vec3(0.0, 2.6, 0.0);
const vec3 CORE_SCALE = vec3(2.5);

const vec3  MARBLE_P      = vec3(0.0, 2.6, 0.0);
const vec3  MARBLE_SCALE  = vec3(2.5);
const float MARBLE_RADIUS = 1.0;

const vec3  KEY_P      = vec3(-8.0, 9.0, 6.0);
const float KEY_RADIUS = 2.0;

const vec3 ROOM_P        = vec3(0.0, 5.75, -5.0);
const vec3 ROOM_HALFSIZE = vec3(20.0, 8.25, 15.0);


//---------------------------------------------------------------------
// the region sdfs
//---------------------------------------------------------------------

vec3 toLocal_core(vec3 p){
    return (p - CORE_P) / CORE_SCALE;
}

float sdf_core(vec3 p){
    float d = hypDodDistance(toLocal_core(p), coreRadius);
    return d * min(CORE_SCALE.x, min(CORE_SCALE.y, CORE_SCALE.z));
}

vec3 toLocal_marble(vec3 p){
    return (p - MARBLE_P) / MARBLE_SCALE;
}

float sdf_marble(vec3 p){
    float d = sphereDistance(toLocal_marble(p), MARBLE_RADIUS);
    return d * min(MARBLE_SCALE.x, min(MARBLE_SCALE.y, MARBLE_SCALE.z));
}

float sdf_key(vec3 p){
    return sphereDistance(p - KEY_P, KEY_RADIUS);
}

//the room SOLID is everything outside the box, so its interior is open air and
//regionAt() returns ID_NONE there
float sdf_room(vec3 p){
    return roomDistance(p - ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the normals — the 4-tap of each region's own sdf, in world coordinates
//---------------------------------------------------------------------
const float NRM_E = 0.0002;

Vector normal_core(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_core(p + k.xyy*NRM_E) + k.yyx*sdf_core(p + k.yyx*NRM_E)
                              + k.yxy*sdf_core(p + k.yxy*NRM_E) + k.xxx*sdf_core(p + k.xxx*NRM_E) ));
}

Vector normal_marble(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_marble(p + k.xyy*NRM_E) + k.yyx*sdf_marble(p + k.yyx*NRM_E)
                              + k.yxy*sdf_marble(p + k.yxy*NRM_E) + k.xxx*sdf_marble(p + k.xxx*NRM_E) ));
}

Vector normal_key(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_key(p + k.xyy*NRM_E) + k.yyx*sdf_key(p + k.yyx*NRM_E)
                              + k.yxy*sdf_key(p + k.yxy*NRM_E) + k.xxx*sdf_key(p + k.xxx*NRM_E) ));
}

Vector normal_room(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_room(p + k.xyy*NRM_E) + k.yyx*sdf_room(p + k.yyx*NRM_E)
                              + k.yxy*sdf_room(p + k.yxy*NRM_E) + k.xxx*sdf_room(p + k.xxx*NRM_E) ));
}


//---------------------------------------------------------------------
// the materials
//  material_ gives the Surface plus this object's own Medium; medium_ gives
//  only the Medium, for when the object is merely the far side
//---------------------------------------------------------------------

Medium medium_core(vec3 p){
    Medium m = defaultMedium();
    m.ior    = 2.5;
    m.absorb = vec3(7.5, 20.794, 22.147);
    return m;
}
Material material_core(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //glass
    m.interior = medium_core(p);
    m.surf.transmit = 1.0;
    return m;
}

Medium medium_marble(vec3 p){
    Medium m = defaultMedium();
    m.ior    = 1.5;
    m.absorb = vec3(0.06, 0.01, 0.04);
    return m;
}
Material material_marble(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //glass
    m.interior = medium_marble(p);
    m.surf.transmit = 1.0;
    return m;
}

Material material_key(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //light
    m.surf.emit = 220.0*vec3(0.9);
    return m;
}
Medium   medium_key  (vec3 p){ return defaultMedium(); }

Material material_room(vec3 p, inout Vector n){
    vec3 q = p - ROOM_P;
    int faceData = roomFaceData(q, ROOM_HALFSIZE);
    if(faceData == ROOM_CEILING){ return makeLight(vec3(1.0), roomLight); }
    if(faceData == ROOM_FLOOR)  { return makeGloss(floorColor, 0.0, wallRough); }
    if(faceData == ROOM_LEFT)   { return makeGloss(warmColor,  0.0, wallRough); }
    if(faceData == ROOM_RIGHT)  { return makeGloss(coolColor,  0.0, wallRough); }
    return makeGloss(wallColor, 0.0, wallRough);
}
Medium medium_room(vec3 p){ return defaultMedium(); }


//---------------------------------------------------------------------
// the analytic intersections
//---------------------------------------------------------------------

float trace_key(Vector tv){
    return sphereTrace(tv, KEY_P, KEY_RADIUS);
}

float trace_room(Vector tv){
    return roomTrace(tv, ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the dispatchers
//---------------------------------------------------------------------

void sdfAll(vec3 p){
    gSDF[ID_CORE  ] = sdf_core(p);
    gSDF[ID_MARBLE] = sdf_marble(p);
    gSDF[ID_KEY   ] = sdf_key(p);
    gSDF[ID_ROOM  ] = sdf_room(p);
}

Vector normalOf(int id, vec3 p){
    if(id == ID_CORE  ){ return normal_core(p); }
    if(id == ID_MARBLE){ return normal_marble(p); }
    if(id == ID_KEY   ){ return normal_key(p); }
    return normal_room(p);
}

//no sheets in this scene: every object is a region with an interior
bool isSheet(int id){ return false; }

Material materialOf(int id, vec3 p, inout Vector n, bool front){
    if(id == ID_CORE  ){ return material_core(p, n); }
    if(id == ID_MARBLE){ return material_marble(p, n); }
    if(id == ID_KEY   ){ return material_key(p, n); }
    return material_room(p, n);
}

Medium mediumOf(int id, vec3 p){
    if(id == ID_CORE  ){ return medium_core(p); }
    if(id == ID_MARBLE){ return medium_marble(p); }
    if(id == ID_KEY   ){ return medium_key(p); }
    if(id == ID_ROOM  ){ return medium_room(p); }
    return defaultMedium();      //ID_NONE: open air
}


//---------------------------------------------------------------------
// the entry points
//---------------------------------------------------------------------

void buildScene(){}

float sdf_Scene(Vector tv){
    vec3 p = tv.pos;
    float d = maxDist;

    d = min(d, sdf_core(p));

    d = min(d, sdf_marble(p));

    return d;
}

float trace_Scene(Vector tv){
    float d = maxDist;
    d = min(d, trace_key(tv));
    d = min(d, trace_room(tv));
    return d;
}
