//=====================================================================
// generated by scenegen from src/scene.js — do not edit by hand
//=====================================================================


//--- library: glsl/shapes/models/polytope4D.glsl ---
//----------------------------------------------------------------------------
// REGULAR 4-POLYTOPE — the six regular polytopes of R^4, drawn as a wireframe
// (a ball at each vertex, a tube along each edge) STEREOGRAPHICALLY PROJECTED
// from S^3 into R^3.
//
// ONE FILE FOR ALL SIX, because the machinery below is identical for every one
// of them: only `type` and `coords` differ, and those are parameters. The six
// classic names are presets over this shape (js/presets/polytopes.js), so a
// scene writes hypercube(...) or sixHundredCell(...) and never sees the pair.
//
// HOW IT WORKS, in the order the code runs:
//
//   1. the point is inverse-stereographically projected onto the unit S^3, so
//      the whole construction happens on the sphere and only the DISTANCE comes
//      back to R^3;
//   2. `spin` rotates it there — an internal rotation of S^3, which is what
//      turns the figure inside out as it sweeps. Not 3D placement;
//   3. `p4_fold` reflects it into the Coxeter fundamental domain: abs() on the
//      xy pair plus reflections in two mirrors nc, nd, iterated. After folding,
//      ONE vertex and FOUR edges represent the whole polytope, which is why a
//      600-cell costs the same per step as a 5-cell (only the fold depth grows);
//   4. distances to that vertex and those edges are SPHERICAL, so `p4_DD`
//      converts each into the Euclidean distance seen under the projection from
//      radius r. That conversion is the heart of the file.
//
// WHICH POLYTOPE: `type` is the Coxeter parameter (3, 4 or 5) and `coords` picks
// a point in the fundamental domain; together they choose the figure.
//   type 3, (0,1,0,0)   5-cell           type 4, (0,0,1,0)   24-cell
//   type 4, (0,1,0,0)   hypercube        type 5, (0,1,0,0)   120-cell
//   type 4, (0,0,0,1)   16-cell          type 5, (0,0,0,1)   600-cell
//
// COST: the fold runs 3, 8 or 15 times for type 3, 4 or 5 — so the 120-cell and
// the 600-cell are markedly dearer than the rest.
//
// VERTEX vs EDGE is a DATA OUTPUT (docs/shape-data.md), not two regions. The
// legacy carried two Material fields and picked between them in a custom
// setData; here the shape is one region and `partData` says which part was hit,
// so a material body switches on it — the same channel the room uses for its
// walls. That keeps the shape usable as an ordinary `shape:` (and so through the
// six presets), which two outputs would not: multi-output shapes have to be
// called from a group's authored body.
//
// The one thing this gives up is a separate MEDIUM per part — one region, one
// interior. The classic look is gloss on both, which has no interior at all, so
// nothing is lost today; a vertex-glass/edge-metal scene would need the group
// form instead.
//
// glsl/shapes/ is the math-only library: plain functions of a point and floats.
//----------------------------------------------------------------------------


//the two parts a hit can belong to, for the partData channel
const int P4_VERTEX = 0;
const int P4_EDGE   = 1;


//how many times the fold must run to close up this Coxeter group
int p4_iterates(int type){
    if(type == 3){ return 3; }
    if(type == 4){ return 8; }
    if(type == 5){ return 15; }
    return 10;
}


//reflect into the fundamental domain
vec4 p4_fold(vec4 pos, vec4 nc, vec4 nd, int iterates){
    for(int i = 0; i < 15; i++){
        if(i > iterates){ break; }
        pos.xy = abs(pos.xy);
        float t = -2.*min(0., dot(pos, nc));
        pos += t*nc;
        t = -2.*min(0., dot(pos, nd));
        pos += t*nd;
    }
    return pos;
}


//a spherical distance on the unit S^3 (given as its cosine ca and sine sa) as
//the EUCLIDEAN distance seen from a point at radius r under the stereographic
//projection. This is what lets a 4D construction be sphere-traced in R^3.
float p4_DD(float ca, float sa, float r){
    return r - (2.*r*ca - (1. - r*r)*sa)/((1. - r*r)*ca + 2.*r*sa + 1. + r*r);
}


float p4_toVertex(vec4 z, vec4 pVec, float r){
    float ca = dot(z, pVec);
    float sa = 0.5*length(pVec - z)*length(pVec + z);
    return p4_DD(ca, sa, r);
}


//distance to the edge lying in the plane of pVec and the mirror normal n
float p4_toSegment(vec4 z, vec4 n, vec4 pVec, float r){
    //pmin: z projected onto that plane, then back onto the sphere
    float zn = dot(z, n), zp = dot(z, pVec), np = dot(n, pVec);
    float alpha = zp - zn*np, beta = zn - zp*np;
    vec4  pmin  = normalize(alpha*pVec + min(0., beta)*n);

    float ca = dot(z, pmin), sa = 0.5*length(pmin - z)*length(pmin + z);
    return p4_DD(ca, sa, r);
}


//the four edges that survive the fold
float p4_toEdges(vec4 z, vec4 nc, vec4 nd, vec4 pVec, float r){
    float da = p4_toSegment(z, vec4(1., 0., 0., 0.), pVec, r);
    float db = p4_toSegment(z, vec4(0., 1., 0., 0.), pVec, r);
    float dc = p4_toSegment(z, nc, pVec, r);
    float dd = p4_toSegment(z, nd, pVec, r);
    return min(min(da, db), min(dc, dd));
}


//the Coxeter data for (type, coords): two mirror normals and the generating
//point whose orbit is the polytope's vertex set
void p4_setup(int type, vec4 coords, out vec4 nc, out vec4 nd, out vec4 pVec){
    float cospin  = cos(PI/float(type));
    float isinpin = 1./sin(PI/float(type));
    float scospin = sqrt(2./3. - cospin*cospin);
    float issinpin = 1./sqrt(3. - 4.*cospin*cospin);

    nc = 0.5*vec4(0., -1., sqrt(3.), 0.);
    nd = vec4(-cospin, -0.5, -0.5/sqrt(3.), scospin);

    vec4 pabc = vec4(0., 0., 0., 1.);
    vec4 pbdc = 0.5*sqrt(3.)*vec4(scospin, 0., 0., cospin);
    vec4 pcda = isinpin*vec4(0., 0.5*sqrt(3.)*scospin, 0.5*scospin, 1./sqrt(3.));
    vec4 pdba = issinpin*vec4(0., 0., 2.*scospin, 1./sqrt(3.));

    pVec = normalize(coords.x*pabc + coords.y*pbdc + coords.z*pcda + coords.w*pdba);
}


//the shared work: project, spin, fold, and measure both parts (file-private)
void p4_parts(vec3 p, int type, vec4 coords, vec3 spinAxis, float spinAngle,
              out float vertexDist, out float edgeDist){
    vec4 nc, nd, pVec;
    p4_setup(type, coords, nc, nd, pVec);

    //onto the sphere
    float r = length(p);
    vec4  z = vec4(2.*p, 1. - r*r)*(1./(1. + r*r));

    //spin it there, then fold into the fundamental domain
    z.xyw = rot3AxisAngle(normalize(spinAxis), spinAngle)*z.xyw;
    z = p4_fold(z, nc, nd, p4_iterates(type));

    vertexDist = p4_toVertex(z, pVec, r);
    edgeDist   = p4_toEdges(z, nc, nd, pVec, r);
}


// p is in the polytope's own coordinates.
//
// `spinAxis` and `spinAngle` (DEGREES) are the internal rotation of S^3 — the
// figure's pose in 4D, not its placement in 3D. The legacy carried this as a
// mat3 built by rot3AxisAngle; taking the axis and angle instead is the same
// rotation, and makes it drivable by a knob.
float polytope4DDistance(vec3 p, int type, vec4 coords, float vertexRad, float edgeRad,
                         vec3 spinAxis, float spinAngle){
    float v, e;
    p4_parts(p, type, coords, spinAxis, spinAngle, v, e);
    return min(v - vertexRad, e - edgeRad);
}


// which part was hit (shape data): P4_VERTEX or P4_EDGE. A material body that
// reads `partData` gets it injected with this object's own consts baked in.
int polytope4DPartData(vec3 q, int type, vec4 coords, float vertexRad, float edgeRad,
                       vec3 spinAxis, float spinAngle){
    float v, e;
    p4_parts(q, type, coords, spinAxis, spinAngle, v, e);
    return (v - vertexRad < e - edgeRad) ? P4_VERTEX : P4_EDGE;
}


// NO BOUND, and there cannot be a constant one. Under the stereographic
// projection the figure's extent DEPENDS ON THE SPIN: as the S^3 rotation
// sweeps, cells pass through the projection point and shoot off toward infinity.
// Measured for the hypercube at vertexRad 0.15, the extent swings from |p| = 1.25
// at spin -45 to 3.76 at spin 0 — and it is unbounded in principle. The legacy's
// fixed `length(p) - 2.4` therefore CLIPPED the figure at some spins, which is a
// bound that silently deletes geometry.
//
// A scene that wants finiteness clips explicitly — clip() donates its cutter as
// the bound, so the cut is visible and chosen rather than accidental.


//--- library: glsl/shapes/environments/room.glsl ---
//----------------------------------------------------------------------------
// ROOM — a closed box, seen from the inside.
//
// The room is ONE region whose solid is everything OUTSIDE the box, so the
// interior is open air and regionAt() returns ID_NONE there. Its six walls are
// not six objects: they are a material FIELD over that one region, read off by
// asking which face a point is nearest. roomFace() answers that.
//
// glsl/shapes/ is the math-only library: plain functions of a point and some
// floats. No structs, no Frame, no Material.
//----------------------------------------------------------------------------


const int ROOM_FLOOR   = 0;
const int ROOM_CEILING = 1;
const int ROOM_LEFT    = 2;
const int ROOM_RIGHT   = 3;
const int ROOM_FRONT   = 4;
const int ROOM_BACK    = 5;


// p is in the room's own coordinates (origin at the box centre).
// Negative in the WALLS, positive in the open interior — the sign convention
// every other region uses, just turned inside out.
float roomDistance(vec3 p, vec3 halfSize){
    return -boxDistance(p, halfSize);
}


// Exact ray intersection, in world coordinates. The ray is inside the box, so
// this is simply the distance at which it leaves: the nearest of the three
// far slab crossings.
float roomTrace(Vector tv, vec3 centre, vec3 halfSize){
    vec3  o  = tv.pos - centre;
    vec3  tm = max((-halfSize - o)/tv.dir, (halfSize - o)/tv.dir);
    float t  = min(tm.x, min(tm.y, tm.z));
    if(t < 0.){ return maxDist; }
    return min(t, maxDist);
}


// Which wall p is on (or nearest to) — a shape DATA output (docs/shape-data.md):
// a material that reads `faceData` gets it injected. d is negative inside the
// room, so its LARGEST component names the axis the point is closest to leaving
// through, and the sign of p picks which of that axis's two faces.
int roomFaceData(vec3 p, vec3 halfSize){
    vec3 d = abs(p) - halfSize;

    if(d.y >= d.x && d.y >= d.z){
        return (p.y > 0.) ? ROOM_CEILING : ROOM_FLOOR;
    }
    if(d.x >= d.z){
        return (p.x > 0.) ? ROOM_RIGHT : ROOM_LEFT;
    }
    return (p.z > 0.) ? ROOM_BACK : ROOM_FRONT;
}


//--- the objects, in declaration order (= containment priority, inner to outer)
const int ID_HYPER = 0;
const int ID_DUAL  = 1;
const int ID_KEY   = 2;
const int ID_ROOM  = 3;

const int N_OBJ = 4;
float gSDF[N_OBJ];


//--- placement and shape parameters ----------------------------------
const vec3  HYPER_P           = vec3(0.0, 1.5, 0.0);
const float HYPER_CLIP_RADIUS = 6.0;
const int   HYPER_TYPE        = 4;
const vec4  HYPER_COORDS      = vec4(0.0, 1.0, 0.0, 0.0);
const vec3  HYPER_SPINAXIS    = vec3(0.0, 1.0, 0.1);

const vec3  DUAL_P           = vec3(0.0, 1.5, 0.0);
const float DUAL_CLIP_RADIUS = 6.0;
const int   DUAL_TYPE        = 4;
const vec4  DUAL_COORDS      = vec4(0.0, 0.0, 0.0, 1.0);
const vec3  DUAL_SPINAXIS    = vec3(0.0, 1.0, 0.1);

const vec3  KEY_P      = vec3(-12.0, 8.0, 2.0);
const float KEY_RADIUS = 1.5;

const vec3 ROOM_P        = vec3(0.0, 5.75, -5.0);
const vec3 ROOM_HALFSIZE = vec3(20.0, 8.25, 15.0);


//---------------------------------------------------------------------
// the region sdfs
//---------------------------------------------------------------------

float sdf_hyper(vec3 p){
    float d = polytope4DDistance(p - HYPER_P, HYPER_TYPE, HYPER_COORDS, vertexRad, edgeRad, HYPER_SPINAXIS, spin);
    return max(d, sphereDistance(p - HYPER_P, HYPER_CLIP_RADIUS));
}

float sdf_dual(vec3 p){
    float d = polytope4DDistance(p - DUAL_P, DUAL_TYPE, DUAL_COORDS, vertexRad, edgeRad, DUAL_SPINAXIS, spin);
    return max(d, sphereDistance(p - DUAL_P, DUAL_CLIP_RADIUS));
}

float sdf_key(vec3 p){
    return sphereDistance(p - KEY_P, KEY_RADIUS);
}

//the room SOLID is everything outside the box, so its interior is open air and
//regionAt() returns ID_NONE there
float sdf_room(vec3 p){
    return roomDistance(p - ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the bounds — the acceleration structure (sdf_Scene only; sdfAll stays exact)
//---------------------------------------------------------------------

float bound_hyper(vec3 p){
    return sphereDistance(p - HYPER_P, HYPER_CLIP_RADIUS);
}

float bound_dual(vec3 p){
    return sphereDistance(p - DUAL_P, DUAL_CLIP_RADIUS);
}


//---------------------------------------------------------------------
// the normals — the 4-tap of each region's own sdf, in world coordinates
//---------------------------------------------------------------------
const float NRM_E = 0.0002;

Vector normal_hyper(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_hyper(p + k.xyy*NRM_E) + k.yyx*sdf_hyper(p + k.yyx*NRM_E)
                              + k.yxy*sdf_hyper(p + k.yxy*NRM_E) + k.xxx*sdf_hyper(p + k.xxx*NRM_E) ));
}

Vector normal_dual(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_dual(p + k.xyy*NRM_E) + k.yyx*sdf_dual(p + k.yyx*NRM_E)
                              + k.yxy*sdf_dual(p + k.yxy*NRM_E) + k.xxx*sdf_dual(p + k.xxx*NRM_E) ));
}

Vector normal_key(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_key(p + k.xyy*NRM_E) + k.yyx*sdf_key(p + k.yyx*NRM_E)
                              + k.yxy*sdf_key(p + k.yxy*NRM_E) + k.xxx*sdf_key(p + k.xxx*NRM_E) ));
}

Vector normal_room(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_room(p + k.xyy*NRM_E) + k.yyx*sdf_room(p + k.yyx*NRM_E)
                              + k.yxy*sdf_room(p + k.yxy*NRM_E) + k.xxx*sdf_room(p + k.xxx*NRM_E) ));
}


//---------------------------------------------------------------------
// the materials
//  material_ gives the Surface plus this object's own Medium; medium_ gives
//  only the Medium, for when the object is merely the far side
//---------------------------------------------------------------------

Material material_hyper(vec3 p, inout Vector n){
    vec3 q = p - HYPER_P;
    int partData = polytope4DPartData(q, HYPER_TYPE, HYPER_COORDS, vertexRad, edgeRad, HYPER_SPINAXIS, spin);
    if(partData == P4_VERTEX){ return makeGloss(vec3(0.6, 0.1, 0.1), 0.2, 0.2); }
    return makeGloss(vec3(0.4), 0.2, 0.2);
}
Medium medium_hyper(vec3 p){ return defaultMedium(); }

Material material_dual(vec3 p, inout Vector n){
    vec3 q = p - DUAL_P;
    int partData = polytope4DPartData(q, DUAL_TYPE, DUAL_COORDS, vertexRad, edgeRad, DUAL_SPINAXIS, spin);
    if(partData == P4_VERTEX){ return makeGloss(vec3(0.12, 0.42, 0.5), 0.2, 0.2); }
    return makeGloss(vec3(0.22, 0.3, 0.34), 0.2, 0.2);
}
Medium medium_dual(vec3 p){ return defaultMedium(); }

Material material_key(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //light
    m.surf.emit = 60.0*vec3(1.0);
    return m;
}
Medium   medium_key  (vec3 p){ return defaultMedium(); }

Material material_room(vec3 p, inout Vector n){
    vec3 q = p - ROOM_P;
    int faceData = roomFaceData(q, ROOM_HALFSIZE);
    if(faceData == ROOM_CEILING){ return makeLight(vec3(1.0), roomLight); }
    if(faceData == ROOM_FLOOR)  { return makeGloss(floorColor, 0.0, wallRough); }
    if(faceData == ROOM_LEFT)   { return makeGloss(warmColor,  0.0, wallRough); }
    if(faceData == ROOM_RIGHT)  { return makeGloss(coolColor,  0.0, wallRough); }
    return makeGloss(wallColor, 0.0, wallRough);
}
Medium medium_room(vec3 p){ return defaultMedium(); }


//---------------------------------------------------------------------
// the analytic intersections
//---------------------------------------------------------------------

float trace_key(Vector tv){
    return sphereTrace(tv, KEY_P, KEY_RADIUS);
}

float trace_room(Vector tv){
    return roomTrace(tv, ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the dispatchers
//---------------------------------------------------------------------

void sdfAll(vec3 p){
    gSDF[ID_HYPER] = sdf_hyper(p);
    gSDF[ID_DUAL ] = sdf_dual(p);
    gSDF[ID_KEY  ] = sdf_key(p);
    gSDF[ID_ROOM ] = sdf_room(p);
}

Vector normalOf(int id, vec3 p){
    if(id == ID_HYPER){ return normal_hyper(p); }
    if(id == ID_DUAL ){ return normal_dual(p); }
    if(id == ID_KEY  ){ return normal_key(p); }
    return normal_room(p);
}

//no sheets in this scene: every object is a region with an interior
bool isSheet(int id){ return false; }

Material materialOf(int id, vec3 p, inout Vector n, bool front){
    if(id == ID_HYPER){ return material_hyper(p, n); }
    if(id == ID_DUAL ){ return material_dual(p, n); }
    if(id == ID_KEY  ){ return material_key(p, n); }
    return material_room(p, n);
}

Medium mediumOf(int id, vec3 p){
    if(id == ID_HYPER){ return medium_hyper(p); }
    if(id == ID_DUAL ){ return medium_dual(p); }
    if(id == ID_KEY  ){ return medium_key(p); }
    if(id == ID_ROOM ){ return medium_room(p); }
    return defaultMedium();      //ID_NONE: open air
}


//---------------------------------------------------------------------
// the entry points
//---------------------------------------------------------------------

void buildScene(){}

float sdf_Scene(Vector tv){
    vec3 p = tv.pos;
    float d = maxDist;

    float b_hyper = bound_hyper(p);
    d = min(d, (b_hyper > BOUND_MARGIN) ? b_hyper : sdf_hyper(p));

    float b_dual = bound_dual(p);
    d = min(d, (b_dual > BOUND_MARGIN) ? b_dual : sdf_dual(p));

    return d;
}

float trace_Scene(Vector tv){
    float d = maxDist;
    d = min(d, trace_key(tv));
    d = min(d, trace_room(tv));
    return d;
}
