//=====================================================================
// generated by scenegen from src/scene.js — do not edit by hand
//=====================================================================


//--- library: glsl/shapes/triangle.glsl ---
//----------------------------------------------------------------------------
// TRIANGLE — an equilateral triangular prism, `side` across, `thickness` deep
// along z (a classic dispersing prism).
//
// glsl/shapes/ is the math-only library: plain functions of a point and some
// floats. No structs, no Frame, no Material. Placement, materials and the
// region interface are emitted by the scene.
//----------------------------------------------------------------------------


// p is in the prism's own coordinates (origin at the centroid). Equilateral
// cross-section in the xy-plane, extruded along z; 0.86602 = cos(30°).
float triangleDistance(vec3 p, float side, float thickness){
    vec3 q = abs(p);
    return max(q.z - thickness, max(q.x*0.86602 + p.y*0.5, -p.y) - side*0.5);
}


//--- library: glsl/shapes/sphere.glsl ---
//----------------------------------------------------------------------------
// SPHERE
//
// glsl/shapes/ is the math-only library: plain functions of a point and some
// floats. No structs, no Frame, no Material, no at()/inside()/setData().
// Placement, materials and the region interface are emitted by the scene.
//----------------------------------------------------------------------------


// p is in the sphere's own coordinates (origin at the centre)
float sphereDistance(vec3 p, float radius){
    return length(p) - radius;
}


// Exact ray intersection, in world coordinates: the distance along tv to the
// sphere, or maxDist if it is not in front of us. tv.dir is unit length.
//
// A ray STARTING INSIDE takes the far root — glass needs that, since a
// transmitted ray has to find the far wall of the object it just entered.
float sphereTrace(Vector tv, vec3 centre, float radius){
    vec3  oc = tv.pos - centre;
    float b  = dot(oc, tv.dir);
    float c  = dot(oc, oc) - radius*radius;
    float disc = b*b - c;
    if(disc < 0.){ return maxDist; }

    float s = sqrt(disc);
    float t = -b - s;
    if(t < 0.){ t = -b + s; }
    if(t < 0.){ return maxDist; }
    return min(t, maxDist);
}


//--- library: glsl/shapes/room.glsl ---
//----------------------------------------------------------------------------
// ROOM — a closed box, seen from the inside.
//
// The room is ONE region whose solid is everything OUTSIDE the box, so the
// interior is open air and regionAt() returns ID_NONE there. Its six walls are
// not six objects: they are a material FIELD over that one region, read off by
// asking which face a point is nearest. roomFace() answers that.
//
// glsl/shapes/ is the math-only library: plain functions of a point and some
// floats. No structs, no Frame, no Material.
//----------------------------------------------------------------------------


const int ROOM_FLOOR   = 0;
const int ROOM_CEILING = 1;
const int ROOM_LEFT    = 2;
const int ROOM_RIGHT   = 3;
const int ROOM_FRONT   = 4;
const int ROOM_BACK    = 5;


// p is in the room's own coordinates (origin at the box centre).
// Negative in the WALLS, positive in the open interior — the sign convention
// every other region uses, just turned inside out.
float roomDistance(vec3 p, vec3 halfSize){
    return -bBox(p, halfSize);
}


// Exact ray intersection, in world coordinates. The ray is inside the box, so
// this is simply the distance at which it leaves: the nearest of the three
// far slab crossings.
float roomTrace(Vector tv, vec3 centre, vec3 halfSize){
    vec3  o  = tv.pos - centre;
    vec3  tm = max((-halfSize - o)/tv.dir, (halfSize - o)/tv.dir);
    float t  = min(tm.x, min(tm.y, tm.z));
    if(t < 0.){ return maxDist; }
    return min(t, maxDist);
}


// Which wall p is on (or nearest to). d is negative inside the room, so its
// LARGEST component names the axis the point is closest to leaving through,
// and the sign of p picks which of that axis's two faces.
int roomFace(vec3 p, vec3 halfSize){
    vec3 d = abs(p) - halfSize;

    if(d.y >= d.x && d.y >= d.z){
        return (p.y > 0.) ? ROOM_CEILING : ROOM_FLOOR;
    }
    if(d.x >= d.z){
        return (p.x > 0.) ? ROOM_RIGHT : ROOM_LEFT;
    }
    return (p.z > 0.) ? ROOM_BACK : ROOM_FRONT;
}


//--- the objects, in declaration order (= containment priority, inner to outer)
const int ID_PRISM = 0;
const int ID_LIGHT = 1;
const int ID_ROOM  = 2;

const int N_OBJ = 3;
float gSDF[N_OBJ];


//--- placement and shape parameters ----------------------------------
const vec3  PRISM_P         = vec3(0.0, 2.0, 0.0);
const vec3  PRISM_AXIS      = vec3(0.0, 0.0, 1.0);
const float PRISM_SIDE      = 4.0;
const float PRISM_THICKNESS = 2.5;

const vec3  LIGHT_P      = vec3(9.0, 4.0, -12.0);
const float LIGHT_RADIUS = 1.5;

const vec3 ROOM_P        = vec3(0.0, 12.0, -7.0);
const vec3 ROOM_HALFSIZE = vec3(30.0, 14.0, 23.0);


//---------------------------------------------------------------------
// the region sdfs
//---------------------------------------------------------------------

vec3 toLocal_prism(vec3 p){
    mat3 rot = rot3AxisAngle(normalize(PRISM_AXIS), 12.0);
    return (p - PRISM_P) * rot;
}

float sdf_prism(vec3 p){
    float d = triangleDistance(toLocal_prism(p), PRISM_SIDE, PRISM_THICKNESS);
    return d;
}

float sdf_light(vec3 p){
    return sphereDistance(p - LIGHT_P, LIGHT_RADIUS);
}

//the room SOLID is everything outside the box, so its interior is open air and
//regionAt() returns ID_NONE there
float sdf_room(vec3 p){
    return roomDistance(p - ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the normals — the 4-tap of each region's own sdf, in world coordinates
//---------------------------------------------------------------------
const float NRM_E = 0.0002;

Vector normal_prism(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_prism(p + k.xyy*NRM_E) + k.yyx*sdf_prism(p + k.yyx*NRM_E)
                              + k.yxy*sdf_prism(p + k.yxy*NRM_E) + k.xxx*sdf_prism(p + k.xxx*NRM_E) ));
}

Vector normal_light(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_light(p + k.xyy*NRM_E) + k.yyx*sdf_light(p + k.yyx*NRM_E)
                              + k.yxy*sdf_light(p + k.yxy*NRM_E) + k.xxx*sdf_light(p + k.xxx*NRM_E) ));
}

Vector normal_room(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_room(p + k.xyy*NRM_E) + k.yyx*sdf_room(p + k.yyx*NRM_E)
                              + k.yxy*sdf_room(p + k.yxy*NRM_E) + k.xxx*sdf_room(p + k.xxx*NRM_E) ));
}


//---------------------------------------------------------------------
// the materials
//  material_ gives the Surface plus this object's own Medium; medium_ gives
//  only the Medium, for when the object is merely the far side
//---------------------------------------------------------------------

Medium medium_prism(vec3 p){
    Medium m = defaultMedium();
    m.ior    = ior;
    m.absorb = vec3(0.0);
    return m;
}
Material material_prism(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //glass
    m.interior = medium_prism(p);
    m.surf.transmit = 1.0;
    return m;
}

Material material_light(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //light
    m.surf.emit = lightPower*vec3(1.0);
    return m;
}
Medium   medium_light  (vec3 p){ return defaultMedium(); }

Material material_room(vec3 p, inout Vector n){
    vec3 q = p - ROOM_P;
    int face = roomFace(q, /*half*/vec3(30.0, 14.0, 23.0));

    if(face == ROOM_CEILING){ return makeLight(vec3(1.0), roomLight); }
    if(face == ROOM_FLOOR)  { return makeGloss(floorColor, 0.0, wallRough); }
    if(face == ROOM_LEFT)   { return makeGloss(warmColor,  0.0, wallRough); }
    if(face == ROOM_RIGHT)  { return makeGloss(coolColor,  0.0, wallRough); }
    return makeGloss(wallColor, 0.0, wallRough);
}
Medium medium_room(vec3 p){ return defaultMedium(); }


//---------------------------------------------------------------------
// the analytic intersections
//---------------------------------------------------------------------

float trace_light(Vector tv){
    return sphereTrace(tv, LIGHT_P, LIGHT_RADIUS);
}

float trace_room(Vector tv){
    return roomTrace(tv, ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the dispatchers
//---------------------------------------------------------------------

void sdfAll(vec3 p){
    gSDF[ID_PRISM] = sdf_prism(p);
    gSDF[ID_LIGHT] = sdf_light(p);
    gSDF[ID_ROOM ] = sdf_room(p);
}

Vector normalOf(int id, vec3 p){
    if(id == ID_PRISM){ return normal_prism(p); }
    if(id == ID_LIGHT){ return normal_light(p); }
    return normal_room(p);
}

//no sheets in this scene: every object is a region with an interior
bool isSheet(int id){ return false; }

Material materialOf(int id, vec3 p, inout Vector n, bool front){
    if(id == ID_PRISM){ return material_prism(p, n); }
    if(id == ID_LIGHT){ return material_light(p, n); }
    return material_room(p, n);
}

Medium mediumOf(int id, vec3 p){
    if(id == ID_PRISM){ return medium_prism(p); }
    if(id == ID_LIGHT){ return medium_light(p); }
    if(id == ID_ROOM ){ return medium_room(p); }
    return defaultMedium();      //ID_NONE: open air
}


//---------------------------------------------------------------------
// the entry points
//---------------------------------------------------------------------

void buildScene(){}

float sdf_Scene(Vector tv){
    vec3 p = tv.pos;
    float d = maxDist;

    d = min(d, sdf_prism(p));

    return d;
}

float trace_Scene(Vector tv){
    float d = maxDist;
    d = min(d, trace_light(tv));
    d = min(d, trace_room(tv));
    return d;
}
