//=====================================================================
// generated by scenegen from src/scene.js — do not edit by hand
//=====================================================================


//--- library: glsl/shapes/environments/room.glsl ---
//----------------------------------------------------------------------------
// ROOM — a closed box, seen from the inside.
//
// The room is ONE region whose solid is everything OUTSIDE the box, so the
// interior is open air and regionAt() returns ID_NONE there. Its six walls are
// not six objects: they are a material FIELD over that one region, read off by
// asking which face a point is nearest. roomFace() answers that.
//
// glsl/shapes/ is the math-only library: plain functions of a point and some
// floats. No structs, no Frame, no Material.
//----------------------------------------------------------------------------


const int ROOM_FLOOR   = 0;
const int ROOM_CEILING = 1;
const int ROOM_LEFT    = 2;
const int ROOM_RIGHT   = 3;
const int ROOM_FRONT   = 4;
const int ROOM_BACK    = 5;


// p is in the room's own coordinates (origin at the box centre).
// Negative in the WALLS, positive in the open interior — the sign convention
// every other region uses, just turned inside out.
float roomDistance(vec3 p, vec3 halfSize){
    return -boxDistance(p, halfSize);
}


// Exact ray intersection, in world coordinates. The ray is inside the box, so
// this is simply the distance at which it leaves: the nearest of the three
// far slab crossings.
float roomTrace(Vector tv, vec3 centre, vec3 halfSize){
    vec3  o  = tv.pos - centre;
    vec3  tm = max((-halfSize - o)/tv.dir, (halfSize - o)/tv.dir);
    float t  = min(tm.x, min(tm.y, tm.z));
    if(t < 0.){ return maxDist; }
    return min(t, maxDist);
}


// Which wall p is on (or nearest to) — a shape DATA output (docs/shape-data.md):
// a material that reads `faceData` gets it injected. d is negative inside the
// room, so its LARGEST component names the axis the point is closest to leaving
// through, and the sign of p picks which of that axis's two faces.
int roomFaceData(vec3 p, vec3 halfSize){
    vec3 d = abs(p) - halfSize;

    if(d.y >= d.x && d.y >= d.z){
        return (p.y > 0.) ? ROOM_CEILING : ROOM_FLOOR;
    }
    if(d.x >= d.z){
        return (p.x > 0.) ? ROOM_RIGHT : ROOM_LEFT;
    }
    return (p.z > 0.) ? ROOM_BACK : ROOM_FRONT;
}


//--- the objects, in declaration order (= containment priority, inner to outer)
const int ID_CUP    = 0;
const int ID_DRINK  = 1;
const int ID_MARBLE = 2;
const int ID_ROCK   = 3;
const int ID_LAMP   = 4;
const int ID_ROOM   = 5;

const int N_OBJ = 6;
float gSDF[N_OBJ];


//--- placement and shape parameters ----------------------------------
const vec3 TUMBLER_P = vec3(-2.9, 1.3, 0.0);
const float CUP_R   = 1.1;             //outer radius
const float CUP_H   = 1.3;             //outer half-height
const float CAV_R   = 0.95;            //cavity radius  -> 0.15 wall
const float CAV_H   = 1.15;            //cavity half-height
const float CAV_Y   = 0.3;             //cavity centre, raised to leave a base
const float WATER_Y = 0.5;             //waterline, in cup-local y

const vec3  MARBLE_P      = vec3(0.0, 1.3, 0.0);
const float MARBLE_RADIUS = 1.3;

const vec3  ROCK_P      = vec3(2.9, 1.35, 0.0);
const float ROCK_RADIUS = 1.05;

const vec3  LAMP_P      = vec3(-1.5, 8.2, 3.5);
const float LAMP_RADIUS = 0.9;

const vec3 ROOM_P        = vec3(0.0, 6.0, 0.0);
const vec3 ROOM_HALFSIZE = vec3(10.0, 6.0, 10.0);


//---------------------------------------------------------------------
// the fields — shared functions of a local point,
//  usable by sdfs (displacement) and materials (colour) alike
//---------------------------------------------------------------------

float rockHeight(vec3 q){
    return fbm2(2.5*q) - 0.5;
}


//---------------------------------------------------------------------
// the region sdfs
//---------------------------------------------------------------------

void sdf_tumbler(vec3 p, out float cup, out float drink){
    vec3  q = p - TUMBLER_P;
    float outer  = cylinderDistance(q, CUP_R, CUP_H, 0.08);
    float cavity = cylinderDistance(q - vec3(0.0, CAV_Y, 0.0), CAV_R, CAV_H, 0.05);
    cup   = max(outer, -cavity);
    drink = max(cavity, q.y - WATER_Y);
}

//single-region entry points, for the 4-tap normals
float sdf_cup(vec3 p){ float cup, drink; sdf_tumbler(p, cup, drink); return cup; }
float sdf_drink(vec3 p){ float cup, drink; sdf_tumbler(p, cup, drink); return drink; }

float sdf_marble(vec3 p){
    return sphereDistance(p - MARBLE_P, MARBLE_RADIUS);
}

float sdf_rock(vec3 p){
    vec3  q = p - ROCK_P;
    float d = sphereDistance(q, ROCK_RADIUS);
    d += 0.18*rockHeight(q);
    return d/(1.0 + 0.18*(2.01*2.5));
}

float sdf_lamp(vec3 p){
    return sphereDistance(p - LAMP_P, LAMP_RADIUS);
}

//the room SOLID is everything outside the box, so its interior is open air and
//regionAt() returns ID_NONE there
float sdf_room(vec3 p){
    return roomDistance(p - ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the bounds — the acceleration structure (sdf_Scene only; sdfAll stays exact)
//---------------------------------------------------------------------

float bound_tumbler(vec3 p){
    vec3 q = p - TUMBLER_P;
    return cylinderSlab(q, CUP_R + 0.15, CUP_H + 0.15);
}

float bound_rock(vec3 p){
    return sphereDistance(p - ROCK_P, ROCK_RADIUS) - 0.5*0.18;
}


//---------------------------------------------------------------------
// the normals — the 4-tap of each region's own sdf, in world coordinates
//---------------------------------------------------------------------
const float NRM_E = 0.0002;

Vector normal_cup(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_cup(p + k.xyy*NRM_E) + k.yyx*sdf_cup(p + k.yyx*NRM_E)
                              + k.yxy*sdf_cup(p + k.yxy*NRM_E) + k.xxx*sdf_cup(p + k.xxx*NRM_E) ));
}

Vector normal_drink(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_drink(p + k.xyy*NRM_E) + k.yyx*sdf_drink(p + k.yyx*NRM_E)
                              + k.yxy*sdf_drink(p + k.yxy*NRM_E) + k.xxx*sdf_drink(p + k.xxx*NRM_E) ));
}

Vector normal_marble(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_marble(p + k.xyy*NRM_E) + k.yyx*sdf_marble(p + k.yyx*NRM_E)
                              + k.yxy*sdf_marble(p + k.yxy*NRM_E) + k.xxx*sdf_marble(p + k.xxx*NRM_E) ));
}

Vector normal_rock(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_rock(p + k.xyy*NRM_E) + k.yyx*sdf_rock(p + k.yyx*NRM_E)
                              + k.yxy*sdf_rock(p + k.yxy*NRM_E) + k.xxx*sdf_rock(p + k.xxx*NRM_E) ));
}

Vector normal_lamp(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_lamp(p + k.xyy*NRM_E) + k.yyx*sdf_lamp(p + k.yyx*NRM_E)
                              + k.yxy*sdf_lamp(p + k.yxy*NRM_E) + k.xxx*sdf_lamp(p + k.xxx*NRM_E) ));
}

Vector normal_room(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_room(p + k.xyy*NRM_E) + k.yyx*sdf_room(p + k.yyx*NRM_E)
                              + k.yxy*sdf_room(p + k.yxy*NRM_E) + k.xxx*sdf_room(p + k.xxx*NRM_E) ));
}


//---------------------------------------------------------------------
// the materials
//  material_ gives the Surface plus this object's own Medium; medium_ gives
//  only the Medium, for when the object is merely the far side
//---------------------------------------------------------------------

Medium medium_cup(vec3 p){
    Medium m = defaultMedium();
    m.ior    = 1.5;
    m.absorb = absorbFor(vec3(0.86, 0.9, 0.88), 1.2);
    return m;
}
Material material_cup(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //glass
    m.interior = medium_cup(p);
    m.surf.transmit = 1.0;
    return m;
}

Medium medium_drink(vec3 p){
    Medium m = defaultMedium();
    m.ior    = 1.34;
    m.absorb = absorbFor(vec3(0.75, 0.22, 0.12), 0.8);
    return m;
}
Material material_drink(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //glass
    m.interior = medium_drink(p);
    m.surf.transmit = 1.0;
    return m;
}

Material material_marble(vec3 p, inout Vector n){
    vec3 q = p - MARBLE_P;
    return marbleField(q, 3.5, polish);
}
Medium medium_marble(vec3 p){ return defaultMedium(); }

Material material_rock(vec3 p, inout Vector n){
    vec3 q = p - ROCK_P;
    vec3 tone = mix(vec3(0.38,0.35,0.32), vec3(0.55,0.52,0.47), fbm(4.0*q));
    return makeGloss(tone, 0.03, 0.55);
}
Medium medium_rock(vec3 p){ return defaultMedium(); }

Material material_lamp(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //light
    m.surf.emit = lampPower*vec3(1.0, 0.94, 0.86);
    return m;
}
Medium   medium_lamp  (vec3 p){ return defaultMedium(); }

Material material_room(vec3 p, inout Vector n){
    vec3 q = p - ROOM_P;
    int faceData = roomFaceData(q, ROOM_HALFSIZE);
    if(faceData == ROOM_CEILING){ return makeLight(vec3(1.0), roomLight); }
    if(faceData == ROOM_FLOOR)  { return makeGloss(floorColor, 0.0, wallRough); }
    if(faceData == ROOM_LEFT)   { return makeGloss(warmColor,  0.0, wallRough); }
    if(faceData == ROOM_RIGHT)  { return makeGloss(coolColor,  0.0, wallRough); }
    return makeGloss(wallColor, 0.0, wallRough);
}
Medium medium_room(vec3 p){ return defaultMedium(); }


//---------------------------------------------------------------------
// the analytic intersections
//---------------------------------------------------------------------

float trace_marble(Vector tv){
    return sphereTrace(tv, MARBLE_P, MARBLE_RADIUS);
}

float trace_lamp(Vector tv){
    return sphereTrace(tv, LAMP_P, LAMP_RADIUS);
}

float trace_room(Vector tv){
    return roomTrace(tv, ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the dispatchers
//---------------------------------------------------------------------

void sdfAll(vec3 p){
    sdf_tumbler(p, gSDF[ID_CUP], gSDF[ID_DRINK]);
    gSDF[ID_MARBLE] = sdf_marble(p);
    gSDF[ID_ROCK  ] = sdf_rock(p);
    gSDF[ID_LAMP  ] = sdf_lamp(p);
    gSDF[ID_ROOM  ] = sdf_room(p);
}

Vector normalOf(int id, vec3 p){
    if(id == ID_CUP   ){ return normal_cup(p); }
    if(id == ID_DRINK ){ return normal_drink(p); }
    if(id == ID_MARBLE){ return normal_marble(p); }
    if(id == ID_ROCK  ){ return normal_rock(p); }
    if(id == ID_LAMP  ){ return normal_lamp(p); }
    return normal_room(p);
}

//no sheets in this scene: every object is a region with an interior
bool isSheet(int id){ return false; }

Material materialOf(int id, vec3 p, inout Vector n, bool front){
    if(id == ID_CUP   ){ return material_cup(p, n); }
    if(id == ID_DRINK ){ return material_drink(p, n); }
    if(id == ID_MARBLE){ return material_marble(p, n); }
    if(id == ID_ROCK  ){ return material_rock(p, n); }
    if(id == ID_LAMP  ){ return material_lamp(p, n); }
    return material_room(p, n);
}

Medium mediumOf(int id, vec3 p){
    if(id == ID_CUP   ){ return medium_cup(p); }
    if(id == ID_DRINK ){ return medium_drink(p); }
    if(id == ID_MARBLE){ return medium_marble(p); }
    if(id == ID_ROCK  ){ return medium_rock(p); }
    if(id == ID_LAMP  ){ return medium_lamp(p); }
    if(id == ID_ROOM  ){ return medium_room(p); }
    return defaultMedium();      //ID_NONE: open air
}


//---------------------------------------------------------------------
// the entry points
//---------------------------------------------------------------------

void buildScene(){}

float sdf_Scene(Vector tv){
    vec3 p = tv.pos;
    float d = maxDist;

    float b_tumbler = bound_tumbler(p);
    if(b_tumbler > BOUND_MARGIN){ d = min(d, b_tumbler); }
    else{
        float cup, drink;
        sdf_tumbler(p, cup, drink);
        d = min(d, min(cup, drink));
    }

    float b_rock = bound_rock(p);
    d = min(d, (b_rock > BOUND_MARGIN) ? b_rock : sdf_rock(p));

    return d;
}

float trace_Scene(Vector tv){
    float d = maxDist;
    d = min(d, trace_marble(tv));
    d = min(d, trace_lamp(tv));
    d = min(d, trace_room(tv));
    return d;
}
