//=====================================================================
// generated by scenegen from src/scene.js — do not edit by hand
//=====================================================================


//--- library: glsl/shapes/sphere.glsl ---
//----------------------------------------------------------------------------
// SPHERE
//
// glsl/shapes/ is the math-only library: plain functions of a point and some
// floats. No structs, no Frame, no Material, no at()/inside()/setData().
// Placement, materials and the region interface are emitted by the scene.
//----------------------------------------------------------------------------


// p is in the sphere's own coordinates (origin at the centre)
float sphereDistance(vec3 p, float radius){
    return length(p) - radius;
}


// Exact ray intersection, in world coordinates: the distance along tv to the
// sphere, or maxDist if it is not in front of us. tv.dir is unit length.
//
// A ray STARTING INSIDE takes the far root — glass needs that, since a
// transmitted ray has to find the far wall of the object it just entered.
float sphereTrace(Vector tv, vec3 centre, float radius){
    vec3  oc = tv.pos - centre;
    float b  = dot(oc, tv.dir);
    float c  = dot(oc, oc) - radius*radius;
    float disc = b*b - c;
    if(disc < 0.){ return maxDist; }

    float s = sqrt(disc);
    float t = -b - s;
    if(t < 0.){ t = -b + s; }
    if(t < 0.){ return maxDist; }
    return min(t, maxDist);
}


Material sheetFace(vec3 tint, float gloss){
    Material m;
    initMat(m);
    m.surf.transmit     = 1.0;
    m.surf.transmitTint = tint;
    m.surf.gloss        = gloss;
    m.surf.roughness    = 0.04;
    return m;
}


//--- the objects, in declaration order (= containment priority, inner to outer)
const int ID_BUBBLE = 0;
const int ID_BALL   = 1;

const int N_OBJ = 2;
float gSDF[N_OBJ];


//--- placement and shape parameters ----------------------------------
const vec3  BUBBLE_P      = vec3(1.6, 1.3, -1.2);
const float BUBBLE_RADIUS = 1.3;

const vec3  BALL_P      = vec3(-1.6, 1.3, -1.2);
const float BALL_RADIUS = 1.3;


//---------------------------------------------------------------------
// the region sdfs
//---------------------------------------------------------------------

float sdf_bubble(vec3 p){
    return sphereDistance(p - BUBBLE_P, BUBBLE_RADIUS);
}

float sdf_ball(vec3 p){
    return sphereDistance(p - BALL_P, BALL_RADIUS);
}


//---------------------------------------------------------------------
// the normals — the 4-tap of each region's own sdf, in world coordinates
//---------------------------------------------------------------------
const float NRM_E = 0.0002;

Vector normal_bubble(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_bubble(p + k.xyy*NRM_E) + k.yyx*sdf_bubble(p + k.yyx*NRM_E)
                              + k.yxy*sdf_bubble(p + k.yxy*NRM_E) + k.xxx*sdf_bubble(p + k.xxx*NRM_E) ));
}

Vector normal_ball(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_ball(p + k.xyy*NRM_E) + k.yyx*sdf_ball(p + k.yyx*NRM_E)
                              + k.yxy*sdf_ball(p + k.yxy*NRM_E) + k.xxx*sdf_ball(p + k.xxx*NRM_E) ));
}


//---------------------------------------------------------------------
// the materials
//  material_ gives the Surface plus this object's own Medium; medium_ gives
//  only the Medium, for when the object is merely the far side
//---------------------------------------------------------------------

Material material_bubble(vec3 p, inout Vector n, bool front){
    if(front){ return sheetFace(frontTint, sheetGloss); }
    return sheetFace(backTint, sheetGloss);
}
Medium medium_bubble(vec3 p){ return defaultMedium(); }

Medium medium_ball(vec3 p){
    Medium m = defaultMedium();
    m.ior    = ballIOR;
    m.absorb = absorbFor(vec3(0.8, 0.88, 0.92), 2.0);
    return m;
}
Material material_ball(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //glass
    m.interior = medium_ball(p);
    m.surf.transmit = 1.0;
    return m;
}


//---------------------------------------------------------------------
// the analytic intersections
//---------------------------------------------------------------------

float trace_bubble(Vector tv){
    return sphereTrace(tv, BUBBLE_P, BUBBLE_RADIUS);
}

float trace_ball(Vector tv){
    return sphereTrace(tv, BALL_P, BALL_RADIUS);
}


//---------------------------------------------------------------------
// the dispatchers
//---------------------------------------------------------------------

void sdfAll(vec3 p){
    gSDF[ID_BUBBLE] = sdf_bubble(p);
    gSDF[ID_BALL  ] = sdf_ball(p);
}

Vector normalOf(int id, vec3 p){
    if(id == ID_BUBBLE){ return normal_bubble(p); }
    return normal_ball(p);
}

//sheets: two-sided surfaces with no interior, excluded from containment
bool isSheet(int id){ return id == ID_BUBBLE; }

Material materialOf(int id, vec3 p, inout Vector n, bool front){
    if(id == ID_BUBBLE){ return material_bubble(p, n, front); }
    return material_ball(p, n);
}

Medium mediumOf(int id, vec3 p){
    if(id == ID_BUBBLE){ return medium_bubble(p); }
    if(id == ID_BALL  ){ return medium_ball(p); }
    return defaultMedium();      //ID_NONE: open air
}


//---------------------------------------------------------------------
// the entry points
//---------------------------------------------------------------------

void buildScene(){}

//nothing marches: every surface here has a closed-form intersection
float sdf_Scene(Vector tv){
    return maxDist;
}

float trace_Scene(Vector tv){
    float d = maxDist;
    d = min(d, trace_bubble(tv));
    d = min(d, trace_ball(tv));
    return d;
}
