//=====================================================================
// generated by scenegen from src/scene.js — do not edit by hand
//=====================================================================


//--- library: glsl/shapes/variety.glsl ---
//@noshape — helpers, not a catalogue shape: the variety builder is its own
//           (carefully designed) piece of the generator, still to come
//----------------------------------------------------------------------------
// ALGEBRAIC VARIETIES
//
// A variety is not authored as a distance function. It is authored as an
// EQUATION — `T eqn(T x, T y, T z)` in dual numbers, from the catalogue in
// glsl/objects/varieties/formulas/ — and everything else is derived:
//
//   1. the gradient        three dual-number evaluations, one per partial.
//                          GENERATED per equation: it is four lines of glue
//                          from the equation's name and nothing else.
//   2. the distance        DE(value, |gradient|) — a first-order estimate of the
//                          distance to the zero set (1Setup/dualNumbers.glsl).
//   3. finite extent       the zero set is unbounded, so it is CLIPPED to some
//                          shape with smax.
//   4. thickness           a level set is infinitely thin. Left alone it is a
//                          SHEET; thickened it becomes a REGION with an inside.
//
// So the author supplies: an equation, a clip shape, a thickness (or none), and
// a bound. That is the whole of a variety object.
//
// This file holds 2 and 4. The gradient is generated; the clip and the bound are
// ordinary shapes from elsewhere in glsl/shapes/.
//----------------------------------------------------------------------------


// data.xyz = gradient, data.w = value, both at the SCALED point. `scale` is the
// variety's internal zoom: the chain rule puts it on the gradient, which keeps
// the returned distance in the object's own local units.
float varietyDistance(vec4 data, float scale){
    return DE(data.w, length(data.xyz)*scale);
}


// Thicken a level set into a shell with a real inside. `inner` pushes the
// surface inward, `outer` outward, so the shell's total thickness is
// inner + outer — keep that comfortably above 2*AT_THRESH or the classifier
// cannot tell the two faces apart.
//
// Leave this OFF to keep the variety a sheet: infinitely thin, two-sided, no
// interior and no refraction.
float varietyShell(float dist, float inner, float outer){
    return abs(dist + inner) - inner - outer;
}


//--- library: glsl/shapes/environments/room.glsl ---
//----------------------------------------------------------------------------
// ROOM — a closed box, seen from the inside.
//
// The room is ONE region whose solid is everything OUTSIDE the box, so the
// interior is open air and regionAt() returns ID_NONE there. Its six walls are
// not six objects: they are a material FIELD over that one region, read off by
// asking which face a point is nearest. roomFace() answers that.
//
// glsl/shapes/ is the math-only library: plain functions of a point and some
// floats. No structs, no Frame, no Material.
//----------------------------------------------------------------------------


const int ROOM_FLOOR   = 0;
const int ROOM_CEILING = 1;
const int ROOM_LEFT    = 2;
const int ROOM_RIGHT   = 3;
const int ROOM_FRONT   = 4;
const int ROOM_BACK    = 5;


// p is in the room's own coordinates (origin at the box centre).
// Negative in the WALLS, positive in the open interior — the sign convention
// every other region uses, just turned inside out.
float roomDistance(vec3 p, vec3 halfSize){
    return -boxDistance(p, halfSize);
}


// Exact ray intersection, in world coordinates. The ray is inside the box, so
// this is simply the distance at which it leaves: the nearest of the three
// far slab crossings.
float roomTrace(Vector tv, vec3 centre, vec3 halfSize){
    vec3  o  = tv.pos - centre;
    vec3  tm = max((-halfSize - o)/tv.dir, (halfSize - o)/tv.dir);
    float t  = min(tm.x, min(tm.y, tm.z));
    if(t < 0.){ return maxDist; }
    return min(t, maxDist);
}


// Which wall p is on (or nearest to) — a shape DATA output (docs/shape-data.md):
// a material that reads `faceData` gets it injected. d is negative inside the
// room, so its LARGEST component names the axis the point is closest to leaving
// through, and the sign of p picks which of that axis's two faces.
int roomFaceData(vec3 p, vec3 halfSize){
    vec3 d = abs(p) - halfSize;

    if(d.y >= d.x && d.y >= d.z){
        return (p.y > 0.) ? ROOM_CEILING : ROOM_FLOOR;
    }
    if(d.x >= d.z){
        return (p.x > 0.) ? ROOM_RIGHT : ROOM_LEFT;
    }
    return (p.z > 0.) ? ROOM_BACK : ROOM_FRONT;
}


//--- the objects, in declaration order (= containment priority, inner to outer)
const int ID_HESSE   = 0;
const int ID_CHMUTOV = 1;
const int ID_LAMP    = 2;
const int ID_ROOM    = 3;

const int N_OBJ = 4;
float gSDF[N_OBJ];


//--- placement and shape parameters ----------------------------------
const vec3  HESSE_P           = vec3(-2.2, 1.9, -1.0);
const float HESSE_CLIP_RADIUS = 1.8;

const vec3  CHMUTOV_P           = vec3(2.2, 1.9, -1.0);
const float CHMUTOV_CLIP_RADIUS = 1.8;
const float CHMUTOV_CLIP_BLEND  = 0.06;

const vec3  LAMP_P      = vec3(-4.0, 8.5, 5.0);
const float LAMP_RADIUS = 1.4;

const vec3 ROOM_P        = vec3(0.0, 6.0, 0.0);
const vec3 ROOM_HALFSIZE = vec3(10.0, 6.0, 10.0);


//---------------------------------------------------------------------
// the region sdfs
//---------------------------------------------------------------------

vec4 data_hesse(vec3 p){
    vec4 x = vec4(p.x, 1.0, 0.0, 0.0);
    vec4 y = vec4(p.y, 0.0, 1.0, 0.0);
    vec4 z = vec4(p.z, 0.0, 0.0, 1.0);
    vec4 x2 = tsqr(x);
    vec4 x3 = tmul(x2, x);
    vec4 y2 = tsqr(y);
    vec4 y3 = tmul(y2, y);
    vec4 z2 = tsqr(z);
    vec4 z3 = tmul(z2, z);
    vec4 v = x3 + y3 + z3 - 3.0*a*tmul(x, y, z);
    return v.yzwx;
}

float sdf_hesse(vec3 p){
    float d = varietyDistance(data_hesse(p - HESSE_P), 1.0);
    return max(d, sphereDistance(p - HESSE_P, HESSE_CLIP_RADIUS));
}

vec4 cheb(vec4 x, int n){
    for(int i = 0; i < n; i++){
        x = 2.0*tmul(x, x) - vec4(1.0, 0.0, 0.0, 0.0);
    }
    return x;
}

vec4 chmutov(vec4 x, vec4 y, vec4 z){
    int n = 2;
    return cheb(x, n) + cheb(y, n) + cheb(z, n) + vec4(1.0, 0.0, 0.0, 0.0);
}

vec4 data_chmutov(vec3 p){
    vec4 x = vec4(p.x, 1.0, 0.0, 0.0);
    vec4 y = vec4(p.y, 0.0, 1.0, 0.0);
    vec4 z = vec4(p.z, 0.0, 0.0, 1.0);
    vec4 v = chmutov(x, y, z);
    return v.yzwx;
}

float sdf_chmutov(vec3 p){
    float d = varietyDistance(data_chmutov(p - CHMUTOV_P), 1.0);
    return smax(d, sphereDistance(p - CHMUTOV_P, CHMUTOV_CLIP_RADIUS), CHMUTOV_CLIP_BLEND);
}

float sdf_lamp(vec3 p){
    return sphereDistance(p - LAMP_P, LAMP_RADIUS);
}

//the room SOLID is everything outside the box, so its interior is open air and
//regionAt() returns ID_NONE there
float sdf_room(vec3 p){
    return roomDistance(p - ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the bounds — the acceleration structure (sdf_Scene only; sdfAll stays exact)
//---------------------------------------------------------------------

float bound_hesse(vec3 p){
    return sphereDistance(p - HESSE_P, HESSE_CLIP_RADIUS);
}

float bound_chmutov(vec3 p){
    return sphereDistance(p - CHMUTOV_P, CHMUTOV_CLIP_RADIUS) - CHMUTOV_CLIP_BLEND;
}


//---------------------------------------------------------------------
// the normals — the 4-tap of each region's own sdf, in world coordinates
//---------------------------------------------------------------------
const float NRM_E = 0.0002;

Vector normal_hesse(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_hesse(p + k.xyy*NRM_E) + k.yyx*sdf_hesse(p + k.yyx*NRM_E)
                              + k.yxy*sdf_hesse(p + k.yxy*NRM_E) + k.xxx*sdf_hesse(p + k.xxx*NRM_E) ));
}

Vector normal_chmutov(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_chmutov(p + k.xyy*NRM_E) + k.yyx*sdf_chmutov(p + k.yyx*NRM_E)
                              + k.yxy*sdf_chmutov(p + k.yxy*NRM_E) + k.xxx*sdf_chmutov(p + k.xxx*NRM_E) ));
}

Vector normal_lamp(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_lamp(p + k.xyy*NRM_E) + k.yyx*sdf_lamp(p + k.yyx*NRM_E)
                              + k.yxy*sdf_lamp(p + k.yxy*NRM_E) + k.xxx*sdf_lamp(p + k.xxx*NRM_E) ));
}

Vector normal_room(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_room(p + k.xyy*NRM_E) + k.yyx*sdf_room(p + k.yyx*NRM_E)
                              + k.yxy*sdf_room(p + k.yxy*NRM_E) + k.xxx*sdf_room(p + k.xxx*NRM_E) ));
}


//---------------------------------------------------------------------
// the materials
//  material_ gives the Surface plus this object's own Medium; medium_ gives
//  only the Medium, for when the object is merely the far side
//---------------------------------------------------------------------

Material material_hesse(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //gloss
    m.surf.diffuse   = vec3(0.75, 0.33, 0.24);
    m.surf.roughness = 0.3;
    m.surf.gloss     = 0.06;
    return m;
}
Medium   medium_hesse  (vec3 p){ return defaultMedium(); }

Material material_chmutov(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //gloss
    m.surf.diffuse   = vec3(0.3, 0.42, 0.58);
    m.surf.roughness = 0.3;
    m.surf.gloss     = 0.06;
    return m;
}
Medium   medium_chmutov  (vec3 p){ return defaultMedium(); }

Material material_lamp(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //light
    m.surf.emit = lampPower*vec3(1.0, 0.95, 0.88);
    return m;
}
Medium   medium_lamp  (vec3 p){ return defaultMedium(); }

Material material_room(vec3 p, inout Vector n){
    vec3 q = p - ROOM_P;
    int faceData = roomFaceData(q, ROOM_HALFSIZE);
    if(faceData == ROOM_CEILING){ return makeLight(vec3(1.0), roomLight); }
    if(faceData == ROOM_FLOOR)  { return makeGloss(floorColor, 0.0, wallRough); }
    if(faceData == ROOM_LEFT)   { return makeGloss(warmColor,  0.0, wallRough); }
    if(faceData == ROOM_RIGHT)  { return makeGloss(coolColor,  0.0, wallRough); }
    return makeGloss(wallColor, 0.0, wallRough);
}
Medium medium_room(vec3 p){ return defaultMedium(); }


//---------------------------------------------------------------------
// the analytic intersections
//---------------------------------------------------------------------

float trace_lamp(Vector tv){
    return sphereTrace(tv, LAMP_P, LAMP_RADIUS);
}

float trace_room(Vector tv){
    return roomTrace(tv, ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the dispatchers
//---------------------------------------------------------------------

void sdfAll(vec3 p){
    gSDF[ID_HESSE  ] = sdf_hesse(p);
    gSDF[ID_CHMUTOV] = sdf_chmutov(p);
    gSDF[ID_LAMP   ] = sdf_lamp(p);
    gSDF[ID_ROOM   ] = sdf_room(p);
}

Vector normalOf(int id, vec3 p){
    if(id == ID_HESSE  ){ return normal_hesse(p); }
    if(id == ID_CHMUTOV){ return normal_chmutov(p); }
    if(id == ID_LAMP   ){ return normal_lamp(p); }
    return normal_room(p);
}

//no sheets in this scene: every object is a region with an interior
bool isSheet(int id){ return false; }

Material materialOf(int id, vec3 p, inout Vector n, bool front){
    if(id == ID_HESSE  ){ return material_hesse(p, n); }
    if(id == ID_CHMUTOV){ return material_chmutov(p, n); }
    if(id == ID_LAMP   ){ return material_lamp(p, n); }
    return material_room(p, n);
}

Medium mediumOf(int id, vec3 p){
    if(id == ID_HESSE  ){ return medium_hesse(p); }
    if(id == ID_CHMUTOV){ return medium_chmutov(p); }
    if(id == ID_LAMP   ){ return medium_lamp(p); }
    if(id == ID_ROOM   ){ return medium_room(p); }
    return defaultMedium();      //ID_NONE: open air
}


//---------------------------------------------------------------------
// the entry points
//---------------------------------------------------------------------

void buildScene(){}

float sdf_Scene(Vector tv){
    vec3 p = tv.pos;
    float d = maxDist;

    float b_hesse = bound_hesse(p);
    d = min(d, (b_hesse > BOUND_MARGIN) ? b_hesse : sdf_hesse(p));

    float b_chmutov = bound_chmutov(p);
    d = min(d, (b_chmutov > BOUND_MARGIN) ? b_chmutov : sdf_chmutov(p));

    return d;
}

float trace_Scene(Vector tv){
    float d = maxDist;
    d = min(d, trace_lamp(tv));
    d = min(d, trace_room(tv));
    return d;
}
