//=====================================================================
// generated by scenegen from src/scene.js — do not edit by hand
//=====================================================================


//--- library: glsl/shapes/sphere.glsl ---
//----------------------------------------------------------------------------
// SPHERE
//
// glsl/shapes/ is the math-only library: plain functions of a point and some
// floats. No structs, no Frame, no Material, no at()/inside()/setData().
// Placement, materials and the region interface are emitted by the scene.
//----------------------------------------------------------------------------


// p is in the sphere's own coordinates (origin at the centre)
float sphereDistance(vec3 p, float radius){
    return length(p) - radius;
}


// Exact ray intersection, in world coordinates: the distance along tv to the
// sphere, or maxDist if it is not in front of us. tv.dir is unit length.
//
// A ray STARTING INSIDE takes the far root — glass needs that, since a
// transmitted ray has to find the far wall of the object it just entered.
float sphereTrace(Vector tv, vec3 centre, float radius){
    vec3  oc = tv.pos - centre;
    float b  = dot(oc, tv.dir);
    float c  = dot(oc, oc) - radius*radius;
    float disc = b*b - c;
    if(disc < 0.){ return maxDist; }

    float s = sqrt(disc);
    float t = -b - s;
    if(t < 0.){ t = -b + s; }
    if(t < 0.){ return maxDist; }
    return min(t, maxDist);
}


//--- library: glsl/shapes/variety.glsl ---
//@noshape — helpers, not a catalogue shape: the variety builder is its own
//           (carefully designed) piece of the generator, still to come
//----------------------------------------------------------------------------
// ALGEBRAIC VARIETIES
//
// A variety is not authored as a distance function. It is authored as an
// EQUATION — `T eqn(T x, T y, T z)` in dual numbers, from the catalogue in
// glsl/objects/varieties/formulas/ — and everything else is derived:
//
//   1. the gradient        three dual-number evaluations, one per partial.
//                          GENERATED per equation: it is four lines of glue
//                          from the equation's name and nothing else.
//   2. the distance        DE(value, |gradient|) — a first-order estimate of the
//                          distance to the zero set (1Setup/dualNumbers.glsl).
//   3. finite extent       the zero set is unbounded, so it is CLIPPED to some
//                          shape with smax.
//   4. thickness           a level set is infinitely thin. Left alone it is a
//                          SHEET; thickened it becomes a REGION with an inside.
//
// So the author supplies: an equation, a clip shape, a thickness (or none), and
// a bound. That is the whole of a variety object.
//
// This file holds 2 and 4. The gradient is generated; the clip and the bound are
// ordinary shapes from elsewhere in glsl/shapes/.
//----------------------------------------------------------------------------


// data.xyz = gradient, data.w = value, both at the SCALED point. `scale` is the
// variety's internal zoom: the chain rule puts it on the gradient, which keeps
// the returned distance in the object's own local units.
float varietyDistance(vec4 data, float scale){
    return DE(data.w, length(data.xyz)*scale);
}


// Thicken a level set into a shell with a real inside. `inner` pushes the
// surface inward, `outer` outward, so the shell's total thickness is
// inner + outer — keep that comfortably above 2*AT_THRESH or the classifier
// cannot tell the two faces apart.
//
// Leave this OFF to keep the variety a sheet: infinitely thin, two-sided, no
// interior and no refraction.
float varietyShell(float dist, float inner, float outer){
    return abs(dist + inner) - inner - outer;
}


//--- library: glsl/shapes/room.glsl ---
//----------------------------------------------------------------------------
// ROOM — a closed box, seen from the inside.
//
// The room is ONE region whose solid is everything OUTSIDE the box, so the
// interior is open air and regionAt() returns ID_NONE there. Its six walls are
// not six objects: they are a material FIELD over that one region, read off by
// asking which face a point is nearest. roomFace() answers that.
//
// glsl/shapes/ is the math-only library: plain functions of a point and some
// floats. No structs, no Frame, no Material.
//----------------------------------------------------------------------------


const int ROOM_FLOOR   = 0;
const int ROOM_CEILING = 1;
const int ROOM_LEFT    = 2;
const int ROOM_RIGHT   = 3;
const int ROOM_FRONT   = 4;
const int ROOM_BACK    = 5;


// p is in the room's own coordinates (origin at the box centre).
// Negative in the WALLS, positive in the open interior — the sign convention
// every other region uses, just turned inside out.
float roomDistance(vec3 p, vec3 halfSize){
    return -bBox(p, halfSize);
}


// Exact ray intersection, in world coordinates. The ray is inside the box, so
// this is simply the distance at which it leaves: the nearest of the three
// far slab crossings.
float roomTrace(Vector tv, vec3 centre, vec3 halfSize){
    vec3  o  = tv.pos - centre;
    vec3  tm = max((-halfSize - o)/tv.dir, (halfSize - o)/tv.dir);
    float t  = min(tm.x, min(tm.y, tm.z));
    if(t < 0.){ return maxDist; }
    return min(t, maxDist);
}


// Which wall p is on (or nearest to) — a shape DATA output (docs/shape-data.md):
// a material that reads `faceData` gets it injected. d is negative inside the
// room, so its LARGEST component names the axis the point is closest to leaving
// through, and the sign of p picks which of that axis's two faces.
int roomFaceData(vec3 p, vec3 halfSize){
    vec3 d = abs(p) - halfSize;

    if(d.y >= d.x && d.y >= d.z){
        return (p.y > 0.) ? ROOM_CEILING : ROOM_FLOOR;
    }
    if(d.x >= d.z){
        return (p.x > 0.) ? ROOM_RIGHT : ROOM_LEFT;
    }
    return (p.z > 0.) ? ROOM_BACK : ROOM_FRONT;
}


//--- the objects, in declaration order (= containment priority, inner to outer)
const int ID_BARTH = 0;
const int ID_LIGHT = 1;
const int ID_ROOM  = 2;

const int N_OBJ = 3;
float gSDF[N_OBJ];


//--- placement and shape parameters ----------------------------------
const vec3  BARTH_P           = vec3(0.0, 1.9, -1.2);
const float BARTH_CLIP_RADIUS = 1.9;
const float BARTH_CLIP_BLEND  = 0.06;
const float BARTH_TAU         = 4.236068;

const vec3  LIGHT_P      = vec3(-7.0, 4.0, 2.0);
const float LIGHT_RADIUS = 1.5;

const vec3 ROOM_P        = vec3(-5.75, 6.5, -5.0);
const vec3 ROOM_HALFSIZE = vec3(14.25, 7.5, 15.0);


//---------------------------------------------------------------------
// the region sdfs
//---------------------------------------------------------------------

vec4 barthSextic(vec4 x, vec4 y, vec4 z, vec4 w, float tau){
    float phi = 0.5*(1.0 + sqrt(5.0));
    float phi2 = phi*phi;
    vec4 x2 = tmul(x, x);
    vec4 y2 = tmul(y, y);
    vec4 z2 = tmul(z, z);
    vec4 w2 = tmul(w, w);
    vec4 p1 = 4.0*tmul(phi2*x2 - y2, phi2*y2 - z2, phi2*z2 - x2);
    vec4 r2 = x2 + y2 + z2 - w2;
    return tau*tmul(r2, r2, w2) - p1;
}

vec4 data_barth(vec3 p){
    vec4 x = vec4(p.x, 1.0, 0.0, 0.0);
    vec4 y = vec4(p.y, 0.0, 1.0, 0.0);
    vec4 z = vec4(p.z, 0.0, 0.0, 1.0);
    vec4 w = vec4(1.0, 0.0, 0.0, 0.0);      //the affine patch: w = 1
    vec4 v = barthSextic(x, y, z, w, BARTH_TAU);
    return v.yzwx;
}

float sdf_barth(vec3 p){
    float d = varietyDistance(data_barth(varScale*(p - BARTH_P)), varScale);
    return smax(d, sphereDistance(p - BARTH_P, BARTH_CLIP_RADIUS), BARTH_CLIP_BLEND);
}

//the marched form: abs stops the ray on {s=0}; the hard max keeps the
//cut cap over {s<0} undrawn. sdf_barth stays signed for faces/normals.
float march_barth(vec3 p){
    float d = varietyDistance(data_barth(varScale*(p - BARTH_P)), varScale);
    return max(abs(d), sphereDistance(p - BARTH_P, BARTH_CLIP_RADIUS));
}

float sdf_light(vec3 p){
    return sphereDistance(p - LIGHT_P, LIGHT_RADIUS);
}

//the room SOLID is everything outside the box, so its interior is open air and
//regionAt() returns ID_NONE there
float sdf_room(vec3 p){
    return roomDistance(p - ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the bounds — the acceleration structure (sdf_Scene only; sdfAll stays exact)
//---------------------------------------------------------------------

float bound_barth(vec3 p){
    return sphereDistance(p - BARTH_P, BARTH_CLIP_RADIUS) - BARTH_CLIP_BLEND;
}


//---------------------------------------------------------------------
// the normals — the 4-tap of each region's own sdf, in world coordinates
//---------------------------------------------------------------------
const float NRM_E = 0.0002;

Vector normal_barth(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_barth(p + k.xyy*NRM_E) + k.yyx*sdf_barth(p + k.yyx*NRM_E)
                              + k.yxy*sdf_barth(p + k.yxy*NRM_E) + k.xxx*sdf_barth(p + k.xxx*NRM_E) ));
}

Vector normal_light(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_light(p + k.xyy*NRM_E) + k.yyx*sdf_light(p + k.yyx*NRM_E)
                              + k.yxy*sdf_light(p + k.yxy*NRM_E) + k.xxx*sdf_light(p + k.xxx*NRM_E) ));
}

Vector normal_room(vec3 p){
    vec2 k = vec2(1.0,-1.0)*0.5773;
    return Vector(p, normalize( k.xyy*sdf_room(p + k.xyy*NRM_E) + k.yyx*sdf_room(p + k.yyx*NRM_E)
                              + k.yxy*sdf_room(p + k.yxy*NRM_E) + k.xxx*sdf_room(p + k.xxx*NRM_E) ));
}


//---------------------------------------------------------------------
// the materials
//  material_ gives the Surface plus this object's own Medium; medium_ gives
//  only the Medium, for when the object is merely the far side
//---------------------------------------------------------------------

Material material_barth(vec3 p, inout Vector n, bool front){
    if(front){ return makeGloss(frontColor, sheetGloss, 0.2); }
    return makeGloss(backColor, sheetGloss, 0.2);
}
Medium medium_barth(vec3 p){ return defaultMedium(); }

Material material_light(vec3 p, inout Vector n){
    Material m = defaultMaterial();      //light
    m.surf.emit = 100.0*vec3(0.9);
    return m;
}
Medium   medium_light  (vec3 p){ return defaultMedium(); }

Material material_room(vec3 p, inout Vector n){
    vec3 q = p - ROOM_P;
    int faceData = roomFaceData(q, ROOM_HALFSIZE);
    if(faceData == ROOM_CEILING){ return makeLight(vec3(1.0), roomLight); }
    if(faceData == ROOM_FLOOR)  { return makeGloss(floorColor, 0.0, wallRough); }
    if(faceData == ROOM_LEFT)   { return makeGloss(warmColor,  0.0, wallRough); }
    if(faceData == ROOM_RIGHT)  { return makeGloss(coolColor,  0.0, wallRough); }
    return makeGloss(wallColor, 0.0, wallRough);
}
Medium medium_room(vec3 p){ return defaultMedium(); }


//---------------------------------------------------------------------
// the analytic intersections
//---------------------------------------------------------------------

float trace_light(Vector tv){
    return sphereTrace(tv, LIGHT_P, LIGHT_RADIUS);
}

float trace_room(Vector tv){
    return roomTrace(tv, ROOM_P, ROOM_HALFSIZE);
}


//---------------------------------------------------------------------
// the dispatchers
//---------------------------------------------------------------------

void sdfAll(vec3 p){
    gSDF[ID_BARTH] = sdf_barth(p);
    gSDF[ID_LIGHT] = sdf_light(p);
    gSDF[ID_ROOM ] = sdf_room(p);
}

Vector normalOf(int id, vec3 p){
    if(id == ID_BARTH){ return normal_barth(p); }
    if(id == ID_LIGHT){ return normal_light(p); }
    return normal_room(p);
}

//sheets: two-sided surfaces with no interior, excluded from containment
bool isSheet(int id){ return id == ID_BARTH; }

Material materialOf(int id, vec3 p, inout Vector n, bool front){
    if(id == ID_BARTH){ return material_barth(p, n, front); }
    if(id == ID_LIGHT){ return material_light(p, n); }
    return material_room(p, n);
}

Medium mediumOf(int id, vec3 p){
    if(id == ID_BARTH){ return medium_barth(p); }
    if(id == ID_LIGHT){ return medium_light(p); }
    if(id == ID_ROOM ){ return medium_room(p); }
    return defaultMedium();      //ID_NONE: open air
}


//---------------------------------------------------------------------
// the entry points
//---------------------------------------------------------------------

void buildScene(){}

float sdf_Scene(Vector tv){
    vec3 p = tv.pos;
    float d = maxDist;

    float b_barth = bound_barth(p);
    d = min(d, (b_barth > BOUND_MARGIN) ? b_barth : march_barth(p));

    return d;
}

float trace_Scene(Vector tv){
    float d = maxDist;
    d = min(d, trace_light(tv));
    d = min(d, trace_room(tv));
    return d;
}
