
//-------------------------------------------------
// HYPERBOLIC HONEYCOMB 2  (hyperboloid / Knighty machinery)
//
// a second regular honeycomb of H^3, using the more general HYPERBOLOID MODEL:
// points are lifted to the Minkowski hyperboloid (inner product
// hdot(p,q) = p.xyz.q.xyz - p.w*q.w), the symmetry group is generated by four
// mirror planes A/B/C/D (Coxeter reflections), and distances come from Knighty's
// distance estimator `knightyDD` fed the object's cosh/sinh "thickness". swap the
// four mirrors + three thicknesses and you get a different {p,q,r} honeycomb --
// this is the generalizable template. see [[shadertoy-integration]].
//
// like hyperbolicHoneycomb.glsl this is the UPPER-HALF-SPACE view with straight
// Euclidean sightlines: `toHyperboloid` carries the render-space z>0 point to the
// hyperboloid, and knightyDD returns a Euclidean DE our marcher can march. the
// floor plane z~0 (the ideal boundary) caps the half-space. multi-material via a
// custom setData that reads the nearest feature's color, exactly as before.
//-------------------------------------------------


// --- Coxeter mirrors + inversion (Minkowski vec4: xyz space, w time) ---
const vec4 HC2_MIRROR_A = vec4(1.0, 0.0, 0.0, 0.0);
const vec4 HC2_MIRROR_B = vec4(-0.5, 0.8660254037844386, 0.0, 0.0);
const vec4 HC2_MIRROR_C = vec4(0.0, 0.0, 1.0, 0.0);
const vec4 HC2_MIRROR_D = vec4(0.0, -0.57735026918962595, -0.92387953251128685, -0.43230397167572659);
const vec4 HC2_VERTEX   = vec4(0.0, 0.0, 0.0, 1.0);
const vec4 HC2_INV_SPHERE = vec4(0.0, 1.335519232014724, 2.1371062825819451, 2.3131871672861219);

// --- feature "thickness" as (cosh,sinh) of the hyperbolic radius ---
const float HC2_VERTEX_COSH = 1.0050041680558035;
const float HC2_VERTEX_SINH = 0.10016675001984403;
const float HC2_EDGE_COSH   = 1.0012502604383691;
const float HC2_EDGE_SINH   = 0.050020835937655016;
const float HC2_FACE_COSH   = 1.0000125000260416;
const float HC2_FACE_SINH   = 0.0050000208333593754;

// symmetric, so column/row major is irrelevant
const mat3 HC2_FACE_BD_INV = mat3(
   -0.80052367148149761,  0.23071304173459076,  0.4614260834691814,
    0.23071304173459076,  1.266841223827166,    0.53368244765433193,
    0.4614260834691814,   0.53368244765433193,  1.0673648953086636
);

const float HC2_FLOOR_Z         = 1.0e-3;
const float HC2_FLOOR_LINE_THICK = 0.008;
const int   HC2_FOLD3_ITER      = 70;   // floor-pattern fold depth

// DEs here are honest, so no fudge is needed — this stays 1.0. (A <1 factor here
// once starved the fine cells near the ideal-boundary floor: they ran out of march
// steps. The raymarcher's own over-relaxation + fallback handles step safety now;
// see glsl/tracer/6Trace/raymarch.glsl.)
const float HC2_FUDGE = 1.0;

// --- region ids (returned by region(); the scene maps them to colors) ---
const int HC2_NONE  = -1;
const int HC2_SEG_A = 0;
const int HC2_SEG_B = 1;
const int HC2_SEG_C = 2;
const int HC2_SEG_D = 3;
const int HC2_VERT  = 4;   // (HC2_VERTEX is taken by the Minkowski vertex vec4)
const int HC2_FACE  = 5;
const int HC2_FLOOR = 6;

//COLORING lives in the scene: the object exposes region() and the floor grid
//pattern floorTint() below; the scene recolors in a setData followup. see
//[[shadertoy-integration]].


//the data of the honeycomb: frame, material (roughness/specular; per-cell diffuse
//comes from the palette), and a fold-depth knob (~40 preview ... ~180 full).
struct HyperbolicHoneycomb2{
    Frame frame;
    Material mat;
    int foldIterations;
};


// -----------------------------------------------------------------------------
// Minkowski / hyperboloid helpers
// -----------------------------------------------------------------------------

float hc2_hdot(vec4 p, vec4 q){ return dot(p.xyz, q.xyz) - p.w*q.w; }

vec4 hc2_hnormalize(vec4 p){ return p * inversesqrt(-hc2_hdot(p,p)); }

float hc2_tryReflect(inout vec4 p, vec4 n){
    float k = min(0.0, hc2_hdot(p, n));
    p -= 2.0 * k * n;
    return k;
}

//fold the 4D point back into the fundamental Coxeter chamber
bool hc2_fold4d(inout vec4 p, int maxIter){
    for(int i=0;i<maxIter;i++){
        float k = 0.0;
        p.x = abs(p.x);
        k += hc2_tryReflect(p, HC2_MIRROR_B);
        k += hc2_tryReflect(p, HC2_MIRROR_C);
        k += hc2_tryReflect(p, HC2_MIRROR_D);
        if(k == 0.0) return true;
    }
    return false;
}

//half the hyperbolic sine-distance between two hyperboloid points
float hc2_hsind(vec4 p, vec4 q){
    return 0.5 * sqrt(-hc2_hdot(p-q, p-q) * hc2_hdot(p+q, p+q));
}

//Knighty's distance estimator: (cosh,sinh) of thickness + Poincare radius r
float hc2_knightyDD(float ca, float sa, float r){
    float rr = r*r;
    float cm1 = ca - 1.0;
    return (1.0 - rr) * (sa + r*cm1) /
           (1.0 + ca + rr*cm1 + 2.0*r*sa);
}

//carry a render-space z>0 point onto the Minkowski hyperboloid; out r = Poincare radius
vec4 hc2_toHyperboloid(vec3 p, out float r){
    p.z += 1.0;
    p *= 2.0 / dot(p, p);
    p.z -= 1.0;
    r = length(p);
    return vec4(2.0*p, 1.0 + r*r) / (1.0 - r*r);
}

void hc2_getDots(vec4 q, out float qV, out float qA, out float qB, out float qC, out float qD){
    qV = -q.w;
    qA = q.x;
    qB = dot(q.xyz, HC2_MIRROR_B.xyz);
    qC = q.z;
    qD = hc2_hdot(q, HC2_MIRROR_D);
}

float hc2_dVertex(vec4 p, float r, float pv){
    float ca = -pv;
    float sa = hc2_hsind(p, HC2_VERTEX);
    return hc2_knightyDD(ca*HC2_VERTEX_COSH - sa*HC2_VERTEX_SINH,
                         sa*HC2_VERTEX_COSH - ca*HC2_VERTEX_SINH, r);
}

float hc2_dSegment(vec4 p, vec4 n, float r, float pv, float pn){
    float nv = -n.w;
    float det = -1.0 - nv*nv;
    vec4 q = hc2_hnormalize(min((-nv*pv - pn)/det, 0.0) * n +
                            ((pv - pn*nv)/det) * HC2_VERTEX);
    float ca = -hc2_hdot(p, q);
    float sa = hc2_hsind(p, q);
    return hc2_knightyDD(ca*HC2_EDGE_COSH - sa*HC2_EDGE_SINH,
                         sa*HC2_EDGE_COSH - ca*HC2_EDGE_SINH, r);
}

float hc2_dFaceBD(vec4 p, float r, float pv, float pB, float pD){
    vec3 c = vec3(pv, pB, pD) * HC2_FACE_BD_INV;
    if(c.y > 0.0 || c.z > 0.0) return 1.0e5;
    vec4 q = hc2_hnormalize(c.x*HC2_VERTEX + c.y*HC2_MIRROR_B + c.z*HC2_MIRROR_D);
    float ca = -hc2_hdot(p, q);
    float sa = hc2_hsind(p, q);
    return hc2_knightyDD(ca*HC2_FACE_COSH - sa*HC2_FACE_SINH,
                         sa*HC2_FACE_COSH - ca*HC2_FACE_SINH, r);
}

float hc2_dSegments(vec4 p, float r, float pv, float pA, float pB, float pC, float pD){
    return min(
        min(hc2_dSegment(p, HC2_MIRROR_A, r, pv, pA), hc2_dSegment(p, HC2_MIRROR_B, r, pv, pB)),
        min(hc2_dSegment(p, HC2_MIRROR_C, r, pv, pC), hc2_dSegment(p, HC2_MIRROR_D, r, pv, pD))
    );
}


// -----------------------------------------------------------------------------
// the Euclidean distance estimator
// -----------------------------------------------------------------------------

float hc2_de(vec3 p, int foldIter){
    float h = p.z - HC2_FLOOR_Z;               // the ideal-boundary floor
    float r;
    vec4 q = hc2_toHyperboloid(p, r);
    hc2_fold4d(q, foldIter);

    float qV, qA, qB, qC, qD;
    hc2_getDots(q, qV, qA, qB, qC, qD);

    float dHoneycomb = min(
        hc2_dFaceBD(q, r, qV, qB, qD),
        min(hc2_dVertex(q, r, qV), hc2_dSegments(q, r, qV, qA, qB, qC, qD))
    );
    return min(h, dHoneycomb);
}


// -----------------------------------------------------------------------------
// floor grid pattern (boundary fold) + per-cell coloring
// -----------------------------------------------------------------------------

bool hc2_foldB(inout vec3 p, inout int count){
    float k = dot(p, HC2_MIRROR_B.xyz);
    if(k >= 0.0) return true;
    p -= 2.0*k*HC2_MIRROR_B.xyz;
    count += 1;
    return false;
}

bool hc2_foldSphere(inout vec3 p, inout int count){
    vec3 q = p - HC2_INV_SPHERE.xyz;
    float d2 = dot(q,q);
    if(d2 == 0.0) return true;
    float k = HC2_INV_SPHERE.w * HC2_INV_SPHERE.w / d2;
    if(k < 1.0) return true;
    p = k*q + HC2_INV_SPHERE.xyz;
    count += 1;
    return false;
}

bool hc2_fold3d(inout vec3 p, inout int count){
    for(int i=0;i<HC2_FOLD3_ITER;i++){
        bool inA = p.x >= 0.0;
        if(!inA){ p.x = -p.x; count += 1; }
        bool inB = hc2_foldB(p, count);
        bool inC = p.z >= 0.0;
        if(!inC){ p.z = -p.z; count += 1; }
        bool inD = hc2_foldSphere(p, count);
        if(inA && inB && inC && inD) return true;
    }
    return false;
}

float hc2_distABCD(vec3 p){
    return min(
        min(abs(p.x), abs(dot(p, HC2_MIRROR_B.xyz))),
        min(abs(p.z), abs(length(p - HC2_INV_SPHERE.xyz) - HC2_INV_SPHERE.w))
    );
}

vec3 hc2_planeToSphere(vec2 p){
    float r2 = dot(p,p);
    return vec3(2.0*p, r2 - 1.0) / (1.0 + r2);
}

//which region is this local point nearest? (HC2_SEG_A .. HC2_FLOOR, or HC2_NONE)
int region( vec3 pos, HyperbolicHoneycomb2 obj ){
    float h = pos.z - HC2_FLOOR_Z;
    float r;
    vec4 q = hc2_toHyperboloid(pos, r);
    if(!hc2_fold4d(q, obj.foldIterations)) return HC2_NONE;

    float qV, qA, qB, qC, qD;
    hc2_getDots(q, qV, qA, qB, qC, qD);

    float dA = hc2_dSegment(q, HC2_MIRROR_A, r, qV, qA);
    float dB = hc2_dSegment(q, HC2_MIRROR_B, r, qV, qB);
    float dC = hc2_dSegment(q, HC2_MIRROR_C, r, qV, qC);
    float dD = hc2_dSegment(q, HC2_MIRROR_D, r, qV, qD);
    float dV = hc2_dVertex(q, r, qV);
    float dF = hc2_dFaceBD(q, r, qV, qB, qD);

    float d = min(min(dF, dV), min(min(dA, dB), min(dC, dD)));
    d = min(d, h);

    if(d == h)  return HC2_FLOOR;
    if(d == dB) return HC2_SEG_B;
    if(d == dC) return HC2_SEG_C;
    if(d == dD) return HC2_SEG_D;
    if(d == dV) return HC2_VERT;
    if(d == dF) return HC2_FACE;
    return HC2_SEG_A;
}

//the floor grid pattern, tinted by scene-supplied colors (two checker tints and
//a line color). call from the scene when region()==HC2_FLOOR.
vec3 floorTint( vec2 xy, HyperbolicHoneycomb2 obj, vec3 c1, vec3 c2, vec3 cLine ){
    int count = 0;
    vec3 folded = hc2_planeToSphere(xy);
    bool found = hc2_fold3d(folded, count);
    vec3 col = found ? ((count % 2 == 0) ? c1 : c2) : cLine;

    //fixed-width line (the original's fwidth AA does not survive path tracing)
    float edge = hc2_distABCD(folded);
    float aa = 0.5 * HC2_FLOOR_LINE_THICK;
    float lineMask = 1.0 - smoothstep(HC2_FLOOR_LINE_THICK - aa,
                                      HC2_FLOOR_LINE_THICK + aa, edge);
    return mix(col, cLine, lineMask);
}


// -----------------------------------------------------------------------------
// object interface
// -----------------------------------------------------------------------------

float sdf( vec3 p, HyperbolicHoneycomb2 obj ){
    return HC2_FUDGE * hc2_de(p, obj.foldIterations);
}

OBJECT_INIT(HyperbolicHoneycomb2)
OBJECT_LOCATORS(HyperbolicHoneycomb2)


Vector normalVec( Vector tv, HyperbolicHoneycomb2 obj ){
    vec3 q = toLocal(obj.frame, tv.pos);
    const float ep = 0.0001;
    vec2 e = vec2(1.0,-1.0)*0.5773;
    vec3 dir = e.xyy*sdf( q + e.xyy*ep, obj )
             + e.yyx*sdf( q + e.yyx*ep, obj )
             + e.yxy*sdf( q + e.yxy*ep, obj )
             + e.xxx*sdf( q + e.xxx*ep, obj );
    return Vector( tv.pos, dirToWorld(obj.frame, normalize(dir)) );
}


//standard flat-material setData (uses obj.mat); the scene overrides the color
OBJECT_SETDATA(HyperbolicHoneycomb2)
